#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Núcleo escrito de servicios y stacks (borrador de Claude, sin validar por Darío). Sin precios ni afirmaciones sobre proyectos de Darío: eso queda en "datos técnicos"."""
from lab_nucleo_skills import N

SV = {
 "vercel": N("Un servicio de hosting para frontends y funciones serverless, con deploy automático desde Git.",
  "Publicar un sitio con servidor, dominio y HTTPS a mano es una tarea aparte. Con Vercel, cada push a Git publica solo.",
  [("Deploy con cada push.", "Sin pasos manuales."), ("Previews por rama.", "Cada cambio tiene su link para revisar antes de publicar."), ("Dominio y HTTPS automáticos.", "Y funciones /api sin configurar un servidor.")],
  "Sitios estáticos, Next.js y proyectos con funciones /api que no necesitan un servidor siempre encendido.",
  "Para procesos que tienen que estar siempre corriendo (workers, cron largos) hay límites de tiempo por función y de uso en el plan gratuito. Revisá los precios vigentes antes de elegirlo."),
 "netlify": N("Un servicio de hosting de sitios estáticos con funciones, formularios y deploy desde Git.",
  "Un sitio estático no tiene dónde recibir un formulario ni dónde redirigir URLs sin armar un servidor.",
  [("Formularios sin backend.", "Los recibe el propio servicio."), ("Redirects simples.", "Y previews por cambio.")],
  "Sitios estáticos y JAMstack que necesitan un formulario o redirects sin programar servidor.",
  "Para una app con lógica de servidor más compleja o una base de datos, vas a necesitar otro servicio al lado."),
 "cloudflare-pages": N("Hosting de sitios estáticos sobre la red de Cloudflare, con Workers para lógica en el borde.",
  "Un sitio alojado en un solo lugar carga más lento para quien está lejos. Una red de distribución lo sirve desde un punto cercano.",
  [("Muy rápido en todo el mundo.", "Por la red de Cloudflare."), ("Dominio y DNS en el mismo lugar.", "Menos servicios para gestionar.")],
  "Sitios estáticos que tienen que cargar rápido en cualquier lugar, o cuando el dominio ya está en Cloudflare.",
  "Si tu proyecto depende de funciones tradicionales de Node, la lógica en el borde (Workers) funciona distinto y puede requerir adaptar el código."),
 "github-pages": N("Hosting gratuito de sitios estáticos directo desde un repositorio de GitHub.",
  "Para publicar un portfolio o una documentación no hace falta contratar nada: el repositorio ya es el sitio.",
  [("Gratis y simple.", "Se publica desde el repo."), ("Sin pasos extra.", "Ideal para empezar.")],
  "Portfolios, documentación y demos que no necesitan un servidor.",
  "Solo sirve contenido estático: no hay funciones de servidor ni base de datos. Para eso hace falta otro servicio."),
 "railway": N("Una plataforma para desplegar servidores Node, bases de datos y workers sin configurar infraestructura.",
  "Una API que tiene que estar siempre encendida (con un Express o tareas programadas) no encaja en el hosting de funciones serverless.",
  [("Servidores siempre activos.", "APIs y cron jobs."), ("Sin infraestructura propia.", "No hay que configurar máquinas.")],
  "APIs que necesitan estar siempre encendidas (Express, cron jobs) o que juntan servidor y base de datos.",
  "Para un sitio estático o una landing es más de lo que hace falta: alcanza con un hosting estático. Revisá el costo de un servicio siempre activo."),
 "render": N("Un servicio de hosting para servidores web, bases Postgres y sitios estáticos.",
  "Una API o un monolito necesita un lugar donde correr de forma permanente, con la base de datos cerca.",
  [("Servicios web y Postgres juntos.", "Y también sitios estáticos."), ("Alternativa a Railway.", "Con un modelo parecido.")],
  "APIs y aplicaciones monolíticas que necesitan un servidor permanente.",
  "Para sitios estáticos o funciones chicas hay opciones más simples. Revisá cómo se comporta el plan gratuito, que puede pausar los servicios cuando no hay tráfico."),
 "mongodb-atlas": N("MongoDB administrado en la nube: una base de datos de documentos tipo JSON que no hay que instalar ni mantener.",
  "Guardar contenido, usuarios o mensajes necesita una base de datos, y montar y mantener una propia es trabajo de infraestructura.",
  [("Documentos flexibles.", "Contenido, usuarios, mensajes y snapshots sin esquema rígido."), ("Administrado.", "Respaldos y disponibilidad los maneja el servicio."), ("Plan gratuito.", "Alcanza para empezar.")],
  "Aplicaciones con datos de forma variable: contenido, usuarios, mensajes, historiales.",
  "Si tus datos son muy relacionales (muchas tablas que se cruzan) una base SQL puede ser más cómoda. En serverless hay que reutilizar la conexión entre llamadas."),
 "supabase": N("Un servicio que junta Postgres, autenticación, almacenamiento de archivos y tiempo real.",
  "Una app con usuarios necesita login, base de datos y permisos. Armarlo todo a mano es mucho backend antes de la primera pantalla.",
  [("SQL de verdad.", "Datos relacionales con Postgres."), ("Reglas de seguridad por fila.", "Cada usuario ve solo lo suyo."), ("SDK simple.", "Se conecta con pocas líneas.")],
  "Apps con usuarios y datos relacionales sin armar un backend propio.",
  "Para un sitio sin usuarios ni datos dinámicos es más de lo que hace falta. Las reglas de seguridad por fila hay que escribirlas bien: un error expone datos."),
 "firebase": N("La suite de Google para apps: base de datos en tiempo real, autenticación, hosting y notificaciones.",
  "Una app que tiene que mostrar cambios al instante (un chat, un panel en vivo) necesita sincronizar datos en tiempo real.",
  [("Tiempo real.", "Los cambios llegan solos a todos los usuarios."), ("Login social rápido.", "Google y otros proveedores casi sin código.")],
  "Apps con tiempo real y login social, sobre todo móviles.",
  "Los datos relacionales y las consultas complejas son más incómodos que en SQL. Además, quedás atado al ecosistema de Google."),
 "clerk": N("Un servicio de autenticación listo para usar: login, registro, redes sociales, organizaciones y componentes de interfaz ya armados.",
  "El login parece simple y es una de las partes más delicadas: contraseñas, sesiones, recuperación de cuenta. Reinventarlo es un riesgo.",
  [("Login resuelto.", "Registro, sesiones y recuperación."), ("Componentes de UI.", "Formularios ya listos."), ("Organizaciones.", "Para SaaS con equipos.")],
  "Para no reinventar el login en un SaaS. Alternativas: Auth0, Supabase Auth, NextAuth/Auth.js.",
  "Para un sitio con un panel de un solo administrador, puede ser más de lo necesario. Los usuarios quedan en un servicio de terceros."),
 "resend": N("Una API para enviar emails transaccionales desde tu código: avisos de formularios, confirmaciones y recuperación de contraseña.",
  "Enviar mail desde un servidor propio termina muchas veces en spam. Un servicio especializado cuida que lleguen.",
  [("Pocas líneas de código.", "Un envío es una llamada a la API."), ("Plan gratuito.", "Alcanza para volúmenes bajos.")],
  "Avisos de formularios, confirmaciones de pedido o turno y recuperación de contraseña.",
  "No es para campañas masivas de marketing. Necesitás verificar el dominio del remitente para que los mails lleguen bien."),
 "formspree": N("Un backend de formularios: apuntás el formulario a su URL y los mensajes te llegan por mail.",
  "Un sitio estático no tiene servidor para recibir un formulario de contacto.",
  [("Sin programar servidor.", "Se configura en minutos."), ("Mensajes por mail.", "Llegan directo a tu casilla.")],
  "Sitios estáticos que necesitan un formulario de contacto sin programar un servidor.",
  "Si necesitás guardar los mensajes en tu propia base de datos o agregar lógica, conviene tener tu propio backend. Revisá los límites del plan gratuito."),
 "mercadopago": N("El servicio de pagos online de Mercado Pago para Argentina: checkout, links de pago y suscripciones.",
  "Cobrar en un sitio argentino significa aceptar tarjetas, dinero en cuenta y cuotas, medios que el cliente local ya usa y en los que confía.",
  [("Medios locales.", "Tarjetas, dinero en cuenta y cuotas."), ("Dos formas de integrarlo.", "Checkout Pro (redirige a Mercado Pago) o Checkout API (formulario propio)."), ("Confirmación por webhook.", "El pago se confirma con una notificación, no con la vuelta del cliente.")],
  "Tiendas y servicios que cobran en pesos a clientes de Argentina.",
  "Para cobrar en dólares o a clientes del exterior, Stripe suele ser mejor opción. Siempre hay que confirmar el pago por webhook y no por la página de retorno."),
 "stripe": N("Una plataforma de pagos y suscripciones a nivel internacional.",
  "Cobrar a clientes del exterior en otra moneda exige medios y reglas distintos a los locales.",
  [("Alcance internacional.", "Tarjetas de todo el mundo."), ("Suscripciones.", "Cobros recurrentes bien resueltos.")],
  "SaaS que cobran en dólares o a clientes del exterior.",
  "Para vender solo en Argentina, con cuotas y medios locales, Mercado Pago encaja mejor."),
 "tiendanube": N("Una plataforma de e-commerce líder en Latinoamérica, para armar una tienda propia sin programar.",
  "Programar una tienda desde cero es caro. Tienda Nube da catálogo, carrito y pagos listos, con integración a Mercado Libre y medios de pago locales.",
  [("Tienda sin programar.", "Se administra desde un panel."), ("Medios locales.", "Integración con pagos y con Mercado Libre.")],
  "Un comercio que quiere una tienda propia rápida y sin desarrollo a medida.",
  "Si necesitás una lógica propia (preventas con seña, calculadoras, paneles a medida), una tienda hecha a medida da más libertad. Dentro de la plataforma el diseño tiene límites."),
 "wordpress": N("El CMS más usado del mundo. Con WooCommerce también funciona como tienda.",
  "Quien tiene un sitio institucional o un blog necesita poder editar el contenido sin depender de un programador.",
  [("Editable por el cliente.", "Cualquier persona actualiza el contenido."), ("Muchos plugins.", "Para casi cualquier necesidad.")],
  "Institucionales y blogs que el cliente edita solo.",
  "Hay que mantener plugins y versión actualizados por seguridad. Para un diseño muy a medida o una app, resulta más pesado que una solución a medida."),
 "sanity": N("Un headless CMS con editor personalizable y API de contenido.",
  "En un sitio hecho a medida, el contenido queda dentro del código. Un CMS separado permite que otra persona lo edite sin tocarlo.",
  [("Editor a medida.", "Se adapta a la estructura de tu contenido."), ("Contenido por API.", "Se consume desde Astro, Next u otro.")],
  "Contenido editable para sitios hechos a medida (Astro, Next).",
  "Para un sitio chico que cambia poco, es más complejidad de la necesaria. Requiere un desarrollador para conectarlo con el sitio."),
 "ga4": N("Google Analytics 4: medición de tráfico y conversiones.",
  "Sin medir, no sabés de dónde vienen las visitas ni qué páginas o acciones logran resultados.",
  [("Origen del tráfico.", "Desde dónde llegan."), ("Conversiones.", "Qué acciones cumplen el objetivo."), ("Gratis.", "Y es el estándar del mercado.")],
  "Saber de dónde vienen las visitas y qué convierte.",
  "Requiere aviso de cookies según el público. Si solo querés métricas básicas y respetar la privacidad, una alternativa liviana es Plausible."),
 "plausible": N("Una herramienta de analítica simple, liviana y respetuosa de la privacidad.",
  "Los banners de cookies molestan y las herramientas de analítica grandes son más complejas de lo que muchos sitios necesitan.",
  [("Sin cookies ni banners.", "Métricas básicas sin pedir permiso."), ("Liviana y clara.", "Un solo panel con lo esencial.")],
  "Sitios que quieren métricas básicas sin cookies ni banners.",
  "No tiene la profundidad de GA4 (embudos, audiencias, integración con anuncios). Revisá las condiciones y el costo vigentes."),
 "clarity": N("Microsoft Clarity: mapas de calor y grabaciones de sesiones, gratis.",
  "Los números dicen cuántos visitaron una página pero no por qué se fueron. Ver dónde hacen clic y dónde abandonan lo explica.",
  [("Mapas de calor.", "Dónde se hace clic y hasta dónde se baja."), ("Grabaciones.", "Se ve cómo navega cada visita."), ("Gratis.", "Sin costo para empezar.")],
  "Ver dónde hacen clic y dónde abandonan los usuarios, para mejorar una página que no convierte.",
  "Con muy poco tráfico, los patrones no son confiables. Las grabaciones pueden mostrar datos personales: configurá el enmascarado y avisalo en tu política de privacidad."),
 "cloudinary": N("Un servicio de almacenamiento y transformación de imágenes y videos al vuelo.",
  "Servir la misma imagen enorme a todos los dispositivos hace lento un sitio. Cada pantalla necesita su tamaño y formato.",
  [("Tamaño y formato justos.", "WebP o AVIF según el dispositivo."), ("Transformaciones al vuelo.", "Recortes y ajustes por URL.")],
  "Sitios con muchas imágenes o galerías, donde el peso afecta la velocidad.",
  "Para un sitio con pocas imágenes ya optimizadas, es de más. Revisá los límites del plan gratuito."),
 "claude-api": N("La API de Anthropic para usar los modelos de Claude desde tu propio código: generar y analizar texto, código e imágenes.",
  "Muchas tareas repetitivas con texto (redactar, resumir, clasificar) se pueden automatizar si el modelo está dentro de tu app.",
  [("Texto a escala.", "Redactar, resumir y clasificar."), ("Asistentes propios.", "Dentro de tu app o tu panel.")],
  "Redactar títulos y descripciones, resumir, clasificar y armar asistentes dentro de una aplicación.",
  "Cada llamada tiene costo y no siempre acierta: conviene que una persona revise lo que se publica. Es de nivel avanzado."),
 "groq": N("Un servicio de inferencia muy rápida de modelos abiertos (Llama y otros).",
  "Para tareas de IA simples, esperar o pagar un modelo grande es innecesario. Un modelo abierto rápido alcanza.",
  [("Muy rápido.", "Respuestas casi instantáneas."), ("Barato y con plan gratuito.", "Para tareas livianas.")],
  "Tareas de IA rápidas y baratas, como sugerir un título o clasificar un texto corto.",
  "Para tareas que exigen mucho razonamiento o textos largos, un modelo más grande rinde mejor."),
 "sentry": N("Monitoreo de errores para frontend y backend.",
  "Cuando algo falla en producción, nadie avisa: el usuario simplemente se va. Sentry registra el error con los datos para encontrarlo.",
  [("Te enterás primero.", "Antes de que lo reporten."), ("Contexto del error.", "Qué pasó y dónde.")],
  "Aplicaciones en producción con usuarios reales, para detectar fallos rápido.",
  "Para una landing estática casi no hay qué monitorear. Hay que configurar alertas con criterio para no recibir ruido."),
 "nic-ar": N("NIC Argentina: el registro oficial de dominios .ar y .com.ar.",
  "Un negocio local necesita un dominio propio. Registrarlo en el organismo oficial evita intermediarios.",
  [("Registro oficial.", "Directo con el organismo."), ("Dominio local.", "El .com.ar da confianza al cliente argentino.")],
  "Registrar el dominio .com.ar de un negocio local. Después se apunta el DNS al hosting (Vercel, Netlify, etc.).",
  "Para un proyecto pensado para el exterior, un .com o similar puede ser mejor."),
}

ST = {
 "vanilla": N("La web sin frameworks: HTML, CSS y JavaScript, lo que el navegador entiende de forma nativa.",
  "Cada framework suma peso y pasos de compilación. Para muchos sitios chicos no hacen falta.",
  [("Sin pasos de compilación.", "Se abre el archivo y funciona."), ("Mínimo peso.", "Carga rápido."), ("Base para todo.", "Lo que se aprende acá sirve en cualquier otro stack.")],
  "Landings, portfolios y herramientas internas chicas. Es el punto de partida obligado para aprender.",
  "Para aplicaciones con mucha interactividad y estado, sin un framework el código se vuelve difícil de mantener."),
 "react-vite": N("React, la librería de componentes más usada, con Vite como herramienta de desarrollo rápida.",
  "En una interfaz con muchas partes que cambian, actualizar la pantalla a mano se vuelve inmanejable. Los componentes ordenan eso.",
  [("Componentes reutilizables.", "Cada parte de la interfaz es independiente."), ("Ecosistema enorme.", "Librerías y ayuda para casi todo."), ("Desarrollo rápido.", "Vite recarga al instante.")],
  "Aplicaciones interactivas y dashboards.",
  "Para un sitio de contenido que necesita buen SEO, funciona mejor un framework con renderizado en servidor. Para una landing es excesivo."),
 "nextjs": N("Un framework de React con rutas, renderizado en servidor (SSR), generación estática (SSG) y API integradas.",
  "Una app de React sola tiene malos resultados en buscadores y necesita un servidor aparte. Next.js resuelve las dos cosas.",
  [("SEO.", "Las páginas llegan armadas al buscador."), ("Todo en un proyecto.", "Interfaz, rutas y API."), ("Híbrido.", "Páginas estáticas y dinámicas juntas.")],
  "E-commerce a medida, SaaS con buen SEO y sitios híbridos.",
  "Para una landing o un portfolio simple es demasiado. La curva de aprendizaje es media a alta."),
 "astro": N("Un framework orientado a contenido: HTML estático por defecto y JavaScript solo donde hace falta.",
  "Muchos sitios de contenido cargan JavaScript que no usan. Astro manda lo mínimo y el sitio carga más rápido.",
  [("Muy rápido.", "Casi sin JavaScript por defecto."), ("Combina librerías.", "Usa componentes de React, Vue u otros."), ("Aprendizaje bajo a medio.", "Se parece al HTML.")],
  "Blogs, documentación, sitios institucionales y landings.",
  "Para aplicaciones muy interactivas, con estado compartido entre muchas pantallas, un framework de aplicaciones encaja mejor."),
 "vue": N("Una alternativa a React con una sintaxis más cercana al HTML. Nuxt le agrega renderizado en servidor y rutas.",
  "Hay quienes encuentran más natural trabajar con plantillas parecidas a HTML que con JavaScript que genera la interfaz.",
  [("Plantillas claras.", "Se parece al HTML."), ("Curva suave.", "Baja a media."), ("Nuxt.", "Agrega SSR y rutas.")],
  "Equipos que prefieren plantillas, para aplicaciones y sitios.",
  "El ecosistema y la demanda laboral son menores que los de React. Si buscás empleo, tené en cuenta qué pide el mercado."),
 "sveltekit": N("Un framework con un compilador que genera muy poco JavaScript.",
  "Las librerías envían al navegador el código del propio framework. Svelte lo resuelve al compilar y manda menos.",
  [("Livianas y rápidas.", "Poco JavaScript en el navegador."), ("Sintaxis simple.", "Curva baja a media.")],
  "Aplicaciones rápidas y livianas.",
  "Menos ecosistema y comunidad que React o Vue: hay menos librerías listas y menos oferta laboral."),
 "node-express": N("JavaScript en el servidor (Node.js) con Express, el framework de APIs más difundido.",
  "Un sitio necesita lógica de servidor: recibir datos, hablar con otras APIs, guardar información. Con Node se hace en el mismo lenguaje que el frontend.",
  [("Un solo lenguaje.", "JavaScript de punta a punta."), ("Muy difundido.", "Mucha documentación."), ("Integraciones.", "APIs y automatizaciones.")],
  "APIs REST, integraciones y automatizaciones.",
  "No siempre hace falta Express: las funciones serverless de Node cubren muchos casos sin un servidor siempre encendido."),
 "mern": N("Un stack completo en JavaScript de punta a punta: MongoDB, Express, React y Node.",
  "Usar un lenguaje distinto en cada capa duplica lo que hay que aprender. MERN usa JavaScript en todas.",
  [("Un solo lenguaje.", "Del navegador a la base de datos."), ("Datos flexibles.", "MongoDB no pide un esquema fijo.")],
  "SaaS y aplicaciones con datos flexibles.",
  "Para datos muy relacionales una base SQL es más cómoda. Para un sitio de contenido con SEO, React puro necesita ayuda extra (como Next.js)."),
 "tailwind": N("CSS con clases utilitarias directamente en el HTML.",
  "Escribir CSS aparte lleva a nombres de clases y hojas de estilo que crecen sin control. Con utilidades se diseña en el mismo lugar.",
  [("Iteración rápida.", "Se prueba un diseño sin salir del HTML."), ("Consistencia.", "Los valores salen de un sistema de diseño.")],
  "Iterar diseño rápido y mantener consistencia con tokens. Combina con shadcn/ui, React y Astro.",
  "Si el proyecto es un sitio chico en HTML y CSS plano, no hace falta. El HTML queda cargado de clases."),
 "shadcn": N("Componentes accesibles (basados en Radix) que se copian a tu proyecto y se adaptan con Tailwind.",
  "Una interfaz con botones, tablas y formularios bien resueltos lleva tiempo. Acá ya están hechos y accesibles.",
  [("Accesibles.", "Teclado y lectores de pantalla resueltos."), ("Son tuyos.", "El código se copia y se modifica."), ("Prolijos.", "Buen aspecto de entrada.")],
  "Dashboards y SaaS con una interfaz prolija sin diseñar cada componente.",
  "Sin personalizar, todas las apps que lo usan se parecen. Requiere React y Tailwind."),
}
