#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Ejemplos personalizados por tipo de negocio (como Brasa): un sitio diseñado por rubro, de un negocio INVENTADO, con identidad propia
y su sección más característica funcionando. Son demos hechas para la ficha (no clientes reales).
Datos de cada negocio: los del preset de cada ficha (nombre, titular, ítems, precios, funciones).
Salida: frontend/prog-ejemplos/negocios/<id>.html (+ .webp con tools/lab_demos_miniaturas.py --negocios). Uso: python3 tools/lab_demos_negocios.py
"""
from pathlib import Path
OUT = Path(__file__).resolve().parent.parent / "frontend" / "prog-ejemplos" / "negocios"

BASE = """*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}
body{font-family:var(--f2);color:var(--ink);background:var(--bg);line-height:1.55;-webkit-font-smoothing:antialiased}
a{color:inherit;text-decoration:none}.w{max-width:1100px;margin:0 auto;padding:0 24px}
.btn{display:inline-flex;align-items:center;gap:8px;padding:13px 22px;font:700 15px var(--f2);border:0;cursor:pointer;background:var(--pri);color:var(--pri-ink);border-radius:var(--r);transition:transform .15s,filter .15s}
.btn:hover{filter:brightness(1.07)}.btn:active{transform:scale(.97)}.btn.o{background:transparent;color:var(--ink);box-shadow:inset 0 0 0 2px currentColor}
.sec{padding:64px 0}h1,h2,h3{font-family:var(--f1)}h2{font-size:clamp(28px,4vw,40px);line-height:1.08;letter-spacing:-.02em;margin-bottom:22px}
.fw{position:fixed;right:16px;bottom:16px;z-index:50;width:52px;height:52px;border-radius:50%;background:#25d366;color:#fff;display:grid;place-items:center;font-size:24px;box-shadow:0 8px 22px rgba(0,0,0,.28);cursor:pointer;border:0}
.demo{position:fixed;left:12px;bottom:12px;z-index:50;font:600 11px system-ui;background:rgba(20,20,20,.82);color:#fff;padding:6px 10px;border-radius:8px}
.toast{position:fixed;left:50%;bottom:78px;transform:translate(-50%,20px);background:#1a1a1a;color:#fff;font:600 13px system-ui;padding:11px 16px;border-radius:10px;opacity:0;pointer-events:none;transition:.25s;max-width:min(92vw,420px);text-align:center;z-index:60}.toast.on{opacity:1;transform:translate(-50%,0)}
footer{padding:28px 0;font-size:13px;opacity:.7;text-align:center}
@media(max-width:820px){.g2,.g3,.g4{grid-template-columns:1fr!important}}
@media(prefers-reduced-motion:reduce){*{transition:none!important;animation:none!important}}
"""
JS = """<div class="toast" id="tt" role="status"></div><script>
function wa(m){var t=document.getElementById('tt');t.textContent='Se abriría WhatsApp con: «'+m+'»';t.classList.add('on');clearTimeout(window._t);window._t=setTimeout(function(){t.classList.remove('on')},3800)}
document.addEventListener('click',function(e){var a=e.target.closest('[data-wa]');if(a){e.preventDefault();wa(a.dataset.wa)}});
</script>"""
WA = '<button class="fw" data-wa="Hola, quiero hacer una consulta" aria-label="WhatsApp">✆</button><div class="demo">Negocio inventado · demo hecha para esta ficha</div>'

def page(title, fonts, tokens, css, body, js=""):
    root = ":root{" + ";".join(f"--{k}:{v}" for k, v in tokens.items()) + "}"
    return ('<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' + title + ' · ejemplo</title>'
            '<link href="https://fonts.googleapis.com/css2?' + fonts + '&display=swap" rel="stylesheet"><style>' + root + BASE + css + '</style></head><body>'
            + body + WA + JS + js + '</body></html>')

B = {}

# ───────── Delivery · Rotisería Don Tito ─────────
B["delivery"] = page("Rotisería Don Tito", "family=Archivo+Black&family=Archivo:wght@400;600;700",
    dict(bg="#fff4e0", ink="#2a1a0a", pri="#ff5a1f", **{"pri-ink": "#fff"}, r="999px", f1="'Archivo Black',sans-serif", f2="Archivo,sans-serif"),
    """.top{background:#2a1a0a;color:#ffe9c7;font-size:13px;text-align:center;padding:8px}nav{display:flex;justify-content:space-between;align-items:center;padding:16px 0}nav b{font:900 26px var(--f1);color:#ff5a1f;letter-spacing:-.03em}nav span{font-size:14px;font-weight:600}
.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:30px;align-items:center;padding:30px 0 56px}.hero h1{font-size:clamp(44px,7vw,84px);line-height:.92;letter-spacing:-.04em}.hero h1 em{font-style:normal;color:#ff5a1f}.hero p{font-size:19px;margin:18px 0 26px;max-width:36ch}
.plate{aspect-ratio:1;border-radius:50%;background:radial-gradient(circle at 35% 30%,#ffd37a,#ff8a3d 55%,#d94a0e);display:grid;place-items:center;box-shadow:0 30px 60px rgba(217,74,14,.35);position:relative}.plate::after{content:"30'";position:absolute;right:2%;top:6%;background:#2a1a0a;color:#ffe9c7;font:900 28px var(--f1);width:86px;height:86px;border-radius:50%;display:grid;place-items:center;transform:rotate(12deg)}.plate span{font-size:110px}
.menu{display:grid;grid-template-columns:1.5fr 1fr;gap:26px;align-items:start}.dish{display:flex;gap:14px;align-items:center;background:#fff;border-radius:22px;padding:14px;margin-bottom:12px;box-shadow:0 6px 18px rgba(42,26,10,.07)}.dish i{width:64px;height:64px;border-radius:18px;background:linear-gradient(135deg,#ffd37a,#ff8a3d);display:grid;place-items:center;font-size:30px;font-style:normal}.dish div{flex:1}.dish b{display:block;font-size:17px}.dish small{opacity:.7}.dish strong{font:900 18px var(--f1)}.dish button{width:40px;height:40px;border-radius:50%;border:0;background:#ff5a1f;color:#fff;font-size:22px;cursor:pointer}
.cart{position:sticky;top:16px;background:#2a1a0a;color:#ffe9c7;border-radius:26px;padding:24px}.cart h3{font-size:22px;margin-bottom:12px}.cart ul{list-style:none;min-height:60px;font-size:15px}.cart li{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px dashed rgba(255,233,199,.25)}.cart .tot{display:flex;justify-content:space-between;font:900 24px var(--f1);margin:16px 0}.cart .btn{width:100%;justify-content:center;margin-bottom:8px}.cart .btn.mp{background:#009ee3}
.zonas{background:#ff5a1f;color:#fff;padding:36px 0;text-align:center;font:900 28px var(--f1)}""",
    '<div class="top">Pedidos de lunes a domingo de 11 a 23 h · Envío gratis desde $ 20.000</div><div class="w"><nav><b>Don Tito</b><span>📍 Villa Crespo · 30 min</span></nav>'
    '<section class="hero"><div><h1>Comida casera, <em>lista en 30 minutos.</em></h1><p>Armá tu pedido, pagalo por Mercado Pago y te lo llevamos caliente.</p><a href="#menu" class="btn">Hacer mi pedido ↓</a></div><div class="plate"><span>🍗</span></div></section></div>'
    '<section class="sec" id="menu"><div class="w"><h2>Menú del día</h2><div class="menu"><div id="dishes"></div><aside class="cart"><h3>Tu pedido</h3><ul id="ci"><li style="opacity:.6">Todavía no agregaste nada</li></ul><div class="tot"><span>Total</span><span id="ct">$ 0</span></div><button class="btn mp" id="pay">Pagar con Mercado Pago</button><button class="btn" id="send">Enviar por WhatsApp</button></aside></div></div></section>'
    '<div class="zonas">Zonas de envío: Villa Crespo · Almagro · Caballito · Palermo</div><footer><div class="w">Rotisería Don Tito · Av. Corrientes 5120</div></footer>',
    """<script>(function(){var D=[['Milanesa napolitana','Con papas fritas',9800,'🥩'],['Tarta de jamón y queso','Porción grande',5200,'🥧'],['Pollo al horno','Con puré',8600,'🍗'],['Empanadas (docena)','Carne, JyQ o humita',15800,'🥟']],C={};var el=document.getElementById('dishes');el.innerHTML=D.map(function(d,i){return'<div class="dish"><i>'+d[3]+'</i><div><b>'+d[0]+'</b><small>'+d[1]+'</small></div><strong>$ '+d[2].toLocaleString('es-AR')+'</strong><button data-i="'+i+'" aria-label="Agregar '+d[0]+'">+</button></div>'}).join('');
function r(){var k=Object.keys(C),t=0;document.getElementById('ci').innerHTML=k.length?k.map(function(i){t+=D[i][2]*C[i];return'<li><span>'+C[i]+' × '+D[i][0]+'</span><span>$ '+(D[i][2]*C[i]).toLocaleString('es-AR')+'</span></li>'}).join(''):'<li style="opacity:.6">Todavía no agregaste nada</li>';document.getElementById('ct').textContent='$ '+t.toLocaleString('es-AR');return t}
el.addEventListener('click',function(e){var b=e.target.closest('button');if(b){C[b.dataset.i]=(C[b.dataset.i]||0)+1;r()}});
document.getElementById('send').onclick=function(){var t=r();wa(t?'Hola Don Tito, quiero: '+Object.keys(C).map(function(i){return C[i]+' '+D[i][0]}).join(', ')+'. Total $ '+t.toLocaleString('es-AR'):'Hola, quiero hacer un pedido')};
document.getElementById('pay').onclick=function(){var t=r();wa(t?'Pago de $ '+t.toLocaleString('es-AR')+' con Mercado Pago (simulado en la demo)':'Primero agregá algo al pedido')}})()</script>""")

# ───────── Inmobiliaria · Aguirre Propiedades ─────────
B["inmobiliaria"] = page("Aguirre Propiedades", "family=Fraunces:opsz,wght@9..144,500;9..144,700&family=Inter:wght@400;500;600",
    dict(bg="#faf6ef", ink="#14233b", pri="#14233b", **{"pri-ink": "#fff"}, r="6px", f1="Fraunces,serif", f2="Inter,sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:center;padding:20px 0}nav b{font:700 24px var(--f1)}nav div{display:flex;gap:26px;font-size:14px;font-weight:500}
.hero{padding:40px 0 20px}.hero h1{font-size:clamp(40px,6vw,72px);line-height:1;letter-spacing:-.03em;max-width:15ch}.hero p{font-size:18px;margin:16px 0 28px;opacity:.75}
.search{background:#fff;border-radius:14px;padding:14px;display:grid;grid-template-columns:repeat(4,1fr) auto;gap:10px;box-shadow:0 16px 40px rgba(20,35,59,.12);max-width:900px}.search select{border:1px solid #e3ddd0;border-radius:8px;padding:13px;font:500 14px var(--f2);background:#fff}
.chips{display:flex;gap:8px;margin:16px 0 0}.chips button{border:1px solid #d9d1c0;background:transparent;border-radius:99px;padding:7px 14px;font:600 13px var(--f2);cursor:pointer}.chips button.on{background:#14233b;color:#fff;border-color:#14233b}
.props{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.prop{background:#fff;border-radius:14px;overflow:hidden;box-shadow:0 6px 20px rgba(20,35,59,.08)}.prop .im{height:170px;position:relative;display:grid;place-items:end start;padding:12px}.prop .im span{background:#14233b;color:#fff;font:700 11px var(--f2);padding:5px 10px;border-radius:99px;letter-spacing:.06em;text-transform:uppercase}.prop .tx{padding:16px}.prop b{display:block;font:700 22px var(--f1)}.prop small{opacity:.7;font-size:13px}.prop .pr{display:flex;justify-content:space-between;align-items:center;margin-top:12px}.prop[hidden]{display:none}
.tas{background:#14233b;color:#fff;border-radius:22px;padding:44px;display:grid;grid-template-columns:1fr 1fr;gap:30px;align-items:center}.tas h2{color:#fff}.tas form{display:grid;gap:10px}.tas input,.tas select{padding:14px;border-radius:8px;border:0;font:500 15px var(--f2)}.tas .btn{background:#e2b857;color:#14233b;justify-content:center}""",
    '<div class="w"><nav><b>Aguirre Propiedades</b><div><a>Comprar</a><a>Alquilar</a><a>Tasaciones</a><a>Contacto</a></div></nav><section class="hero"><h1>Tu próxima casa está en Belgrano.</h1><p>Hace 26 años acompañamos a familias del barrio a comprar, vender y alquilar con tranquilidad.</p>'
    '<div class="search"><select aria-label="Operación"><option>Comprar</option><option>Alquilar</option></select><select aria-label="Zona"><option>Belgrano</option><option>Núñez</option><option>Colegiales</option></select><select aria-label="Ambientes"><option>Ambientes</option><option>1</option><option>2</option><option>3+</option></select><select aria-label="Precio"><option>Hasta USD 300 k</option><option>Hasta USD 500 k</option></select><button class="btn">Buscar</button></div>'
    '<div class="chips" id="ch"><button class="on" data-f="todas">Todas</button><button data-f="dep">Departamentos</button><button data-f="casa">Casas</button></div></section></div>'
    '<section class="sec"><div class="w"><h2>Propiedades destacadas</h2><div class="props" id="pp"></div></div></section>'
    '<div class="w"><div class="tas"><div><h2>¿Cuánto vale tu propiedad?</h2><p style="opacity:.8">Te la tasamos sin cargo, en 48 horas, con comparables reales de la zona.</p></div><form onsubmit="wa(\'Pedido de tasación enviado (demo)\');return false"><input placeholder="Dirección de la propiedad" aria-label="Dirección"><select aria-label="Tipo"><option>Departamento</option><option>Casa</option><option>Local</option></select><input placeholder="Tu WhatsApp" aria-label="WhatsApp"><button class="btn">Pedir tasación</button></form></div></div><footer><div class="w">Aguirre Propiedades · Matrícula CUCICBA 1234 · Av. Cabildo 2100</div></footer>',
    """<script>(function(){var P=[['3 ambientes con balcón','Departamento · 78 m² · Belgrano','USD 218.000','dep','linear-gradient(135deg,#9fb6d6,#5a7aa6)'],['Casa con jardín','Casa · 210 m² · Núñez','USD 465.000','casa','linear-gradient(135deg,#a9c9a0,#5f8f5a)'],['Monoambiente a estrenar','Departamento · 34 m² · Colegiales','USD 96.000','dep','linear-gradient(135deg,#e8c9a0,#c08a4e)'],['2 ambientes luminoso','Departamento · 52 m² · Belgrano','USD 149.000','dep','linear-gradient(135deg,#c8b6e0,#8a6fb8)'],['Casa reciclada','Casa · 160 m² · Colegiales','USD 380.000','casa','linear-gradient(135deg,#e0b4a6,#b8604a)'],['4 ambientes con cochera','Departamento · 112 m² · Núñez','USD 295.000','dep','linear-gradient(135deg,#a6d4d8,#4f9aa3)']];
document.getElementById('pp').innerHTML=P.map(function(p){return'<article class="prop" data-t="'+p[3]+'"><div class="im" style="background:'+p[4]+'"><span>En venta</span></div><div class="tx"><b>'+p[0]+'</b><small>'+p[1]+'</small><div class="pr"><strong>'+p[2]+'</strong><a class="btn" style="padding:9px 14px;font-size:13px" data-wa="Hola, me interesa: '+p[0]+'">Consultar</a></div></div></article>'}).join('');
document.getElementById('ch').onclick=function(e){var b=e.target.closest('button');if(!b)return;this.querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b)});document.querySelectorAll('.prop').forEach(function(a){a.hidden=b.dataset.f!=='todas'&&a.dataset.t!==b.dataset.f})}})()</script>""")

# ───────── Consultorio · Rivas ─────────
B["consultorio"] = page("Consultorio Odontológico Rivas", "family=Figtree:wght@400;500;600;700;800",
    dict(bg="#f4fbfa", ink="#0c2f33", pri="#0e8c8c", **{"pri-ink": "#fff"}, r="12px", f1="Figtree,sans-serif", f2="Figtree,sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:center;padding:18px 0}nav b{font-size:20px;display:flex;align-items:center;gap:8px}nav b i{width:30px;height:30px;border-radius:9px;background:#0e8c8c;display:grid;place-items:center;color:#fff;font-style:normal}nav div{display:flex;gap:24px;font-size:14px;font-weight:600}
.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:36px;align-items:center;padding:30px 0 50px}.hero h1{font-size:clamp(38px,5.5vw,62px);line-height:1.02;letter-spacing:-.035em}.hero p{font-size:18px;margin:16px 0 26px;opacity:.75;max-width:40ch}.hero .row{display:flex;gap:12px;flex-wrap:wrap}.hero .proof{display:flex;gap:22px;margin-top:28px;font-size:14px}.hero .proof b{display:block;font-size:26px;color:#0e8c8c}
.card{background:#fff;border-radius:22px;padding:26px;box-shadow:0 20px 50px rgba(14,140,140,.14)}.card h3{font-size:20px;margin-bottom:4px}.days{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:16px 0}.days button,.slots button{border:1.5px solid #cfe6e4;background:#fff;border-radius:10px;padding:10px 4px;font:600 14px var(--f2);cursor:pointer}.days button.on,.slots button.on{background:#0e8c8c;color:#fff;border-color:#0e8c8c}.slots{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:16px}.slots button.off{opacity:.35;text-decoration:line-through;cursor:not-allowed}.card .btn{width:100%;justify-content:center}.sel{font-size:14px;margin:6px 0 14px;font-weight:600}
.esp{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.esp article{background:#fff;border-radius:18px;padding:24px;border:1px solid #d9eeec}.esp i{width:46px;height:46px;border-radius:14px;background:#d9f2f0;display:grid;place-items:center;font-size:22px;font-style:normal;margin-bottom:12px}.esp b{font-size:18px}.esp p{font-size:14px;opacity:.7;margin-top:4px}
.team{display:flex;gap:20px;align-items:center;background:#0c2f33;color:#fff;border-radius:22px;padding:30px}.team i{width:84px;height:84px;border-radius:50%;background:linear-gradient(135deg,#7fd4d0,#0e8c8c);display:grid;place-items:center;font:800 28px var(--f1);font-style:normal;flex:none}.team p{opacity:.8;font-size:15px}
details{background:#fff;border-radius:14px;padding:16px 20px;margin-bottom:10px;border:1px solid #d9eeec}summary{font-weight:700;cursor:pointer}details p{margin-top:8px;opacity:.75;font-size:15px}""",
    '<div class="w"><nav><b><i>✚</i>Consultorio Rivas</b><div><a>Especialidades</a><a>Equipo</a><a>Preguntas</a><a>Cómo llegar</a></div></nav>'
    '<section class="hero"><div><h1>Tu sonrisa, en buenas manos.</h1><p>Odontología general, ortodoncia e implantes en Caballito. Atendemos con turno, sin esperas.</p><div class="row"><a class="btn" href="#turno">Sacar turno</a><a class="btn o" data-wa="Hola, quiero consultar por un tratamiento">Escribir por WhatsApp</a></div><div class="proof"><div><b>4,9 ★</b>240 reseñas</div><div><b>12 años</b>en el barrio</div><div><b>Obras sociales</b>OSDE, Swiss, Galeno</div></div></div>'
    '<div class="card" id="turno"><h3>Reservá tu turno</h3><p style="font-size:14px;opacity:.7">Elegí día y horario. Te confirmamos por WhatsApp.</p><div class="days" id="dd"></div><div class="slots" id="ss"></div><p class="sel" id="sl">Elegí un día y un horario</p><button class="btn" id="cf">Confirmar turno</button></div></section></div>'
    '<section class="sec" style="background:#e9f6f5"><div class="w"><h2>Especialidades</h2><div class="esp"><article><i>🦷</i><b>Limpieza y control</b><p>Revisión completa y limpieza profunda.</p></article><article><i>😁</i><b>Ortodoncia</b><p>Brackets y alineadores invisibles.</p></article><article><i>🔩</i><b>Implantes</b><p>Con tomografía 3D y plan por etapas.</p></article></div></div></section>'
    '<section class="sec"><div class="w"><div class="team"><i>MR</i><div><h3 style="font-size:22px">Dra. Marta Rivas · M.P. 12.345</h3><p>Odontóloga (UBA) con posgrado en implantología. Cada tratamiento se explica antes de empezar y se presupuesta por escrito.</p></div></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w" style="max-width:760px"><h2>Preguntas frecuentes</h2><details open><summary>¿Atienden por obra social?</summary><p>Sí: OSDE, Swiss Medical y Galeno. Consultanos tu plan por WhatsApp.</p></details><details><summary>¿Cuánto dura la primera consulta?</summary><p>Unos 30 minutos: revisión, diagnóstico y presupuesto.</p></details><details><summary>¿Dónde están?</summary><p>Av. Rivadavia 5400, Caballito. A dos cuadras del subte A.</p></details></div></section><footer><div class="w">Consultorio Odontológico Rivas · Lun a Vie 9 a 19 h</div></footer>',
    """<script>(function(){var dd=document.getElementById('dd'),ss=document.getElementById('ss'),sl=document.getElementById('sl'),D=['Lun 6','Mar 7','Mié 8','Jue 9','Vie 10'],H=['09:00','10:30','12:00','15:00','16:30','18:00'],d=null,h=null;
dd.innerHTML=D.map(function(x,i){return'<button data-i="'+i+'">'+x+'</button>'}).join('');ss.innerHTML=H.map(function(x,i){return'<button data-h="'+x+'"'+(i===1?' class="off"':'')+'>'+x+'</button>'}).join('');
function u(){sl.textContent=d!==null&&h?'Turno: '+D[d]+' a las '+h:'Elegí un día y un horario'}
dd.onclick=function(e){var b=e.target.closest('button');if(!b)return;d=+b.dataset.i;dd.querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b)});u()};
ss.onclick=function(e){var b=e.target.closest('button');if(!b||b.classList.contains('off'))return;h=b.dataset.h;ss.querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b)});u()};
document.getElementById('cf').onclick=function(){wa(d!==null&&h?'Turno solicitado para '+D[d]+' a las '+h:'Primero elegí día y horario')}})()</script>""")

# ───────── Estudio contable · Ferrari & Asociados ─────────
B["estudio"] = page("Estudio Ferrari & Asociados", "family=Newsreader:ital,opsz,wght@0,6..72,500;0,6..72,700;1,6..72,500&family=IBM+Plex+Sans:wght@400;500;600",
    dict(bg="#f6f3ec", ink="#171b26", pri="#1a2744", **{"pri-ink": "#fff"}, r="2px", f1="Newsreader,serif", f2="'IBM Plex Sans',sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:baseline;padding:22px 0;border-bottom:1px solid #171b26}nav b{font:700 26px var(--f1)}nav b em{font-weight:500}nav div{display:flex;gap:26px;font-size:13px;letter-spacing:.08em;text-transform:uppercase}
.hero{display:grid;grid-template-columns:1.3fr .7fr;gap:50px;padding:56px 0 50px;border-bottom:1px solid #171b26}.hero h1{font-size:clamp(46px,7vw,92px);line-height:.95;letter-spacing:-.035em;font-style:italic;font-weight:500}.hero p{font-size:18px;margin:22px 0 28px;max-width:44ch}.hero aside{border-left:1px solid #171b26;padding-left:28px;align-self:end;font-size:14px}.hero aside b{font:700 44px var(--f1);display:block}
.srv{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #171b26;border-left:1px solid #171b26}.srv article{padding:28px;border-right:1px solid #171b26;border-bottom:1px solid #171b26}.srv small{font:600 12px var(--f2);letter-spacing:.1em;text-transform:uppercase;opacity:.6}.srv h3{font-size:28px;margin:6px 0}.srv p{font-size:15px;opacity:.78}
.blog article{display:grid;grid-template-columns:110px 1fr auto;gap:20px;padding:18px 0;border-bottom:1px solid #cfc9b9;align-items:baseline}.blog small{font:600 12px var(--f2);opacity:.6;letter-spacing:.08em;text-transform:uppercase}.blog b{font:500 22px var(--f1)}
.form{background:#1a2744;color:#fff;padding:44px;display:grid;grid-template-columns:1fr 1fr;gap:34px}.form h2{color:#fff}.form form{display:grid;gap:10px}.form select,.form input,.form textarea{padding:13px;border:0;font:400 15px var(--f2);border-radius:2px}.form .btn{background:#d9b25a;color:#1a2744;justify-content:center}""",
    '<div class="w"><nav><b>Ferrari <em>&amp; Asociados</em></b><div><a>Servicios</a><a>Novedades</a><a>Contacto</a></div></nav><section class="hero"><div><h1>Tus números, en orden.</h1><p>Contadores públicos matriculados. Monotributo, sociedades y sueldos para pymes y profesionales, con un solo interlocutor y respuestas en el día.</p><a class="btn" href="#consulta">Hacer una consulta</a></div><aside><b>28 años</b>de trayectoria<br><br><b>+450</b>clientes activos</aside></section>'
    '<section class="sec"><h2>Servicios</h2><div class="srv"><article><small>01</small><h3>Monotributo</h3><p>Alta, recategorización, facturación electrónica y control de topes.</p></article><article><small>02</small><h3>Sociedades</h3><p>Constitución de SRL y SAS, balances, impuestos y asambleas.</p></article><article><small>03</small><h3>Sueldos</h3><p>Liquidación, cargas sociales y legajos de tu equipo.</p></article></div></section>'
    '<section class="sec" style="padding-top:0"><h2>Novedades impositivas</h2><div class="blog"><article><small>Oct 2026</small><b>Qué cambia en Ganancias para autónomos este mes</b><a>Leer →</a></article><article><small>Sep 2026</small><b>Vencimientos de septiembre: la lista completa</b><a>Leer →</a></article><article><small>Ago 2026</small><b>Monotributo: cuándo conviene pasarse de categoría</b><a>Leer →</a></article></div></section>'
    '<div class="form" id="consulta"><div><h2>Contanos tu caso</h2><p style="opacity:.8">Respondemos en menos de 24 horas hábiles. La primera consulta no tiene costo.</p></div><form onsubmit="wa(\'Consulta enviada (demo)\');return false"><select aria-label="Motivo"><option>Monotributo</option><option>Sociedades</option><option>Sueldos</option><option>Otro</option></select><input placeholder="Nombre" aria-label="Nombre"><input placeholder="Email o WhatsApp" aria-label="Contacto"><textarea rows="3" placeholder="Contanos brevemente" aria-label="Mensaje"></textarea><button class="btn">Enviar consulta</button></form></div><footer>Estudio Ferrari &amp; Asociados · Lavalle 1450, piso 6 · C.P.C.E.C.A.B.A.</footer></div>')

# ───────── Gimnasio · Box Norte ─────────
B["gimnasio"] = page("Box Norte", "family=Barlow+Condensed:wght@600;700;800;900&family=Barlow:wght@400;500;600",
    dict(bg="#0f1113", ink="#f1f3ee", pri="#c8f031", **{"pri-ink": "#0f1113"}, r="4px", f1="'Barlow Condensed',sans-serif", f2="Barlow,sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:center;padding:18px 0}nav b{font:900 30px var(--f1);letter-spacing:.04em;text-transform:uppercase}nav b span{color:#c8f031}nav div{display:flex;gap:26px;font:600 14px var(--f1);letter-spacing:.12em;text-transform:uppercase;opacity:.8}
.hero{position:relative;padding:60px 0 70px}.hero h1{font-size:clamp(64px,13vw,170px);line-height:.82;text-transform:uppercase;font-weight:900;letter-spacing:-.01em}.hero h1 span{color:#c8f031;display:block}.hero p{font-size:19px;margin:22px 0 26px;max-width:40ch;opacity:.8}.hero .stripe{position:absolute;right:-40px;top:20px;width:42%;height:74%;background:repeating-linear-gradient(115deg,#c8f031 0 14px,transparent 14px 38px);opacity:.14}
.grid{display:grid;grid-template-columns:90px repeat(5,1fr);gap:6px;font-size:13px}.grid .h{font:700 14px var(--f1);letter-spacing:.1em;text-transform:uppercase;opacity:.6;padding:6px}.grid .t{font:700 15px var(--f1);opacity:.6;padding-top:12px}.cl{background:#1b1f22;border-radius:6px;padding:10px;border-left:3px solid #c8f031;cursor:pointer;transition:background .15s}.cl:hover{background:#252a2e}.cl.on{background:#c8f031;color:#0f1113;border-left-color:#0f1113}.cl b{display:block;font:800 16px var(--f1);text-transform:uppercase}.cl small{opacity:.7}.cl.no{background:transparent;border:1px dashed #2c3236;cursor:default}
.plans{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.plan{background:#1b1f22;border-radius:8px;padding:30px;border-top:4px solid #2c3236}.plan.top{border-top-color:#c8f031;background:#22282b}.plan small{font:700 13px var(--f1);letter-spacing:.14em;text-transform:uppercase;color:#c8f031}.plan h3{font:900 34px var(--f1);text-transform:uppercase;margin:4px 0 2px}.plan .pr{font:900 44px var(--f1)}.plan .pr span{font-size:16px;opacity:.6}.plan ul{list-style:none;margin:14px 0 20px;font-size:15px;opacity:.85}.plan li{padding:4px 0}.plan li::before{content:"→ ";color:#c8f031}.plan .btn{width:100%;justify-content:center}
.band{background:#c8f031;color:#0f1113;text-align:center;padding:30px;font:900 clamp(26px,4vw,44px) var(--f1);text-transform:uppercase}""",
    '<div class="w"><nav><b>Box <span>Norte</span></b><div><a>Clases</a><a>Planes</a><a>Coaches</a><a>Contacto</a></div></nav><section class="hero"><div class="stripe"></div><h1>Entrená fuerte.<span>Entrená acá.</span></h1><p>Box de funcional y fuerza en Núñez. Clases de 60 minutos con coach, cupos limitados y primera clase gratis.</p><a class="btn" href="#clases">Reservar clase gratis →</a></section></div>'
    '<section class="sec" id="clases"><div class="w"><h2 style="font-family:var(--f1);text-transform:uppercase;font-size:44px">Clases de la semana</h2><div class="grid" id="gr"></div><p class="sel" id="gs" style="margin-top:16px;font-weight:600">Tocá una clase para reservar tu lugar</p></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w"><h2 style="font-family:var(--f1);text-transform:uppercase;font-size:44px">Planes</h2><div class="plans"><div class="plan"><small>Para arrancar</small><h3>2 veces por semana</h3><div class="pr">$ 38.000<span>/mes</span></div><ul><li>8 clases por mes</li><li>Coach en cada clase</li></ul><button class="btn o" data-wa="Quiero el plan de 2 veces por semana">Elegir</button></div><div class="plan top"><small>Más elegido</small><h3>Libre</h3><div class="pr">$ 52.000<span>/mes</span></div><ul><li>Todas las clases</li><li>Zona de pesas</li><li>Débito automático</li></ul><button class="btn" data-wa="Quiero el plan Libre">Elegir</button></div><div class="plan"><small>Con seguimiento</small><h3>Personalizado</h3><div class="pr">$ 78.000<span>/mes</span></div><ul><li>Plan a medida</li><li>Control mensual</li></ul><button class="btn o" data-wa="Quiero el plan Personalizado">Elegir</button></div></div></div></section><div class="band">Pagá la cuota con Mercado Pago · Sin matrícula</div><footer>Box Norte · Av. del Libertador 7400</footer>',
    """<script>(function(){var D=['Lun','Mar','Mié','Jue','Vie'],R=[['07:00','Fuerza','Coach Nico'],['09:00','Funcional','Coach Lu'],['12:30','WOD','Coach Nico'],['18:30','Funcional','Coach Lu'],['20:00','Fuerza','Coach Nico']],g=document.getElementById('gr'),h='<div></div>'+D.map(function(x){return'<div class="h">'+x+'</div>'}).join('');
R.forEach(function(r,i){h+='<div class="t">'+r[0]+'</div>';D.forEach(function(d,j){var no=(i===1&&j===4)||(i===3&&j===2);h+=no?'<div class="cl no"><small>Sin clase</small></div>':'<div class="cl" data-c="'+d+' '+r[0]+' · '+r[1]+'"><b>'+r[1]+'</b><small>'+r[2]+' · '+(8+((i*3+j*2)%7))+' lugares</small></div>'})});g.innerHTML=h;
g.onclick=function(e){var c=e.target.closest('.cl');if(!c||c.classList.contains('no'))return;g.querySelectorAll('.cl').forEach(function(x){x.classList.toggle('on',x===c)});document.getElementById('gs').textContent='Reservaste: '+c.dataset.c+' (primera clase gratis)';wa('Reserva de clase: '+c.dataset.c)}})()</script>""")


import lab_demos_negocios2, lab_demos_negocios3   # noqa: registran el resto de los rubros en B (import circular a propósito: comparten page y B)

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for i, h in B.items(): (OUT / f"{i}.html").write_text(h, encoding="utf-8")
    print(f"OK · {len(B)} ejemplos de negocios en {OUT}")


if __name__ == "__main__":
    main()
