#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Biblioteca de secciones y de paneles para las demos de patrones (tools/lab_demos_patrones.py).
Todo el contenido es inventado (la app "Plata"); son demos hechas para la ficha, no proyectos reales.
"""
import random

CSS = """*{box-sizing:border-box;margin:0}
:root{--ink:#1a1d29;--ink2:#575d70;--bg:#fff;--soft:#f4f6fb;--line:#e1e4ee;--acc:#2f5bea;--ok:#12a150;--card:#fff}
body{font-family:Manrope,system-ui,sans-serif;color:var(--ink);background:var(--bg);line-height:1.5}
body.dark{--ink:#f2f4fb;--ink2:#a9b0c8;--bg:#0c1020;--soft:#141a30;--line:#262d4a;--card:#141a30}
a{color:inherit;text-decoration:none}.w{max-width:1040px;margin:0 auto;padding:0 24px}
section{padding:48px 0}.alt{background:var(--soft)}
h1{font-size:46px;line-height:1.04;letter-spacing:-.04em;font-weight:800}h2{font-size:28px;letter-spacing:-.03em;font-weight:800;margin-bottom:10px;line-height:1.1}h3{font-size:17px;font-weight:700;margin-bottom:4px}
.lead{font-size:18px;color:var(--ink2);max-width:46ch;margin-top:14px}.small{font-size:13.5px;color:var(--ink2)}.c{text-align:center}.c .lead{margin-left:auto;margin-right:auto}
.b{display:inline-block;padding:12px 22px;border-radius:10px;font-weight:700;font-size:15px;background:var(--acc);color:#fff;border:0;cursor:pointer;font-family:inherit}
.b.o{background:transparent;color:var(--ink);border:1.5px solid var(--line)}.b.g{background:var(--ok)}.b.big{padding:16px 30px;font-size:17px;border-radius:12px}
.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:20px}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}
.card{border:1px solid var(--line);border-radius:14px;padding:20px;background:var(--card)}
nav{display:flex;align-items:center;justify-content:space-between;padding:16px 24px;max-width:1040px;margin:0 auto;font-size:14px}nav b{font-size:21px;letter-spacing:-.02em}nav .l{display:flex;gap:22px;color:var(--ink2);font-weight:500}
.mock{border:1px solid var(--line);border-radius:18px;padding:22px;background:var(--card);box-shadow:0 24px 50px rgba(30,45,120,.14)}.mock small{color:var(--ink2);font-weight:600;font-size:13px}.mock .n{font-size:40px;font-weight:800;letter-spacing:-.03em}
.bars{display:flex;align-items:flex-end;gap:9px;height:110px;margin-top:14px}.bars i{flex:1;background:var(--acc);border-radius:4px 4px 0 0}
.k{display:inline-block;font-size:12px;font-weight:700;color:#12804a;background:#e4f6ec;padding:5px 11px;border-radius:99px;margin-bottom:14px}body.dark .k{background:#0f3a28;color:#7be7b0}
.ico{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;background:#e8eeff;color:var(--acc);font-weight:800;margin-bottom:12px}
.row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.stars{color:#f5a623;letter-spacing:2px}
.logos{display:flex;gap:30px;justify-content:center;flex-wrap:wrap;color:var(--ink2);font-weight:800;font-size:17px;opacity:.75}
table{width:100%;border-collapse:collapse;font-size:14.5px}th,td{padding:12px 14px;text-align:left;border-bottom:1px solid var(--line)}th{font-size:13px;color:var(--ink2)}td.y{color:var(--ok);font-weight:700}td.n{color:#c0392b}tr.me td{background:#eef3ff;font-weight:700}
input,select{width:100%;padding:13px 14px;border:1.5px solid var(--line);border-radius:10px;font:inherit;font-size:15px;background:var(--bg);color:var(--ink)}
.form{border:1px solid var(--line);border-radius:18px;padding:26px;background:var(--card);box-shadow:0 22px 50px rgba(30,45,120,.12)}.form input{margin-bottom:12px}.form h2{font-size:22px}
details{border-bottom:1px solid var(--line);padding:14px 0}summary{font-weight:700;cursor:pointer}details p{margin-top:8px;color:var(--ink2);font-size:14.5px}
.cta{padding:56px 0;text-align:center;background:var(--acc);color:#fff}.cta h2{font-size:32px}.cta .b{background:#fff;color:var(--acc);margin-top:16px}
footer{padding:26px 24px;text-align:center;font-size:12.5px;color:var(--ink2);border-top:1px solid var(--line)}
.tag{display:inline-block;padding:5px 12px;border-radius:99px;background:var(--soft);border:1px solid var(--line);font-size:13px;font-weight:600;margin:3px}
.num{font-size:34px;font-weight:800;letter-spacing:-.03em}.step{counter-increment:s}.step::before{content:counter(s);display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:var(--acc);color:#fff;font-weight:800;margin-bottom:10px}
.dark .mock{box-shadow:0 24px 60px rgba(0,0,0,.5)}
@media(max-width:860px){.grid3,.grid2,.grid4{grid-template-columns:1fr}h1{font-size:34px}nav .l{display:none}}
"""

def page(title, body, css="", theme="", js=""):
    return ('<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Plata · ' + title + '</title>'
            '<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>' + CSS + css + '</style></head><body class="' + theme + '">'
            + body + js + '</body></html>')

MOCK = '<div class="mock"><small>Disponible este mes</small><div class="n">$ 842.300</div><div class="bars" aria-hidden="true"><i style="height:48%"></i><i style="height:72%"></i><i style="height:40%"></i><i style="height:88%"></i><i style="height:62%"></i><i style="height:100%"></i></div></div>'

NAVS = {
    "std": '<nav><b>Plata</b><div class="l"><a>Cuentas</a><a>Gastos</a><a>Ahorro</a><a>Ayuda</a></div><a class="b">Abrir cuenta</a></nav>',
    "min": '<nav><b>Plata</b><a class="small" style="text-decoration:underline">Ingresar</a></nav>',
    "none": '',
}

# ── secciones: cada una devuelve HTML (todo con la misma oferta: Plata, finanzas personales) ──
def S(cls, inner, w=True): return '<section class="' + cls + '">' + ('<div class="w">' + inner + '</div>' if w else inner) + '</section>'

SEC = {}
SEC["hero"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><h1>Tu plata, a la vista y en orden.</h1><p class="lead">Juntá tus cuentas y mirá cuánto te queda en el mes, sin planillas.</p><div class="row" style="margin-top:22px"><a class="b big">Abrir mi cuenta</a><a class="b o big">Ver cómo funciona</a></div></div>' + MOCK + '</div>')
SEC["hero_c"] = lambda: S("c", '<h1 style="max-width:16ch;margin:0 auto">Tu plata, a la vista y en orden.</h1><p class="lead">Juntá tus cuentas y mirá cuánto te queda en el mes, sin planillas.</p><div style="margin-top:22px"><a class="b big">Abrir mi cuenta</a></div><div style="max-width:520px;margin:34px auto 0">' + MOCK + '</div>')
SEC["hero_big"] = lambda: S("", '<div style="background:linear-gradient(135deg,#2f5bea,#7c3aed);color:#fff;border-radius:0;padding:110px 24px 90px;text-align:center"><h1 style="font-size:68px;max-width:14ch;margin:0 auto">Tu plata, a la vista y en orden.</h1><p style="font-size:20px;opacity:.9;margin:18px auto 28px;max-width:40ch">Una sola app para tus cuentas, gastos y metas.</p><a class="b big" style="background:#fff;color:#2f5bea">Empezar gratis</a></div>', w=False)
SEC["hero_video"] = lambda: S("", '<div style="background:radial-gradient(circle at 70% 30%,#3b5bdb,#0c1020 70%);color:#fff;padding:90px 24px;text-align:center;position:relative"><div style="width:84px;height:84px;border-radius:50%;background:rgba(255,255,255,.2);border:2px solid #fff;display:grid;place-items:center;margin:0 auto 26px;font-size:30px">▶</div><h1 style="max-width:16ch;margin:0 auto">Mirá cómo Plata ordena tu mes en 30 segundos.</h1><p style="opacity:.85;margin-top:14px">Video de 30 segundos · sin sonido necesario</p><div class="row" style="justify-content:center;margin-top:26px"><span class="tag" style="background:rgba(255,255,255,.14);color:#fff;border-color:rgba(255,255,255,.3)">Todo en una pantalla</span><span class="tag" style="background:rgba(255,255,255,.14);color:#fff;border-color:rgba(255,255,255,.3)">Gastos automáticos</span><span class="tag" style="background:rgba(255,255,255,.14);color:#fff;border-color:rgba(255,255,255,.3)">Metas con fecha</span></div></div>', w=False)
SEC["hero_search"] = lambda: S("c", '<h1 style="max-width:16ch;margin:0 auto">Encontrá un asesor financiero cerca tuyo.</h1><div style="max-width:580px;margin:24px auto 0;display:flex;gap:8px"><input placeholder="¿Qué necesitás? Ej.: ordenar deudas" aria-label="Buscar"><a class="b">Buscar</a></div><div style="margin-top:14px"><span class="tag">Deudas</span><span class="tag">Ahorro</span><span class="tag">Jubilación</span><span class="tag">Primera inversión</span></div>')
SEC["hero_count"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><span class="k">Próximamente · acceso anticipado</span><h1>Plata Pro llega el 15 de noviembre.</h1><div class="row" style="margin-top:22px;gap:12px"><div class="card c" style="padding:12px 18px"><div class="num">24</div><div class="small">días</div></div><div class="card c" style="padding:12px 18px"><div class="num">06</div><div class="small">horas</div></div><div class="card c" style="padding:12px 18px"><div class="num">41</div><div class="small">min</div></div></div></div><div class="form"><h2>Anotate primero</h2><p class="small" style="margin-bottom:14px">Te avisamos cuando abra.</p><input placeholder="tu@correo.com" aria-label="Email"><a class="b" style="display:block;text-align:center">Quiero acceso anticipado</a></div></div>')
SEC["hero_prompt"] = lambda: S("c", '<h1 style="max-width:16ch;margin:0 auto">Contale a Plata cómo gastás y te arma el plan.</h1><div style="max-width:620px;margin:24px auto 0;display:flex;gap:8px"><input placeholder="Ej.: gano $1.200.000 y quiero ahorrar para un viaje" aria-label="Contá tu situación"><a class="b">Armar mi plan</a></div><p class="small" style="margin-top:10px">Sin registrarte · el resultado aparece en unos segundos</p>')
SEC["hero_name"] = lambda: S("", '<div style="padding:30px 0"><p class="small" style="font-weight:700;letter-spacing:.1em;text-transform:uppercase">Ana Ferreyra · Diseño de producto</p><h1 style="font-size:64px;max-width:14ch;margin-top:10px">Diseño apps de finanzas que se entienden.</h1></div>')
SEC["hero_event"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><span class="k">Congreso · Buenos Aires · 21 de octubre</span><h1>Plata Day 2026: ordená tu economía.</h1><p class="lead">Un día de charlas prácticas sobre ahorro, deudas e inversión.</p><div class="row" style="margin-top:20px"><div class="card c" style="padding:10px 16px"><div class="num" style="font-size:26px">19</div><div class="small">días</div></div><div class="card c" style="padding:10px 16px"><div class="num" style="font-size:26px">08</div><div class="small">horas</div></div></div></div>' + MOCK.replace('Disponible este mes', 'Entradas vendidas').replace('$ 842.300', '412 / 600') + '</div>')
SEC["hero_rating"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><span class="k">App de finanzas personales</span><h1>Plata</h1><div class="row" style="margin-top:14px"><span class="stars" style="font-size:26px">★★★★★</span><span class="num" style="font-size:30px">4,8</span><span class="small">de 5 · 3.214 reseñas verificadas</span></div><p class="lead">Ordená tus cuentas y gastos en una sola pantalla.</p><div style="margin-top:20px"><a class="b big">Probar gratis</a></div></div>' + MOCK + '</div>')
SEC["hero_problem"] = lambda: S("c", '<h1 style="max-width:17ch;margin:0 auto">Llegás a fin de mes sin saber en qué se fue la plata.</h1><p class="lead">Planillas, tarjetas, apps del banco: nada cierra y cada mes arranca de cero.</p>')
SEC["hero_live"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><span class="k" style="background:#fde8e6;color:#b3261e">● En vivo</span><h1>Mirá tus gastos mientras pasan.</h1><p class="lead">Cada compra aparece en segundos, con tu saldo al día.</p><div class="row" style="margin-top:20px"><a class="b big">Empezar prueba</a><a class="b o big">Hablar con el equipo</a></div></div><div class="mock"><small>Últimos movimientos</small><div style="margin-top:10px;display:grid;gap:9px;font-size:14px"><div style="display:flex;justify-content:space-between"><span>● Café · hace 4 s</span><b>− $ 3.200</b></div><div style="display:flex;justify-content:space-between"><span>● Subte · hace 38 s</span><b>− $ 700</b></div><div style="display:flex;justify-content:space-between"><span>● Sueldo · hace 2 min</span><b style="color:#12a150">+ $ 1.250.000</b></div></div></div></div>')
SEC["hero_mission"] = lambda: S("", '<div style="background:var(--soft);padding:70px 40px;border-radius:20px"><span class="k">Plata para empresas</span><h1 style="max-width:18ch">Ordenamos las finanzas de más de 800 equipos.</h1><p class="lead">Gastos, reembolsos y presupuestos en un solo lugar.</p></div>')
SEC["hero_config"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><h1>Armá tu tarjeta Plata.</h1><p class="lead">Elegí el color y mirá cómo queda al instante.</p><div class="row" style="margin-top:18px" id="sw"><button class="tag" data-c="#2f5bea">Azul</button><button class="tag" data-c="#12a150">Verde</button><button class="tag" data-c="#e8453c">Rojo</button><button class="tag" data-c="#1a1d29">Negro</button></div></div><div style="perspective:900px"><div id="card3d" style="height:230px;border-radius:20px;background:#2f5bea;color:#fff;padding:24px;transform:rotateY(-18deg) rotateX(6deg);box-shadow:0 30px 50px rgba(30,45,120,.35);transition:background .3s,transform .3s"><b style="font-size:22px">Plata</b><div style="margin-top:80px;letter-spacing:.2em">•••• •••• •••• 4821</div></div></div></div>')
SEC["hero_device"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><h1>Plata, en tu celular.</h1><div class="row" style="margin-top:14px"><span class="stars">★★★★★</span><b>4,8</b><span class="small">en las tiendas de apps</span></div><div class="row" style="margin-top:20px"><a class="b big" style="background:#111">App Store</a><a class="b big" style="background:#111">Google Play</a></div></div><div style="display:grid;place-items:center"><div style="width:230px;height:420px;border:9px solid #1a1d29;border-radius:34px;padding:18px;background:var(--card)"><small class="small">Disponible</small><div class="num" style="font-size:28px">$ 842.300</div><div class="bars" style="height:90px"><i style="height:48%"></i><i style="height:72%"></i><i style="height:40%"></i><i style="height:88%"></i><i style="height:62%"></i></div></div></div></div>')
SEC["hero_pricing"] = lambda: S("c", '<h1 style="max-width:14ch;margin:0 auto">Planes simples, sin letra chica.</h1><p class="lead">Empezás gratis y pasás a un plan pago solo cuando lo necesites.</p><div class="row" style="justify-content:center;margin-top:18px"><span class="tag">Mensual</span><span class="tag" style="background:#e4f6ec">Anual · 2 meses gratis</span></div>')
SEC["hero_faq"] = lambda: S("c", '<h1 style="max-width:14ch;margin:0 auto">¿En qué te ayudamos?</h1><div style="max-width:560px;margin:22px auto 0"><input placeholder="Buscá: “cambiar mi plan”, “cerrar mi cuenta”…" aria-label="Buscar en la ayuda"></div>')
SEC["hero_community"] = lambda: S("c", '<span class="k">Comunidad Plata · 18.200 miembros</span><h1 style="max-width:16ch;margin:0 auto">Aprendé a manejar tu plata con gente como vos.</h1><div style="margin-top:22px"><a class="b big">Sumarme gratis</a></div>')
SEC["hero_trust"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><span class="k">Regulada · Datos cifrados</span><h1>Tu plata, en manos que se pueden auditar.</h1><p class="lead">Más de 12.400 cuentas confían en Plata. Mirá cómo cuidamos tus datos.</p></div>' + MOCK + '</div>')
SEC["hero_story"] = lambda: S("", '<div style="padding:60px 0"><p class="small" style="font-weight:700;letter-spacing:.1em;text-transform:uppercase">Prólogo</p><h1 style="max-width:16ch;margin-top:12px">Todo empezó con una planilla que nadie entendía.</h1><p class="lead">Así nació Plata.</p></div>')
SEC["hero_min"] = lambda: S("c", '<div style="padding:50px 0"><h1 style="font-size:54px;max-width:14ch;margin:0 auto">Tu plata, en orden.</h1><p class="lead">Una sola pantalla para todas tus cuentas.</p><div style="margin-top:24px"><a class="b big">Empezar gratis</a></div></div>')
SEC["hero_news"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><span class="k">Newsletter semanal · gratis</span><h1>Plata Semanal: finanzas claras, los jueves.</h1><p class="lead">Cinco minutos de lectura, sin jerga.</p></div><div class="form"><h2>Recibila gratis</h2><input placeholder="tu@correo.com" aria-label="Email"><a class="b" style="display:block;text-align:center">Suscribirme</a><p class="small c" style="margin-top:10px">Cancelás cuando quieras</p></div></div>')
SEC["hero_webinar"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><span class="k">Webinar gratis · jueves 22 · 19 h</span><h1>Cómo ordenar tus gastos en 30 días.</h1><div class="row" style="margin-top:18px"><div class="card c" style="padding:10px 16px"><div class="num" style="font-size:26px">02</div><div class="small">días</div></div><div class="card c" style="padding:10px 16px"><div class="num" style="font-size:26px">11</div><div class="small">horas</div></div></div></div><div class="form"><h2>Reservá tu lugar</h2><input placeholder="Nombre" aria-label="Nombre"><input placeholder="tu@correo.com" aria-label="Email"><a class="b g" style="display:block;text-align:center">Reservar mi lugar</a><p class="small c" style="margin-top:10px">Quedan 38 de 200 lugares</p></div></div>')
SEC["hero_lead"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><span class="k">Guía gratis · PDF de 24 páginas</span><h1>Guía para salir de deudas en 90 días.</h1><p class="lead">El método paso a paso que usamos con más de 3.000 personas.</p></div><div style="display:grid;place-items:center"><div style="width:210px;height:280px;border-radius:8px 18px 18px 8px;background:linear-gradient(135deg,#2f5bea,#1b2f8a);color:#fff;padding:24px;box-shadow:14px 18px 36px rgba(30,45,120,.4);transform:rotate(-4deg)"><b>Plata</b><div style="margin-top:70px;font-size:22px;font-weight:800;line-height:1.1">Salí de deudas en 90 días</div></div></div></div>')

# bloques
SEC["value"] = lambda: S("alt", '<div class="c"><h2>Una sola pantalla para tu plata</h2><p class="lead">Cuentas, tarjetas y metas, siempre al día.</p></div>')
SEC["features3"] = lambda: S("", '<div class="grid3"><div class="card"><div class="ico">1</div><h3>Todo en una pantalla</h3><p class="small">Tus cuentas y tarjetas juntas, con el saldo real.</p></div><div class="card"><div class="ico">2</div><h3>Gastos sin cargar nada</h3><p class="small">Se ordenan solos por categoría.</p></div><div class="card"><div class="ico">3</div><h3>Metas con fecha</h3><p class="small">Te avisa si vas bien.</p></div></div>')
SEC["features6"] = lambda: S("", '<div class="c" style="margin-bottom:26px"><h2>Todo lo que necesitás</h2></div><div class="grid3"><div class="card"><div class="ico">◎</div><h3>Cuentas unificadas</h3><p class="small">Todos tus bancos juntos.</p></div><div class="card"><div class="ico">▤</div><h3>Gastos por categoría</h3><p class="small">Sin cargar nada.</p></div><div class="card"><div class="ico">⚑</div><h3>Metas</h3><p class="small">Con fecha y aviso.</p></div><div class="card"><div class="ico">⌁</div><h3>Alertas</h3><p class="small">Antes de pasarte.</p></div><div class="card"><div class="ico">⇄</div><h3>Pagos con QR</h3><p class="small">En segundos.</p></div><div class="card"><div class="ico">⛨</div><h3>Seguridad</h3><p class="small">Datos cifrados.</p></div></div>')
SEC["features_icons"] = SEC["features6"]
SEC["problem"] = lambda: S("alt", '<div class="grid3"><div class="card"><h3>Cinco apps</h3><p class="small">Una por banco, ninguna te dice cuánto tenés en total.</p></div><div class="card"><h3>Una planilla</h3><p class="small">Que se desactualiza a la semana.</p></div><div class="card"><h3>Un sobresalto</h3><p class="small">Cuando llega el resumen de la tarjeta.</p></div></div>')
SEC["solution"] = lambda: S("", '<div class="grid2" style="align-items:center"><div><h2>Plata junta todo y te lo muestra simple.</h2><p class="lead">Conectás tus cuentas una vez y listo.</p></div>' + MOCK + '</div>')
SEC["testimonials"] = lambda: S("alt", '<div class="c" style="margin-bottom:24px"><h2>Lo que dicen quienes ya la usan</h2></div><div class="grid3"><div class="card"><div class="stars">★★★★★</div><p style="margin:10px 0">“Por primera vez sé cuánto me queda antes de gastar.”</p><b>Lucía F.</b><div class="small">Docente, Rosario</div></div><div class="card"><div class="stars">★★★★★</div><p style="margin:10px 0">“Dejé la planilla en la primera semana.”</p><b>Martín G.</b><div class="small">Diseñador, CABA</div></div><div class="card"><div class="stars">★★★★★</div><p style="margin:10px 0">“Las metas con fecha me hicieron ahorrar el doble.”</p><b>Sofía R.</b><div class="small">Contadora, Córdoba</div></div></div>')
SEC["logos"] = lambda: S("", '<p class="small c" style="margin-bottom:16px">Aparecimos en</p><div class="logos"><span>Diario Sur</span><span>FinTech AR</span><span>Radio Ciudad</span><span>Revista Pymes</span><span>Canal 5</span></div>')
SEC["stats"] = lambda: S("alt", '<div class="grid4 c"><div><div class="num">12.400</div><div class="small">cuentas activas</div></div><div><div class="num">$ 1.800 M</div><div class="small">ordenados por mes</div></div><div><div class="num">4,8 ★</div><div class="small">en las tiendas</div></div><div><div class="num">98 %</div><div class="small">renueva</div></div></div>')
SEC["trust"] = lambda: S("", '<div class="grid4 c"><div class="card"><div class="ico" style="margin:0 auto 10px">⛨</div><h3>Datos cifrados</h3><p class="small">Estándar bancario</p></div><div class="card"><div class="ico" style="margin:0 auto 10px">✓</div><h3>Auditada</h3><p class="small">Cada año, por terceros</p></div><div class="card"><div class="ico" style="margin:0 auto 10px">⚖</div><h3>Regulada</h3><p class="small">Cumple la normativa</p></div><div class="card"><div class="ico" style="margin:0 auto 10px">☎</div><h3>Soporte humano</h3><p class="small">Lunes a sábado</p></div></div>')
SEC["case_metrics"] = lambda: S("alt", '<div class="grid3"><div class="card"><div class="num" style="color:#12a150">−38 %</div><p class="small">de gastos hormiga en 3 meses</p></div><div class="card"><div class="num" style="color:#12a150">+$ 96.000</div><p class="small">ahorrados por mes en promedio</p></div><div class="card"><div class="num" style="color:#12a150">2×</div><p class="small">más metas cumplidas</p></div></div>')
SEC["demo_mock"] = lambda: S("alt", '<div class="c" style="margin-bottom:22px"><h2>Probalo acá mismo</h2><p class="lead">Mové el control y mirá cómo cambia tu mes.</p></div><div class="mock" style="max-width:560px;margin:0 auto"><small>Si ahorrás por mes…</small><div class="n" id="vv">$ 120.000</div><input type="range" min="50000" max="400000" step="10000" value="120000" aria-label="Ahorro mensual" style="padding:0;margin-top:12px" oninput="document.getElementById(\'vv\').textContent=\'$ \'+(+this.value).toLocaleString(\'es-AR\');document.getElementById(\'yy\').textContent=\'$ \'+(this.value*12).toLocaleString(\'es-AR\')"><p class="small" style="margin-top:10px">En un año juntás <b id="yy">$ 1.440.000</b></p></div>')
SEC["steps3"] = lambda: S("", '<div class="c" style="margin-bottom:24px"><h2>Cómo funciona</h2></div><div class="grid3" style="counter-reset:s"><div class="card step"><h3>Conectá tus cuentas</h3><p class="small">Una sola vez, en 2 minutos.</p></div><div class="card step"><h3>Mirá tu mes</h3><p class="small">Todo ordenado y al día.</p></div><div class="card step"><h3>Ponete metas</h3><p class="small">Y seguí tu avance.</p></div></div>')
SEC["compare"] = lambda: S("", '<div class="c" style="margin-bottom:22px"><h2>Plata contra las alternativas</h2></div><div class="card" style="padding:6px"><table><tr><th></th><th>Planilla</th><th>App del banco</th><th>Plata</th></tr><tr><td>Todas las cuentas juntas</td><td class="n">Manual</td><td class="n">Solo la suya</td><td class="y">✓</td></tr><tr><td>Gastos por categoría</td><td class="n">Manual</td><td class="n">Parcial</td><td class="y">✓ Automático</td></tr><tr><td>Metas con aviso</td><td class="n">—</td><td class="n">—</td><td class="y">✓</td></tr><tr class="me"><td>Precio</td><td>Gratis</td><td>Gratis</td><td>Gratis / $ 2.900</td></tr></table></div>')
SEC["pricing"] = lambda: S("", '<div class="grid3"><div class="card"><h3>Gratis</h3><div class="num">$ 0</div><p class="small" style="margin:8px 0 14px">Para empezar.</p><a class="b o" style="display:block;text-align:center">Elegir</a></div><div class="card" style="border:2px solid var(--acc);position:relative"><span class="k" style="position:absolute;top:-14px;left:20px;background:var(--acc);color:#fff">Más elegido</span><h3>Plus</h3><div class="num">$ 2.900<span class="small">/mes</span></div><p class="small" style="margin:8px 0 14px">Cuentas ilimitadas y metas.</p><a class="b" style="display:block;text-align:center">Elegir</a></div><div class="card"><h3>Familia</h3><div class="num">$ 4.900<span class="small">/mes</span></div><p class="small" style="margin:8px 0 14px">Hasta 5 personas.</p><a class="b o" style="display:block;text-align:center">Elegir</a></div></div>')
SEC["matrix"] = lambda: S("alt", '<div class="card" style="padding:6px"><table><tr><th>Función</th><th>Gratis</th><th>Plus</th><th>Familia</th></tr><tr><td>Cuentas conectadas</td><td>2</td><td>Ilimitadas</td><td>Ilimitadas</td></tr><tr><td>Metas de ahorro</td><td>1</td><td>Ilimitadas</td><td>Ilimitadas</td></tr><tr><td>Alertas</td><td>—</td><td class="y">✓</td><td class="y">✓</td></tr><tr><td>Personas</td><td>1</td><td>1</td><td>5</td></tr></table></div>')
SEC["faq"] = lambda: S("", '<div style="max-width:700px;margin:0 auto"><h2 class="c" style="margin-bottom:14px">Preguntas frecuentes</h2><details open><summary>¿Es gratis?</summary><p>Sí, hay un plan gratuito sin límite de tiempo.</p></details><details><summary>¿Es seguro conectar mis cuentas?</summary><p>Usamos conexión de solo lectura y datos cifrados.</p></details><details><summary>¿Puedo cancelar cuando quiera?</summary><p>Sí, desde la app y sin llamados.</p></details></div>')
SEC["form"] = lambda: S("alt", '<div style="max-width:440px;margin:0 auto"><div class="form"><h2>Empezá gratis</h2><input placeholder="tu@correo.com" aria-label="Email"><a class="b g" style="display:block;text-align:center">Crear mi cuenta</a><p class="small c" style="margin-top:10px">Sin tarjeta · cancelás cuando quieras</p></div></div>')
SEC["form_lead"] = lambda: S("alt", '<div style="max-width:440px;margin:0 auto"><div class="form"><h2>Descargá la guía</h2><input placeholder="Tu nombre" aria-label="Nombre"><input placeholder="tu@correo.com" aria-label="Email"><a class="b g" style="display:block;text-align:center">Enviármela por mail</a></div></div>')
SEC["lead_preview"] = lambda: S("", '<div class="c" style="margin-bottom:20px"><h2>Qué vas a encontrar adentro</h2></div><div class="grid3"><div class="card"><h3>Mapa de deudas</h3><p class="small">Ordená cuánto debés y a quién.</p></div><div class="card"><h3>Plan en 90 días</h3><p class="small">Semana por semana.</p></div><div class="card"><h3>Plantillas</h3><p class="small">Para negociar con el banco.</p></div></div>')
SEC["cta"] = lambda: '<section class="cta"><div class="w"><h2>Empezá hoy a ver tu plata clara</h2><p style="opacity:.9">Gratis, sin tarjeta.</p><a class="b big">Abrir mi cuenta</a></div></section>'
SEC["cta_results"] = lambda: '<section class="cta"><div class="w"><h2>Tus resultados empiezan este mes</h2><p style="opacity:.9">Con garantía: si no te sirve, no pagás.</p><a class="b big">Empezar ahora</a></div></section>'
SEC["footer"] = lambda: '<footer>Plata S.A. · Términos · Privacidad · Contacto</footer>'
SEC["speakers"] = lambda: S("", '<div class="c" style="margin-bottom:20px"><h2>Quiénes hablan</h2></div><div class="grid4"><div class="card c"><div class="ico" style="margin:0 auto 10px;border-radius:50%">AF</div><h3>Ana Ferreyra</h3><p class="small">Diseño de producto</p></div><div class="card c"><div class="ico" style="margin:0 auto 10px;border-radius:50%">LM</div><h3>Luis Méndez</h3><p class="small">Economista</p></div><div class="card c"><div class="ico" style="margin:0 auto 10px;border-radius:50%">CP</div><h3>Carla Páez</h3><p class="small">Asesora financiera</p></div><div class="card c"><div class="ico" style="margin:0 auto 10px;border-radius:50%">DR</div><h3>Diego Ríos</h3><p class="small">Inversiones</p></div></div>')
SEC["agenda"] = lambda: S("alt", '<h2 style="margin-bottom:14px">Agenda</h2><div class="card" style="padding:6px"><table><tr><td><b>09:00</b></td><td>Apertura</td></tr><tr><td><b>10:00</b></td><td>Cómo armar tu primer presupuesto</td></tr><tr><td><b>12:00</b></td><td>Deudas: salir sin ahogarte</td></tr><tr><td><b>15:00</b></td><td>Invertir desde cero</td></tr></table></div>')
SEC["sponsors"] = lambda: S("", '<p class="small c" style="margin-bottom:14px">Con el apoyo de</p><div class="logos"><span>Banco Norte</span><span>Seguros Sol</span><span>Café Andino</span><span>Radio Ciudad</span></div>')
SEC["cta_event"] = lambda: '<section class="cta"><div class="w"><h2>Reservá tu entrada</h2><p style="opacity:.9">Preventa hasta el 30 de septiembre · $ 18.000</p><a class="b big">Inscribirme</a></div></section>'
SEC["reviews_break"] = lambda: S("alt", '<div class="grid2" style="align-items:center"><div><div class="num" style="font-size:56px">4,8</div><div class="stars" style="font-size:22px">★★★★★</div><p class="small">3.214 reseñas verificadas</p></div><div style="display:grid;gap:7px;font-size:13px"><div>5 ★ <span style="display:inline-block;height:8px;width:82%;background:#f5a623;border-radius:4px;vertical-align:middle"></span> 82 %</div><div>4 ★ <span style="display:inline-block;height:8px;width:12%;background:#f5a623;border-radius:4px;vertical-align:middle"></span> 12 %</div><div>3 ★ <span style="display:inline-block;height:8px;width:4%;background:#f5a623;border-radius:4px;vertical-align:middle"></span> 4 %</div><div>2 ★ <span style="display:inline-block;height:8px;width:1%;background:#f5a623;border-radius:4px;vertical-align:middle"></span> 1 %</div><div>1 ★ <span style="display:inline-block;height:8px;width:1%;background:#f5a623;border-radius:4px;vertical-align:middle"></span> 1 %</div></div></div>')
SEC["reviews_list"] = lambda: S("", '<div class="grid2"><div class="card"><div class="stars">★★★★★</div><b> Compra verificada</b><p style="margin:8px 0">Me ordenó el mes en una tarde.</p><span class="small">Lucía F. · hace 2 días</span></div><div class="card"><div class="stars">★★★★☆</div><b> Compra verificada</b><p style="margin:8px 0">Muy buena; me faltan más bancos.</p><span class="small">Martín G. · hace 1 semana · <i>Respondió Plata</i></span></div></div>')
SEC["categories"] = lambda: S("", '<h2 style="margin-bottom:14px">Categorías populares</h2><div class="grid4"><div class="card c"><h3>Deudas</h3><p class="small">128 asesores</p></div><div class="card c"><h3>Ahorro</h3><p class="small">214 asesores</p></div><div class="card c"><h3>Inversión</h3><p class="small">97 asesores</p></div><div class="card c"><h3>Jubilación</h3><p class="small">64 asesores</p></div></div>')
SEC["listings"] = lambda: S("alt", '<h2 style="margin-bottom:14px">Destacados cerca tuyo</h2><div class="grid3"><div class="card"><b>Carla Páez</b><div class="stars">★★★★★</div><p class="small">Deudas y ahorro · Almagro</p><b>$ 18.000 / hora</b></div><div class="card"><b>Luis Méndez</b><div class="stars">★★★★★</div><p class="small">Inversiones · Caballito</p><b>$ 22.000 / hora</b></div><div class="card"><b>Diego Ríos</b><div class="stars">★★★★☆</div><p class="small">Jubilación · Palermo</p><b>$ 20.000 / hora</b></div></div>')
SEC["cta_host"] = lambda: '<section class="cta"><div class="w"><h2>¿Sos asesor? Sumate a Plata</h2><p style="opacity:.9">Recibí consultas de personas que ya te están buscando.</p><a class="b big">Quiero ofrecer mis servicios</a></div></section>'
SEC["industries"] = lambda: S("", '<h2 style="margin-bottom:14px">Soluciones por industria</h2><div class="grid4"><div class="card"><h3>Retail</h3></div><div class="card"><h3>Salud</h3></div><div class="card"><h3>Educación</h3></div><div class="card"><h3>Logística</h3></div></div>')
SEC["roles"] = lambda: S("alt", '<h2 style="margin-bottom:14px">Soluciones por rol</h2><div class="grid3"><div class="card"><h3>Finanzas</h3><p class="small">Cierres en la mitad de tiempo.</p></div><div class="card"><h3>Operaciones</h3><p class="small">Gastos bajo control.</p></div><div class="card"><h3>Dirección</h3><p class="small">Una vista del negocio.</p></div></div>')
SEC["cta_sales"] = lambda: '<section class="cta"><div class="w"><h2>Hablá con nuestro equipo de ventas</h2><a class="b big">Contactar a ventas</a></div></section>'
SEC["projects"] = lambda: S("", '<div style="display:grid;grid-template-columns:repeat(3,1fr);grid-auto-rows:140px;gap:14px"><div class="card" style="grid-row:span 2;background:linear-gradient(160deg,#dbe5ff,#fff)"><h3>App Plata</h3><p class="small">Finanzas personales</p></div><div class="card" style="background:#ffe9d6"><h3>Banco Norte</h3></div><div class="card" style="background:#e1f6ea"><h3>Mercado AR</h3></div><div class="card" style="background:#efe3ff"><h3>Seguros Sol</h3></div><div class="card" style="grid-column:span 2;background:#e6f2ff"><h3>Panel de ahorro</h3></div></div>')
SEC["about"] = lambda: S("alt", '<div class="grid2"><div><h2>Sobre mí</h2><p class="lead">Diseño productos financieros desde hace 8 años. Creo que si algo con plata no se entiende, está mal diseñado.</p></div><div class="card"><h3>Trabajo con</h3><p class="small">Investigación, diseño de interfaz y prototipos.</p></div></div>')
SEC["contact"] = lambda: S("", '<div class="c"><h2>¿Hacemos algo juntos?</h2><div style="margin-top:14px"><a class="b big">ana@correo.com</a></div></div>')
SEC["bento"] = lambda: S("", '<div style="display:grid;grid-template-columns:repeat(4,1fr);grid-auto-rows:120px;gap:12px"><div class="card" style="grid-column:span 2;grid-row:span 2;background:#e8eeff"><h3>Todo en una pantalla</h3><p class="small">Cuentas, tarjetas y metas.</p></div><div class="card" style="background:#fff3e0"><h3>Alertas</h3></div><div class="card" style="background:#e4f6ec"><h3>QR</h3></div><div class="card" style="grid-column:span 2;background:#f3ecff"><h3>Gastos automáticos</h3></div></div>')
SEC["specs"] = lambda: S("alt", '<div class="card" style="padding:6px"><table><tr><td>Cifrado</td><td>AES-256</td></tr><tr><td>Bancos compatibles</td><td>34</td></tr><tr><td>Actualización</td><td>Cada 15 minutos</td></tr><tr><td>Plataformas</td><td>iOS · Android · Web</td></tr></table></div>')
SEC["price_buy"] = lambda: S("", '<div class="card" style="max-width:560px;margin:0 auto;display:flex;justify-content:space-between;align-items:center;gap:14px"><div><h3>Tarjeta Plata · Azul</h3><p class="small">Envío gratis · 3 cuotas sin interés</p></div><div><div class="num">$ 4.900</div><a class="b g" style="margin-top:6px">Pedir mi tarjeta</a></div></div>')
SEC["prompt_preview"] = lambda: S("alt", '<div class="mock" style="max-width:560px;margin:0 auto"><small>Tu plan generado</small><div style="margin-top:10px;display:grid;gap:8px;font-size:14.5px"><div>• Vivienda y servicios: <b>45 %</b></div><div>• Comida y transporte: <b>30 %</b></div><div>• Ahorro para el viaje: <b>15 %</b></div><div>• Libre: <b>10 %</b></div></div></div>')
SEC["live_metrics"] = lambda: S("alt", '<div class="grid4 c"><div class="card"><div class="num" style="color:#12a150">99,98 %</div><div class="small">disponibilidad</div></div><div class="card"><div class="num">240 ms</div><div class="small">tiempo de respuesta</div></div><div class="card"><div class="num">1,2 M</div><div class="small">movimientos hoy</div></div><div class="card"><div class="num">0</div><div class="small">incidentes abiertos</div></div></div>')
SEC["topics"] = lambda: S("", '<h2 style="margin-bottom:14px">De qué se habla hoy</h2><div class="grid3"><div class="card"><h3>Cómo salí de deudas</h3><p class="small">128 respuestas</p></div><div class="card"><h3>Mi primer plazo fijo</h3><p class="small">96 respuestas</p></div><div class="card"><h3>Ahorrar con sueldo bajo</h3><p class="small">210 respuestas</p></div></div>')
SEC["members"] = lambda: S("alt", '<h2 style="margin-bottom:14px">Miembros que ayudan</h2><div class="grid4"><div class="card c"><div class="ico" style="margin:0 auto 8px;border-radius:50%">LF</div><b>Lucía</b><p class="small">412 respuestas</p></div><div class="card c"><div class="ico" style="margin:0 auto 8px;border-radius:50%">MG</div><b>Martín</b><p class="small">388 respuestas</p></div><div class="card c"><div class="ico" style="margin:0 auto 8px;border-radius:50%">SR</div><b>Sofía</b><p class="small">301 respuestas</p></div><div class="card c"><div class="ico" style="margin:0 auto 8px;border-radius:50%">JA</div><b>Julián</b><p class="small">275 respuestas</p></div></div>')
SEC["cta_join"] = lambda: '<section class="cta"><div class="w"><h2>Sumate a la comunidad</h2><p style="opacity:.9">Es gratis y podés irte cuando quieras.</p><a class="b big">Quiero sumarme</a></div></section>'
SEC["editions"] = lambda: S("", '<h2 style="margin-bottom:14px">Últimas ediciones</h2><div class="card" style="padding:6px"><table><tr><td><b>#84</b></td><td>El truco del 50-30-20, explicado</td><td class="small">Leer →</td></tr><tr><td><b>#83</b></td><td>Qué hacer con el aguinaldo</td><td class="small">Leer →</td></tr><tr><td><b>#82</b></td><td>Tarjeta de crédito: lo que no te cuentan</td><td class="small">Leer →</td></tr></table></div>')
SEC["subs"] = lambda: S("alt", '<div class="c"><div class="num">21.300</div><p class="small">personas la leen cada jueves</p></div>')
SEC["bio"] = lambda: S("", '<div class="grid2" style="align-items:center"><div class="card c" style="padding:40px"><div class="ico" style="margin:0 auto 10px;border-radius:50%">CP</div><h3>Carla Páez</h3><p class="small">Asesora financiera · 12 años de experiencia</p></div><div><h2>Quién lo da</h2><p class="lead">Ayudó a más de 3.000 personas a salir de deudas.</p></div></div>')
SEC["learn"] = lambda: S("alt", '<h2 style="margin-bottom:14px">Qué vas a aprender</h2><div class="grid3"><div class="card"><h3>Presupuesto simple</h3></div><div class="card"><h3>Gastos hormiga</h3></div><div class="card"><h3>Un fondo de emergencia</h3></div></div>')
SEC["bonus"] = lambda: S("", '<div class="card" style="max-width:640px;margin:0 auto;background:#fff8e1;border-color:#f0d874"><h3>🎁 Bonus para quienes asistan en vivo</h3><p class="small">Plantilla de presupuesto + una consulta de 15 minutos. Se asignan por orden de inscripción.</p></div>')
SEC["form_again"] = lambda: S("alt", '<div style="max-width:440px;margin:0 auto"><div class="form"><h2>Reservá tu lugar</h2><input placeholder="tu@correo.com" aria-label="Email"><a class="b g" style="display:block;text-align:center">Reservar mi lugar</a></div></div>')
SEC["preview_product"] = lambda: S("alt", '<div class="c" style="margin-bottom:20px"><h2>Un adelanto</h2></div><div style="max-width:520px;margin:0 auto">' + MOCK + '</div>')
SEC["proof_count"] = lambda: S("", '<div class="c"><div class="num">3.482</div><p class="small">personas ya se anotaron</p></div>')
SEC["screens"] = lambda: S("alt", '<div style="display:flex;gap:18px;overflow:hidden;justify-content:center"><div class="mock" style="width:200px;flex:none"><small>Inicio</small><div class="n" style="font-size:24px">$ 842.300</div></div><div class="mock" style="width:200px;flex:none"><small>Gastos</small><div class="bars" style="height:70px"><i style="height:60%"></i><i style="height:90%"></i><i style="height:40%"></i></div></div><div class="mock" style="width:200px;flex:none"><small>Metas</small><div class="n" style="font-size:24px">72 %</div></div><div class="mock" style="width:200px;flex:none"><small>Alertas</small><div class="n" style="font-size:24px">3</div></div></div>')
SEC["download"] = lambda: '<section class="cta"><div class="w"><h2>Descargá Plata gratis</h2><div class="row" style="justify-content:center;margin-top:12px"><a class="b big" style="background:#111;color:#fff;margin-top:0">App Store</a><a class="b big" style="background:#111;color:#fff;margin-top:0">Google Play</a></div></div></section>'
SEC["cats_faq"] = lambda: S("alt", '<div class="grid4"><div class="card c"><h3>Primeros pasos</h3></div><div class="card c"><h3>Cuentas</h3></div><div class="card c"><h3>Pagos</h3></div><div class="card c"><h3>Seguridad</h3></div></div>')
SEC["cta_support"] = lambda: '<section class="cta"><div class="w"><h2>¿No encontraste lo que buscabas?</h2><a class="b big">Escribirnos</a></div></section>'
SEC["chapter1"] = lambda: S("alt", '<div style="max-width:620px"><p class="small" style="font-weight:700;letter-spacing:.1em;text-transform:uppercase">Capítulo 1 · El problema</p><h2 style="font-size:34px;margin-top:8px">Cinco apps, ninguna respuesta.</h2><p class="lead">Cada banco mostraba su pedazo. Nadie veía el total.</p></div>')
SEC["chapter2"] = lambda: S("", '<div style="max-width:620px;margin-left:auto;text-align:right"><p class="small" style="font-weight:700;letter-spacing:.1em;text-transform:uppercase">Capítulo 2 · El recorrido</p><h2 style="font-size:34px;margin-top:8px">Conectamos todo en una pantalla.</h2><p class="lead" style="margin-left:auto">Probamos con 40 personas y ajustamos durante un año.</p></div>')
SEC["chapter3"] = lambda: S("alt", '<div style="max-width:620px"><p class="small" style="font-weight:700;letter-spacing:.1em;text-transform:uppercase">Capítulo 3 · La solución</p><h2 style="font-size:34px;margin-top:8px">Hoy tu mes entra en una mano.</h2>' + '<div style="max-width:420px;margin-top:20px">' + MOCK + '</div></div>')
SEC["ba"] = lambda: S("alt", '<div class="c" style="margin-bottom:20px"><h2>Antes y después de Plata</h2></div><div class="grid2"><div class="card"><span class="tag" style="background:#fde8e6">Antes</span><p style="margin:10px 0">5 apps, 2 planillas y la tarjeta sin controlar.</p><div class="num" style="color:#c0392b">−$ 210.000</div><p class="small">de descubierto al mes</p></div><div class="card"><span class="tag" style="background:#e4f6ec">Después</span><p style="margin:10px 0">Una pantalla con todo al día.</p><div class="num" style="color:#12a150">+$ 96.000</div><p class="small">ahorrados al mes</p></div></div>')
SEC["horiz"] = lambda: S("", '<h2 style="margin-bottom:14px">Tu año, paso a paso →</h2><div style="display:flex;gap:16px;overflow-x:auto;padding-bottom:12px;scroll-snap-type:x mandatory"><div class="card" style="min-width:260px;scroll-snap-align:start"><span class="k">Mes 1</span><h3>Conectás tus cuentas</h3></div><div class="card" style="min-width:260px;scroll-snap-align:start"><span class="k">Mes 2</span><h3>Ves tus gastos hormiga</h3></div><div class="card" style="min-width:260px;scroll-snap-align:start"><span class="k">Mes 3</span><h3>Armás tu primera meta</h3></div><div class="card" style="min-width:260px;scroll-snap-align:start"><span class="k">Mes 6</span><h3>Tu fondo de emergencia</h3></div><div class="card" style="min-width:260px;scroll-snap-align:start"><span class="k">Mes 12</span><h3>Tu primera inversión</h3></div></div>')
SEC["cards_detail"] = lambda: S("", '<div class="grid2"><div class="card"><h3>Gastos automáticos</h3><p class="small">Detecta supermercado, transporte y servicios sin que cargues nada.</p></div><div class="card"><h3>Metas con fecha</h3><p class="small">Elegís monto y fecha; Plata calcula cuánto apartar por mes.</p></div></div>')
SEC["strip_value"] = lambda: S("", '<div class="c" style="padding:10px 0"><h2 style="font-size:32px">Una pantalla. Todas tus cuentas.</h2></div>')
SEC["proof_one"] = lambda: S("alt", '<div class="c"><div class="num">12.400 personas</div><p class="small">ya ordenaron su plata con Plata</p></div>')
SEC["use_cases"] = lambda: S("alt", '<div class="grid3"><div class="card"><h3>Para ahorrar</h3><p class="small">Metas con fecha.</p></div><div class="card"><h3>Para salir de deudas</h3><p class="small">Un plan por mes.</p></div><div class="card"><h3>Para vivir en pareja</h3><p class="small">Gastos compartidos.</p></div></div>')
SEC["onboard"] = lambda: S("alt", '<div class="mock" style="max-width:520px;margin:0 auto"><small>Paso 1 de 3 · Recorrido guiado</small><h3 style="margin-top:8px">Elegí tu banco</h3><div class="row" style="margin-top:10px"><span class="tag">Banco Norte</span><span class="tag">Banco Sur</span><span class="tag">Billetera X</span></div><div class="row" style="margin-top:16px"><a class="b">Siguiente</a><a class="b o">Saltear</a></div></div>')
SEC["reveal"] = lambda: S("", '<div class="grid3"><div class="card"><h3>Sin sorpresas</h3><p class="small">Ves lo que vas a gastar antes de gastar.</p></div><div class="card"><h3>Sin carga manual</h3><p class="small">Todo llega solo.</p></div><div class="card"><h3>Sin letra chica</h3><p class="small">Gratis hasta que lo decidas.</p></div></div>')
SEC["cta_end"] = lambda: '<section class="cta"><div class="w"><h2>Ya lo viste: ahora probalo con tu plata</h2><a class="b big">Empezar gratis</a></div></section>'
SEC["fullscreen"] = lambda: S("", '<div style="min-height:340px;border-radius:20px;background:linear-gradient(135deg,#0c1020,#2f5bea);color:#fff;display:grid;place-items:center;text-align:center;padding:30px"><div><h1 style="font-size:44px">Tocá el saldo.</h1><div style="font-size:54px;font-weight:800;margin:12px 0;cursor:pointer" id="sal">$ 842.300</div><p style="opacity:.85">Cada toque abre una parte de tu mes →</p></div></div>', w=True)
SEC["pers_hero"] = SEC["hero_prompt"]
SEC["pers_features"] = lambda: S("", '<div class="c" style="margin-bottom:20px"><span class="tag">Para vos, que querés ahorrar para un viaje</span></div><div class="grid3"><div class="card"><h3>Meta de viaje</h3><p class="small">$ 2.400.000 para marzo.</p></div><div class="card"><h3>Gastos que podés recortar</h3><p class="small">Delivery y suscripciones.</p></div><div class="card"><h3>Aporte recomendado</h3><p class="small">$ 160.000 por mes.</p></div></div>')
SEC["pers_testi"] = lambda: S("alt", '<div class="card" style="max-width:560px;margin:0 auto"><div class="stars">★★★★★</div><p style="margin:10px 0">“Ahorré para mi viaje a Bariloche en 8 meses.”</p><b>Sofía R.</b> <span class="small">· también quería viajar</span></div>')
SEC["cta_smart"] = lambda: '<section class="cta"><div class="w"><h2>Empezá tu plan de viaje hoy</h2><a class="b big">Crear mi meta</a></div></section>'

# ── Paneles ──
DASH_CSS = """body{background:#f1f3f9;font-family:Manrope,system-ui,sans-serif;color:#1a1d29}*{box-sizing:border-box;margin:0}
.top{display:flex;justify-content:space-between;align-items:center;padding:12px 18px;background:#fff;border-bottom:1px solid #e1e4ee}.top b{font-size:17px}.top span{font-size:12.5px;color:#575d70}
.wrap{padding:16px 18px}.card{background:#fff;border:1px solid #e1e4ee;border-radius:12px;padding:14px}.card h4{font-size:12px;color:#575d70;font-weight:700;letter-spacing:.04em;text-transform:uppercase;margin-bottom:8px}
.kpi{font-size:26px;font-weight:800;letter-spacing:-.03em}.up{color:#12a150;font-size:12px;font-weight:700}.dn{color:#c0392b;font-size:12px;font-weight:700}
.g{display:grid;gap:12px}table{width:100%;border-collapse:collapse;font-size:12.5px}th,td{padding:7px 8px;text-align:left;border-bottom:1px solid #eceef6}th{color:#575d70;font-size:11px}
.bar{height:9px;background:#e8ecf7;border-radius:5px;overflow:hidden}.bar i{display:block;height:100%;background:#2f5bea}.row{display:flex;justify-content:space-between;align-items:center;gap:8px}.s{font-size:12px;color:#575d70}
.pill{display:inline-block;padding:3px 9px;border-radius:99px;font-size:11.5px;font-weight:700}.ok{background:#e4f6ec;color:#12804a}.wa{background:#fff3d6;color:#9a6a00}.er{background:#fde8e6;color:#b3261e}
@media(max-width:860px){.g{grid-template-columns:1fr!important}}
"""
def dpage(title, body, js=""):
    return ('<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Plata · ' + title + '</title>'
            '<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>' + DASH_CSS + '</style></head><body>' + body + js + '</body></html>')

def line_svg(vals, w=420, h=110, color="#2f5bea", fill=True, dash_from=None, band=None):
    mx, mn = max(vals), min(vals); rng = (mx - mn) or 1
    pts = [(i * (w - 8) / (len(vals) - 1) + 4, h - 8 - (v - mn) / rng * (h - 20)) for i, v in enumerate(vals)]
    d = " ".join(("M" if i == 0 else "L") + f"{x:.1f},{y:.1f}" for i, (x, y) in enumerate(pts))
    out = f'<svg viewBox="0 0 {w} {h}" width="100%" height="{h}" role="img" aria-label="Gráfico de líneas" preserveAspectRatio="none">'
    if band and dash_from is not None:
        up = " ".join(("M" if i == 0 else "L") + f"{x:.1f},{max(2, y - band * (i - dash_from + 1)):.1f}" for i, (x, y) in enumerate(pts) if i >= dash_from)
        dn = " ".join(f"L{x:.1f},{min(h - 2, y + band * (i - dash_from + 1)):.1f}" for i, (x, y) in reversed(list(enumerate(pts))) if i >= dash_from)
        out += f'<path d="{up} {dn} Z" fill="{color}" opacity=".13"/>'
    if dash_from is None:
        if fill: out += f'<path d="{d} L{pts[-1][0]:.1f},{h} L{pts[0][0]:.1f},{h} Z" fill="{color}" opacity=".12"/>'
        out += f'<path d="{d}" fill="none" stroke="{color}" stroke-width="2.2"/>'
    else:
        a = " ".join(("M" if i == 0 else "L") + f"{x:.1f},{y:.1f}" for i, (x, y) in enumerate(pts[:dash_from + 1]))
        b = " ".join(("M" if i == 0 else "L") + f"{x:.1f},{y:.1f}" for i, (x, y) in enumerate(pts[dash_from:]))
        out += f'<path d="{a}" fill="none" stroke="{color}" stroke-width="2.4"/><path d="{b}" fill="none" stroke="{color}" stroke-width="2.4" stroke-dasharray="6 5"/>'
    return out + '</svg>'

def bars_html(vals, h=90, color="#2f5bea"):
    mx = max(vals)
    return '<div style="display:flex;align-items:flex-end;gap:5px;height:%dpx">' % h + "".join(f'<i style="flex:1;height:{v / mx * 100:.0f}%;background:{color};border-radius:3px 3px 0 0"></i>' for v in vals) + '</div>'

R = random.Random(7)
SERIE = [38, 42, 40, 47, 52, 49, 58, 61, 57, 66, 72, 69, 78, 84]
DASH = {}

# Sin patrón: un volcado de números sin jerarquía
SIN_PANEL = dpage("Sin patrón", '<div class="top"><b>Informe de Plata</b><span>Septiembre</span></div><div class="wrap"><div class="card"><table><tr><th>Concepto</th><th>Ene</th><th>Feb</th><th>Mar</th><th>Abr</th><th>May</th><th>Jun</th><th>Jul</th><th>Ago</th><th>Sep</th></tr>' + "".join(f'<tr><td>{n}</td>' + "".join(f"<td>{R.randint(100, 9999):,}".replace(",", ".") + "</td>" for _ in range(9)) + '</tr>' for n in ["Altas", "Bajas", "Activos", "Ingresos", "Gastos", "Soporte", "Reembolsos", "Churn", "ARPU", "Visitas", "Registros", "Conversión", "Tickets"]) + '</table></div></div>')

# 1 · denso en datos
DASH["data-dense-dashboard"] = dpage("Dashboard denso en datos", '<div class="top"><b>Plata · Operaciones</b><span>Últimos 14 días · actualizado 10:42</span></div><div class="wrap g" style="grid-template-columns:repeat(6,1fr)">'
    + "".join(f'<div class="card"><h4>{t}</h4><div class="kpi" style="font-size:20px">{v}</div><div class="{c}">{d}</div></div>' for t, v, c, d in [("Altas", "1.284", "up", "▲ 8,2 %"), ("Bajas", "212", "dn", "▲ 3,1 %"), ("Activos", "12.4 k", "up", "▲ 1,9 %"), ("Ingresos", "$ 48 M", "up", "▲ 6,4 %"), ("Tickets", "342", "dn", "▲ 12 %"), ("ARPU", "$ 3.870", "up", "▲ 0,8 %")])
    + '<div class="card" style="grid-column:span 3"><h4>Ingresos diarios</h4>' + line_svg(SERIE, 460, 100) + '</div><div class="card" style="grid-column:span 3"><h4>Altas por canal</h4>' + bars_html([30, 52, 44, 70, 38, 61, 80, 55], 100) + '</div>'
    + '<div class="card" style="grid-column:span 3"><h4>Últimas operaciones</h4><table><tr><th>Cliente</th><th>Plan</th><th>Monto</th><th>Estado</th></tr>' + "".join(f'<tr><td>{a}</td><td>{b}</td><td>{c}</td><td><span class="pill {d}">{e}</span></td></tr>' for a, b, c, d, e in [("L. Fernández", "Plus", "$ 2.900", "ok", "Pagó"), ("M. Gómez", "Familia", "$ 4.900", "ok", "Pagó"), ("S. Ramírez", "Plus", "$ 2.900", "wa", "Pendiente"), ("J. Acosta", "Gratis", "$ 0", "ok", "Activo"), ("C. Torres", "Plus", "$ 2.900", "er", "Rechazado"), ("D. Herrera", "Plus", "$ 2.900", "ok", "Pagó")]) + '</table></div>'
    + '<div class="card" style="grid-column:span 3"><h4>Por región</h4>' + "".join(f'<div class="row s" style="margin:6px 0"><span style="width:70px">{n}</span><div class="bar" style="flex:1"><i style="width:{v}%"></i></div><b>{v}%</b></div>' for n, v in [("CABA", 82), ("GBA", 64), ("Córdoba", 41), ("Rosario", 33), ("Mendoza", 22), ("Tucumán", 15)]) + '</div></div>')

# 2 · mapa de calor
cells = ""
dias = ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"]
for di, d in enumerate(dias):
    cells += f'<div class="s" style="align-self:center">{d}</div>'
    for h in range(24):
        base = 0.15 + (0.55 if 8 <= h <= 21 else 0) * (1 - (0.45 if di > 4 else 0)) + (0.3 if h in (12, 13, 20) else 0)
        v = min(1, max(0.05, base + R.uniform(-.12, .12)))
        cells += f'<div title="{d} {h}:00" style="height:24px;border-radius:4px;background:rgba(47,91,234,{v:.2f})"></div>'
DASH["heat-map-heatmap-style"] = dpage("Mapa de calor", '<div class="top"><b>¿Cuándo usa la gente Plata?</b><span>Aperturas de la app por hora y día</span></div><div class="wrap"><div class="card"><h4>Intensidad de uso · últimas 4 semanas</h4><div style="display:grid;grid-template-columns:36px repeat(24,1fr);gap:3px;margin-top:6px"><div></div>' + "".join(f'<div class="s" style="text-align:center;font-size:10px">{h}</div>' for h in range(24)) + cells + '</div><div class="row s" style="margin-top:14px;justify-content:flex-start;gap:10px">Menos<div style="display:flex;gap:2px">' + "".join(f'<i style="width:26px;height:12px;border-radius:3px;background:rgba(47,91,234,{a})"></i>' for a in (.1, .3, .5, .75, 1)) + '</div>Más</div></div><p class="s" style="margin-top:12px">Lectura rápida: el pico es entre las 12 y las 14 h y a las 20 h; los fines de semana el uso baja a la mitad.</p></div>')

# 3 · ejecutivo
DASH["executive-dashboard"] = dpage("Dashboard ejecutivo", '<div class="top"><b>Plata · Resumen del mes</b><span>Septiembre 2026</span></div><div class="wrap" style="max-width:980px;margin:0 auto"><h1 style="font-size:30px;letter-spacing:-.03em;margin:14px 0 16px">El mes va bien: crecemos 6 % y el ahorro de los clientes sube.</h1><div class="g" style="grid-template-columns:repeat(4,1fr)">'
    + "".join(f'<div class="card" style="padding:22px"><h4>{t}</h4><div class="kpi" style="font-size:38px">{v}</div><div class="{c}" style="font-size:14px">{d}</div></div>' for t, v, c, d in [("Ingresos", "$ 48 M", "up", "▲ 6,4 % vs agosto"), ("Clientes activos", "12.4 k", "up", "▲ 1,9 %"), ("Bajas", "1,7 %", "up", "▼ 0,3 pp"), ("Satisfacción", "4,8", "up", "= estable")])
    + '</div><div class="card" style="margin-top:12px;padding:22px"><h4>Ingresos, últimos 14 meses</h4>' + line_svg(SERIE, 900, 120) + '</div><div class="card" style="margin-top:12px;border-left:4px solid #e8a317"><b>Atención:</b> los tickets de soporte subieron 12 %. Detalle en la vista de operaciones.</div></div>')

# 4 · tiempo real
DASH["real-time-monitoring"] = dpage("Monitoreo en tiempo real", '<div class="top"><b>Plata · Estado del sistema</b><span><span class="pill ok">● En vivo</span> <span id="hora">10:42:08</span></span></div><div class="wrap"><div class="g" style="grid-template-columns:repeat(4,1fr)">'
    + "".join(f'<div class="card"><h4>{t}</h4><div class="kpi" id="{i}">{v}</div><span class="pill {c}">{e}</span></div>' for t, i, v, c, e in [("Movimientos / min", "m1", "1.284", "ok", "Normal"), ("Latencia", "m2", "240 ms", "ok", "Normal"), ("Errores", "m3", "0,02 %", "wa", "Vigilar"), ("Cola de pagos", "m4", "12", "ok", "Normal")])
    + '</div><div class="g" style="grid-template-columns:2fr 1fr;margin-top:12px"><div class="card"><h4>Movimientos por minuto</h4><div id="live" style="height:110px"></div></div><div class="card"><h4>Alertas</h4><div style="display:grid;gap:8px;font-size:12.5px"><div><span class="pill er">Crítica</span> Banco Sur sin respuesta · hace 2 min</div><div><span class="pill wa">Aviso</span> Latencia alta en pagos QR · hace 9 min</div><div><span class="pill ok">Resuelta</span> Reintento de notificaciones · hace 31 min</div></div></div></div></div>',
    '<script>(function(){var v=[40,44,42,48,52,49,58,61,57,66,60,64],e=document.getElementById("live");function d(){var w=420,h=110,mx=Math.max.apply(0,v),mn=Math.min.apply(0,v),p=v.map(function(y,i){return(i*(w-8)/(v.length-1)+4)+","+(h-8-(y-mn)/((mx-mn)||1)*(h-20))}).join(" ");e.innerHTML=\'<svg viewBox="0 0 \'+w+" "+h+\'" width="100%" height="110" preserveAspectRatio="none"><polyline points="\'+p+\'" fill="none" stroke="#2f5bea" stroke-width="2.4"/></svg>\'}d();if(matchMedia("(prefers-reduced-motion:reduce)").matches)return;setInterval(function(){v.shift();v.push(Math.max(30,Math.min(80,v[v.length-1]+Math.round((Math.random()-.5)*14))));d();document.getElementById("m1").textContent=(1200+Math.round(Math.random()*160)).toLocaleString("es-AR");document.getElementById("m2").textContent=(220+Math.round(Math.random()*50))+" ms";var t=new Date();document.getElementById("hora").textContent=t.toLocaleTimeString("es-AR")},1200)})()</script>')

# 5 · drill-down
DASH["drill-down-analytics"] = dpage("Analítica con drill-down", '<div class="top"><b>Ventas por región</b><span id="mig">Total</span></div><div class="wrap"><div class="card" style="max-width:760px;margin:0 auto"><div class="s" id="crumbs" style="margin-bottom:10px"><b>Total</b></div><div id="lista"></div><p class="s" style="margin-top:12px">Tocá una barra para bajar un nivel · tocá «Total» para volver.</p></div></div>',
    '<script>(function(){var D={"Total":[["Buenos Aires",52],["Córdoba",21],["Santa Fe",14],["Mendoza",8],["Otras",5]],"Buenos Aires":[["CABA",58],["Zona Norte",18],["Zona Oeste",14],["Zona Sur",10]],"CABA":[["Almagro",24],["Palermo",31],["Caballito",22],["Belgrano",23]]};var path=["Total"];function r(){var n=path[path.length-1],l=D[n];document.getElementById("crumbs").innerHTML=path.map(function(p,i){return(i<path.length-1?\'<a href="#" data-i="\'+i+\'" style="color:#2f5bea;font-weight:700">\'+p+"</a> › ":"<b>"+p+"</b>")}).join("");document.getElementById("lista").innerHTML=l.map(function(x){return\'<div class="row" data-n="\'+x[0]+\'" style="margin:9px 0;cursor:\'+(D[x[0]]?"pointer":"default")+\'"><span style="width:110px;font-size:13px;font-weight:600">\'+x[0]+\'</span><div class="bar" style="flex:1;height:16px"><i style="width:\'+x[1]*1.6+\'%"></i></div><b style="width:44px;text-align:right">\'+x[1]+"%</b></div>"}).join("")}document.addEventListener("click",function(e){var a=e.target.closest("[data-i]");if(a){e.preventDefault();path=path.slice(0,+a.dataset.i+1);r();return}var b=e.target.closest("[data-n]");if(b&&D[b.dataset.n]){path.push(b.dataset.n);r()}});r()})()</script>')

# 6 · comparativo
DASH["comparative-analysis-dashboard"] = dpage("Dashboard comparativo", '<div class="top"><b>Agosto contra septiembre</b><span>Período contra período</span></div><div class="wrap"><div class="card"><table><tr><th>Métrica</th><th>Agosto</th><th>Septiembre</th><th>Cambio</th></tr>' + "".join(f'<tr><td><b>{a}</b></td><td>{b}</td><td>{c}</td><td class="{d}" style="font-weight:700">{e}</td></tr>' for a, b, c, d, e in [("Altas", "1.187", "1.284", "up", "▲ 8,2 %"), ("Ingresos", "$ 45,1 M", "$ 48,0 M", "up", "▲ 6,4 %"), ("Bajas", "198", "212", "dn", "▲ 7,1 %"), ("Tickets", "305", "342", "dn", "▲ 12,1 %"), ("Satisfacción", "4,8", "4,8", "s", "= 0")]) + '</table></div><div class="g" style="grid-template-columns:1fr 1fr;margin-top:12px"><div class="card"><h4>Test A/B · botón de registro</h4><div class="s">Versión A (verde)</div><div class="bar" style="height:16px;margin:4px 0 10px"><i style="width:34%;background:#9aa6c6"></i></div><div class="s">Versión B (azul) · <b style="color:#12a150">gana +2,3 pp</b></div><div class="bar" style="height:16px;margin-top:4px"><i style="width:47%"></i></div></div><div class="card"><h4>Por región · septiembre vs agosto</h4>' + "".join(f'<div class="row s" style="margin:7px 0"><span style="width:70px">{n}</span><div style="flex:1;display:flex;gap:3px"><div class="bar" style="flex:1"><i style="width:{a}%;background:#9aa6c6"></i></div><div class="bar" style="flex:1"><i style="width:{b}%"></i></div></div></div>' for n, a, b in [("CABA", 70, 78), ("GBA", 52, 58), ("Córdoba", 34, 38)]) + '</div></div></div>')

# 7 · predictivo
PRED = [38, 42, 40, 47, 52, 49, 58, 63, 68, 73, 79, 85]
DASH["predictive-analytics"] = dpage("Analítica predictiva", '<div class="top"><b>Ingresos: pronóstico a 6 meses</b><span>Modelo actualizado hoy</span></div><div class="wrap"><div class="g" style="grid-template-columns:2fr 1fr"><div class="card"><h4>Real y proyección (la línea punteada es el pronóstico)</h4>' + line_svg(PRED, 640, 190, dash_from=5, band=4) + '<div class="row s" style="margin-top:8px"><span>Mar ... Ago (real)</span><span>Sep ... Feb (pronóstico, banda de confianza 80 %)</span></div></div><div class="card"><h4>Escenarios a febrero</h4><div style="display:grid;gap:12px"><div><div class="row"><span class="s">Optimista</span><b>$ 92 M</b></div><div class="bar"><i style="width:92%;background:#12a150"></i></div></div><div><div class="row"><span class="s">Esperado</span><b>$ 85 M</b></div><div class="bar"><i style="width:85%"></i></div></div><div><div class="row"><span class="s">Prudente</span><b>$ 74 M</b></div><div class="bar"><i style="width:74%;background:#e8a317"></i></div></div></div></div></div><div class="card" style="margin-top:12px;border-left:4px solid #e8a317"><b>Alerta anticipada:</b> se espera un aumento de bajas en diciembre (+9 %). Conviene reforzar el soporte en noviembre.</div></div>')

# 8 · comportamiento
DASH["user-behavior-analytics"] = dpage("Analítica de comportamiento de usuarios", '<div class="top"><b>Embudo de registro</b><span>Últimos 30 días</span></div><div class="wrap"><div class="g" style="grid-template-columns:2fr 1fr"><div class="card"><h4>De la visita a la cuenta activa</h4>' + "".join(f'<div style="margin:10px 0"><div class="row s"><b style="color:#1a1d29">{n}</b><span>{v} · {p}</span></div><div class="bar" style="height:26px;margin-top:4px;width:{w}%;border-radius:6px"><i style="width:100%;opacity:{o}"></i></div></div>' for n, v, p, w, o in [("Visitaron la página", "48.200", "100 %", 100, 1), ("Empezaron el registro", "9.640", "20 %", 80, .85), ("Conectaron una cuenta", "5.120", "11 %", 56, .7), ("Vieron su primer resumen", "4.380", "9 %", 46, .55), ("Siguen activos a los 7 días", "3.690", "7,7 %", 38, .4)]) + '<p class="s" style="margin-top:10px"><b style="color:#c0392b">La mayor pérdida está en el paso 2 → 3</b>: 47 % abandona al conectar la cuenta.</p></div><div class="card"><h4>Recorrido más común</h4><div style="display:grid;gap:8px;font-size:12.5px"><div class="pill ok">Inicio</div><div class="s">↓ 62 %</div><div class="pill ok">Conectar cuenta</div><div class="s">↓ 44 %</div><div class="pill wa">Ayuda / FAQ</div><div class="s">↓ 31 %</div><div class="pill er">Abandona</div></div></div></div></div>')

# 9 · financiero
DASH["financial-dashboard"] = dpage("Dashboard financiero", '<div class="top"><b>Plata · Finanzas</b><span>Septiembre 2026 · en pesos</span></div><div class="wrap"><div class="g" style="grid-template-columns:repeat(4,1fr)">' + "".join(f'<div class="card"><h4>{t}</h4><div class="kpi">{v}</div><div class="{c}">{d}</div></div>' for t, v, c, d in [("Facturación", "$ 48,0 M", "up", "▲ 6,4 %"), ("Costos", "$ 31,2 M", "dn", "▲ 3,0 %"), ("Resultado", "$ 16,8 M", "up", "▲ 13,5 %"), ("Margen", "35 %", "up", "▲ 2,2 pp")])
    + '</div><div class="g" style="grid-template-columns:1fr 1fr;margin-top:12px"><div class="card"><h4>Ganancias y pérdidas</h4><table><tr><td>Facturación</td><td style="text-align:right">$ 48.000.000</td></tr><tr><td>(−) Sueldos</td><td style="text-align:right">$ 18.400.000</td></tr><tr><td>(−) Infraestructura</td><td style="text-align:right">$ 6.900.000</td></tr><tr><td>(−) Marketing</td><td style="text-align:right">$ 5.900.000</td></tr><tr style="font-weight:800"><td>Resultado</td><td style="text-align:right;color:#12a150">$ 16.800.000</td></tr></table></div><div class="card"><h4>Presupuesto del mes</h4>' + "".join(f'<div style="margin:9px 0"><div class="row s"><span>{n}</span><b>{p} %</b></div><div class="bar"><i style="width:{min(p, 100)}%;background:{"#c0392b" if p > 100 else "#2f5bea"}"></i></div></div>' for n, p in [("Sueldos", 96), ("Infraestructura", 88), ("Marketing", 112), ("Soporte", 71)]) + '</div></div><div class="card" style="margin-top:12px"><h4>Flujo de caja, 14 semanas</h4>' + line_svg(SERIE, 900, 90) + '</div></div>')

# 10 · inteligencia comercial
DASH["sales-intelligence-dashboard"] = dpage("Dashboard de inteligencia comercial", '<div class="top"><b>Plata · Ventas a empresas</b><span>Trimestre en curso</span></div><div class="wrap"><div class="card"><h4>Pipeline de negocios</h4><div style="display:grid;grid-template-columns:repeat(5,1fr);gap:8px">' + "".join(f'<div style="background:#f1f4fc;border-radius:10px;padding:12px;text-align:center"><div class="s">{n}</div><div class="kpi" style="font-size:24px">{c}</div><div class="s">{m}</div></div>' for n, c, m in [("Prospectos", "142", "$ 98 M"), ("Contactados", "86", "$ 71 M"), ("Propuesta", "41", "$ 46 M"), ("Negociación", "19", "$ 28 M"), ("Ganados", "12", "$ 17 M")]) + '</div></div><div class="g" style="grid-template-columns:1fr 1fr;margin-top:12px"><div class="card"><h4>Ranking de vendedores</h4><table><tr><th>#</th><th>Vendedor</th><th>Ganado</th><th>Meta</th></tr>' + "".join(f'<tr><td>{i}</td><td>{n}</td><td>{g}</td><td><div class="bar" style="width:90px"><i style="width:{m}%;background:{"#12a150" if m >= 100 else "#2f5bea"}"></i></div></td></tr>' for i, (n, g, m) in enumerate([("Carla P.", "$ 5,2 M", 104), ("Diego R.", "$ 4,6 M", 92), ("Luis M.", "$ 3,9 M", 78), ("Ana F.", "$ 3,3 M", 66)], 1)) + '</table></div><div class="card"><h4>Rendimiento por zona</h4>' + "".join(f'<div class="row s" style="margin:8px 0"><span style="width:80px">{n}</span><div class="bar" style="flex:1"><i style="width:{v}%"></i></div><b>{v} %</b></div>' for n, v in [("CABA", 88), ("GBA", 71), ("Centro", 55), ("Cuyo", 41), ("Norte", 33)]) + '<p class="s" style="margin-top:10px"><b>Tasa de cierre:</b> 8,5 % · <b>ciclo medio:</b> 34 días</p></div></div></div>')

PANEL_TXT = {
    "data-dense-dashboard": ("Mucha información en una sola pantalla, con casi nada de espacio entre piezas: seis indicadores arriba, dos gráficos, una tabla y un reparto por región. Sirve a quien analiza todo el día y necesita ver todo junto.", "Sin el patrón: los mismos datos volcados en una tabla de doce meses sin gráficos ni jerarquía; hay que leerla número por número."),
    "heat-map-heatmap-style": ("La intensidad se lee por color: cuanto más oscuro el cuadrado, más uso. En un vistazo se ven el pico del mediodía y de la noche y la caída de los fines de semana, sin leer un solo número.", "Sin el patrón: una tabla de 168 números por hora y día; el patrón existe, pero no se ve."),
    "executive-dashboard": ("Pocas cifras, grandes, con su tendencia, y una frase arriba que dice cómo va el mes. Todo lo demás se oculta; solo se destaca lo que pide atención.", "Sin el patrón: la tabla detallada de doce meses; quien decide tiene que buscar la conclusión."),
    "real-time-monitoring": ("Los datos se actualizan solos: un gráfico que avanza, indicadores con estado (normal, vigilar, crítico) y una lista de alertas ordenada por urgencia. Es para detectar problemas apenas pasan.", "Sin el patrón: una tabla estática de números que hay que recargar para ver si algo cambió."),
    "drill-down-analytics": ("Se empieza por el total y se baja de a un nivel tocando una barra: del país a la provincia, de ahí a la zona. El camino queda arriba para volver cuando quieras.", "Sin el patrón: una tabla enorme con todos los niveles mezclados."),
    "comparative-analysis-dashboard": ("Dos períodos lado a lado con el cambio al final de cada fila, el resultado de un test A/B con el ganador marcado y una comparación por región. La comparación es el centro de la pantalla.", "Sin el patrón: los números de cada mes en tablas separadas; el cambio hay que calcularlo a mano."),
    "predictive-analytics": ("A la línea real se le suma un pronóstico punteado con su banda de confianza, tres escenarios y una alerta anticipada. Se mira hacia adelante, no hacia atrás.", "Sin el patrón: solo el histórico; no dice qué se espera ni con qué margen."),
    "user-behavior-analytics": ("El embudo muestra cuánta gente se pierde en cada paso y marca el paso más grave en rojo; al costado, el recorrido más común. Se entiende de un vistazo dónde mejorar.", "Sin el patrón: los totales de cada paso en una tabla; no se ve dónde está la mayor pérdida."),
    "financial-dashboard": ("Los indicadores clave arriba (facturación, costos, resultado, margen), el resultado desglosado, el presupuesto con avisos cuando se pasa y el flujo de caja. Pensado para controlar el estado del negocio.", "Sin el patrón: una tabla de cifras sin presupuesto ni alertas; no se ve qué se pasó."),
    "sales-intelligence-dashboard": ("El pipeline por etapas con monto, el ranking de vendedores contra su meta, el rendimiento por zona y los indicadores de cierre. Todo lo que necesita un equipo comercial para decidir dónde poner esfuerzo.", "Sin el patrón: una lista de negocios sin etapas ni metas."),
}

LANDING = {
    # id: (cols, secs-list, nav, theme, cambia, js, prueba)
    "hero-features-cta": ("landing", ["hero", "value", "features3", "cta", "footer"], "std", "", "Una secuencia corta y conocida: promesa con imagen, una frase de valor, tres funciones y un único llamado al final. Cada bloque prepara el siguiente."),
    "hero-testimonials-cta": ("landing", ["hero_problem", "solution", "testimonials", "cta", "footer"], "min", "", "Primero se nombra el problema, después la solución y recién entonces las voces de otros clientes, justo antes de pedir la acción. La prueba social llega cuando la duda es más fuerte."),
    "product-demo-features": ("landing", ["hero_c", "demo_mock", "features3", "cta", "footer"], "std", "", "El producto está en el centro y se puede tocar: mové el control y el resultado cambia. Las funciones aparecen después, ya con la persona convencida de que sirve."),
    "minimal-single-column": ("landing", ["hero_min", "features3", "cta", "footer"], "none", "", "Una sola columna sin menú: titular, descripción corta, tres beneficios y un botón. Sin distracciones y pensada primero para el celular."),
    "funnel-3-step-conversion": ("landing", ["hero_problem", "steps3", "form", "footer"], "min", "", "La persona avanza de a un paso: el problema, cómo se resuelve en tres pasos y la acción. Cada sección muestra solo lo necesario para llegar a la siguiente."),
    "comparison-table-cta": ("landing", ["hero_problem", "compare", "pricing", "cta", "footer"], "min", "", "La página se apoya en una tabla que compara la opción propia contra las alternativas, con la fila propia resaltada, y cierra con precios y un solo llamado."),
    "lead-magnet-form": ("landing", ["hero_lead", "lead_preview", "form_lead", "footer"], "none", "", "Se ofrece algo útil a cambio del email: una tapa del material, qué trae adentro y un formulario corto. Sin menú ni salidas."),
    "pricing-page-cta": ("landing", ["hero_pricing", "pricing", "matrix", "faq", "cta", "footer"], "std", "", "Los precios son el centro: tres planes con el recomendado destacado, la tabla que explica las diferencias y las preguntas que frenan la compra."),
    "video-first-hero": ("landing", ["hero_video", "features3", "value", "cta", "footer"], "std", "dark", "Arriba de todo va un video (con subtítulos, sin necesitar sonido) y las funciones aparecen debajo, ya con el producto visto en acción."),
    "scroll-triggered-storytelling": ("landing", ["hero_story", "chapter1", "chapter2", "chapter3", "cta_end", "footer"], "min", "", "La página se lee como capítulos: el problema, el recorrido y la solución, y el llamado a la acción llega al final, en el momento de mayor interés."),
    "ai-personalization-landing": ("landing", ["pers_hero", "prompt_preview", "pers_features", "pers_testi", "cta_smart", "footer"], "min", "", "El contenido se adapta a lo que cuenta la persona: el titular, las funciones y hasta el testimonio hablan de su caso (en el ejemplo, ahorrar para un viaje)."),
    "waitlist-coming-soon": ("landing", ["hero_count", "preview_product", "proof_count", "footer"], "none", "", "Antes del lanzamiento: cuenta regresiva, un adelanto del producto, un formulario para dejar el email y la cantidad de personas anotadas."),
    "comparison-table-focus": ("landing", ["hero_problem", "compare", "features6", "cta", "footer"], "min", "", "Todo gira en torno a la matriz comparativa: se plantea el problema, se compara con hechos y las funciones se explican después a fondo."),
    "pricing-focused-landing": ("landing", ["hero_c", "pricing", "matrix", "faq", "cta", "footer"], "std", "", "La propuesta de valor es corta y enseguida vienen los tres niveles de precio, con el del medio destacado como «más elegido»."),
    "app-store-style-landing": ("landing", ["hero_device", "screens", "features_icons", "reviews_break", "download", "footer"], "std", "", "Imita una ficha de tienda de aplicaciones: el celular con la app, capturas, funciones con íconos, calificaciones y botones de descarga."),
    "faq-documentation-landing": ("landing", ["hero_faq", "cats_faq", "faq", "cta_support", "footer"], "std", "", "La página es un centro de ayuda: buscador, categorías populares, preguntas en acordeón y una salida clara hacia soporte."),
    "immersive-interactive-experience": ("landing", ["fullscreen", "onboard", "reveal", "cta_end", "footer"], "none", "dark", "Arranca con un elemento interactivo a pantalla completa (tocá el saldo), sigue con un recorrido guiado que se puede saltear y termina con un llamado."),
    "event-conference-landing": ("landing", ["hero_event", "speakers", "agenda", "sponsors", "cta_event", "footer"], "std", "", "Responde primero lo esencial de un evento (fecha, lugar y cuenta regresiva) y después quiénes hablan, la agenda y quién lo apoya."),
    "product-review-ratings-focused": ("landing", ["hero_rating", "reviews_break", "reviews_list", "cta", "footer"], "std", "", "La calificación promedio está arriba, con su desglose por estrellas y reseñas individuales verificadas, antes de pedir la compra."),
    "community-forum-landing": ("landing", ["hero_community", "topics", "members", "cta_join", "footer"], "std", "", "Muestra que la comunidad está viva: cantidad de miembros, los temas del día y quiénes más ayudan, antes de invitar a sumarse."),
    "before-after-transformation": ("landing", ["hero_problem", "ba", "steps3", "cta_results", "footer"], "min", "", "Se muestra la transformación con números reales: cómo estaba la persona antes, cómo está después y en qué pasos se llega."),
    "marketplace-directory": ("landing", ["hero_search", "categories", "listings", "trust", "cta_host", "footer"], "std", "", "El buscador es la acción principal: categorías populares, resultados destacados, seguridad y una invitación para quienes quieran ofrecer."),
    "newsletter-content-first": ("landing", ["hero_news", "editions", "subs", "bio", "footer"], "min", "", "El formulario, de un solo campo, está arriba. Debajo se muestra qué se recibe (ediciones recientes), cuánta gente la lee y quién la escribe."),
    "webinar-registration": ("landing", ["hero_webinar", "learn", "bio", "bonus", "form_again", "footer"], "none", "", "Tema, fecha, cuenta regresiva y formulario arriba; abajo qué se aprende, quién lo da, un bonus para quienes asistan y el formulario otra vez."),
    "enterprise-gateway": ("landing", ["hero_mission", "industries", "roles", "logos", "cta_sales", "footer"], "std", "", "Una empresa grande tiene muchos públicos: se elige el camino por industria o por rol, se muestran clientes conocidos y se cierra con contacto a ventas."),
    "portfolio-grid": ("landing", ["hero_name", "projects", "about", "contact", "footer"], "std", "", "Lo visual va primero: nombre y rol, una grilla de proyectos de distinto tamaño, una breve presentación y el contacto."),
    "horizontal-scroll-journey": ("landing", ["hero_c", "horiz", "cards_detail", "footer"], "std", "", "Un tramo de la página se recorre hacia el costado (deslizá las tarjetas): sirve para contar una secuencia, como los meses de un año."),
    "bento-grid-showcase": ("landing", ["hero_c", "bento", "cards_detail", "specs", "cta", "footer"], "std", "", "Las funciones se muestran en tarjetas de distintos tamaños; la más importante es la más grande. Mucha información sin amontonar."),
    "interactive-3d-configurator": ("landing", ["hero_config", "specs", "price_buy", "footer"], "std", "", "El producto se arma ahí mismo: elegí el color y la tarjeta cambia en 3D, con el precio y la compra justo debajo."),
    "ai-driven-dynamic-landing": ("landing", ["hero_prompt", "prompt_preview", "steps3", "value", "footer"], "min", "", "El primer elemento es un campo donde la persona cuenta su caso y el resultado aparece enseguida. Se demuestra el valor antes de explicarlo."),
    "feature-rich-showcase": ("landing", ["hero_c", "features6", "use_cases", "logos", "cta", "footer"], "std", "", "Seis funciones en tarjetas, casos de uso y logos de prensa. Para productos con mucho para mostrar."),
    "hero-centric-design": ("landing", ["hero_big", "strip_value", "proof_one", "cta", "footer"], "none", "", "Casi todo se juega en el primer pantallazo: un titular enorme sobre color a todo el ancho, una frase de valor, una prueba y un solo botón."),
    "trust-authority-conversion": ("landing", ["hero_trust", "trust", "stats", "solution", "form", "footer"], "min", "", "La credibilidad va antes de pedir nada: certificaciones, auditorías y cifras reales, y recién después un camino corto hacia la acción."),
    "real-time-operations-landing": ("landing", ["hero_live", "live_metrics", "steps3", "cta_sales", "footer"], "std", "", "El estado del producto se ve en vivo desde la portada: movimientos que llegan, indicadores de disponibilidad y una prueba para empezar."),
}
PAGINAS = {  # patrones de página que viven en la colección de estilos
    "minimal-direct": ("estilos", ["hero_min", "features3", "cta", "footer"], "none", "", "Poco texto, mucho aire y una sola columna: un mensaje directo, tres beneficios y un botón. Carga rápido y se lee en segundos."),
    "social-proof-focused": ("estilos", ["hero", "logos", "testimonials", "stats", "cta", "footer"], "std", "", "La prueba social está al frente: logos de prensa, testimonios con nombre, cifras reales y recién después la invitación a actuar."),
    "interactive-product-demo": ("estilos", ["hero_c", "demo_mock", "onboard", "cta", "footer"], "std", "", "El producto se prueba sin registrarse: mové el control y mirá el resultado, y un recorrido guiado explica el resto."),
    "trust-authority": ("estilos", ["hero_trust", "trust", "case_metrics", "logos", "form", "footer"], "std", "", "Certificados, auditorías, casos con números y prensa conocida: lo que necesita ver quien va a confiar dinero o datos."),
    "storytelling-driven": ("estilos", ["hero_story", "chapter1", "chapter2", "chapter3", "cta_end", "footer"], "min", "", "Una historia con principio, recorrido y final: la marca se entiende por lo que le pasó a la gente y no por una lista de funciones."),
}

SWITCH_JS = '<script>(function(){var c=document.getElementById("card3d");if(!c)return;document.querySelectorAll("#sw .tag").forEach(function(b){b.addEventListener("click",function(){c.style.background=b.dataset.c;c.style.transform="rotateY(18deg) rotateX(-4deg)"; setTimeout(function(){c.style.transform="rotateY(-18deg) rotateX(6deg)"},350)})})})()</script>'
PRUEBA = {"product-demo-features", "interactive-product-demo", "interactive-3d-configurator", "immersive-interactive-experience", "horizontal-scroll-journey", "real-time-monitoring", "drill-down-analytics", "faq-documentation-landing"}

def build_extra():
    out = {}
    for pid, (col, secs, nav, theme, cambia) in {**{k: (v[0], v[1], v[2], v[3], v[4]) for k, v in LANDING.items()}, **{k: v for k, v in PAGINAS.items()}}.items():
        body = NAVS[nav] + "".join(SEC[s]() for s in secs)
        title = pid.replace("-", " ").capitalize()
        out[(col, pid)] = dict(html=page(title, body, theme=theme, js=SWITCH_JS if "hero_config" in secs else ""), titulo=title, cambia=cambia,
                              antes="Sin el patrón: la oferta de Plata en una página donde compiten cinco botones del mismo peso, tres menús, una promo y un login.", prueba=pid in PRUEBA)
    for pid, html in DASH.items():
        c, a = PANEL_TXT[pid]
        out[("estilos", pid)] = dict(html=html, titulo=pid, cambia=c, antes=a, antes_file="prog-ejemplos/patrones/_sin-panel.html", prueba=pid in PRUEBA)
    return out
