#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Tercer grupo de ejemplos de negocios (ver lab_demos_negocios.py)."""
from lab_demos_negocios import page, B

# ───────── Turismo · Cabañas Los Coihues ─────────
B["turismo"] = page("Cabañas Los Coihues", "family=Playfair+Display:ital,wght@0,500;0,700;1,500&family=Lato:wght@400;700",
    dict(bg="#f1efe6", ink="#1f3d33", pri="#1f3d33", **{"pri-ink": "#fff"}, r="4px", f1="'Playfair Display',serif", f2="Lato,sans-serif"),
    """.hero{position:relative;min-height:560px;color:#fff;background:linear-gradient(180deg,rgba(15,35,28,.25),rgba(15,35,28,.65)),radial-gradient(ellipse at 50% 85%,#6fb0c8 0 18%,transparent 19%),linear-gradient(180deg,#9ec7d6 0 55%,#3c6f5c 55% 100%);display:grid;align-content:space-between}
.hero nav{display:flex;justify-content:space-between;align-items:center;padding:22px 0;font-size:13px;letter-spacing:.14em;text-transform:uppercase}.hero nav b{font:700 26px var(--f1);text-transform:none;letter-spacing:0}.hero nav div{display:flex;gap:24px;align-items:center}.lang button{background:transparent;border:1px solid rgba(255,255,255,.6);color:#fff;padding:4px 10px;font:700 12px var(--f2);cursor:pointer}.lang button.on{background:#fff;color:#1f3d33}
.hero h1{font-size:clamp(46px,7vw,92px);line-height:.98;font-style:italic;font-weight:500;max-width:14ch;margin-bottom:26px}.hero .w{padding-bottom:50px}
.cab{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.cab article{background:#fff;overflow:hidden}.cab .im{height:180px;display:grid;place-items:center;font-size:60px}.cab .tx{padding:20px}.cab h3{font-size:24px}.cab small{opacity:.7;display:block;margin:4px 0 10px}.cab .pr{font:700 22px var(--f1)}.cab .pr span{font:400 14px var(--f2);opacity:.6}
.cal{background:#fff;padding:30px;display:grid;grid-template-columns:1fr 1fr;gap:34px}.cal .g7{display:grid;grid-template-columns:repeat(7,1fr);gap:4px;text-align:center}.cal .g7 b{font-size:12px;opacity:.6;padding:6px 0}.cal .g7 button{aspect-ratio:1;border:0;background:#f1efe6;cursor:pointer;font:700 14px var(--f2)}.cal .g7 button.x{background:transparent;text-decoration:line-through;opacity:.3;cursor:not-allowed}.cal .g7 button.in{background:#cfe3d8}.cal .g7 button.s{background:#1f3d33;color:#fff}.cal .res{align-self:center}.cal .res .num{font:700 40px var(--f1)}.cal .btn{margin-top:14px}.cal small{display:block;margin-top:10px;opacity:.65}
.act{display:flex;flex-wrap:wrap;gap:10px}.act span{border:1px solid #1f3d33;padding:8px 16px;border-radius:99px;font-weight:700;font-size:14px}""",
    '<header class="hero"><div class="w" style="width:100%"><nav><b>Los Coihues</b><div><a data-k="n1">Cabañas</a><a data-k="n2">Disponibilidad</a><span class="lang" id="lg"><button class="on" data-l="es">ES</button><button data-l="en">EN</button></span></div></nav></div><div class="w"><h1 data-k="h">Despertate frente al lago.</h1><a class="btn" href="#disp" data-k="cta" style="background:#fff;color:#1f3d33">Ver disponibilidad</a></div></header>'
    '<section class="sec"><div class="w"><h2 data-k="t1">Nuestras cabañas</h2><div class="cab" id="cb"></div></div></section>'
    '<section class="sec" id="disp" style="padding-top:0"><div class="w"><h2 data-k="t2">Elegí tus fechas · Octubre</h2><div class="cal"><div><div class="g7" id="cl"></div></div><div class="res"><div class="num" id="rn">—</div><p id="rt" data-k="rt">Elegí la fecha de llegada y la de salida</p><button class="btn" id="rb" data-k="rb">Reservar con seña por Mercado Pago</button><small data-k="rs">Cancelación gratuita hasta 7 días antes.</small></div></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w"><h2 data-k="t3">Qué hacer en la zona</h2><div class="act"><span>Kayak en el lago</span><span>Senderos al mirador</span><span>Cervecería artesanal</span><span>Cabalgatas</span></div></div></section><footer>Cabañas Los Coihues · Villa La Angostura, Neuquén</footer>',
    """<script>(function(){var T={es:{n1:'Cabañas',n2:'Disponibilidad',h:'Despertate frente al lago.',cta:'Ver disponibilidad',t1:'Nuestras cabañas',t2:'Elegí tus fechas · Octubre',rt:'Elegí la fecha de llegada y la de salida',rb:'Reservar con seña por Mercado Pago',rs:'Cancelación gratuita hasta 7 días antes.',t3:'Qué hacer en la zona',n:' noches'},en:{n1:'Cabins',n2:'Availability',h:'Wake up by the lake.',cta:'Check availability',t1:'Our cabins',t2:'Pick your dates · October',rt:'Choose check-in and check-out',rb:'Book with deposit (Mercado Pago)',rs:'Free cancellation up to 7 days before.',t3:'Things to do nearby',n:' nights'}},L='es',C=[['Cabaña Lago','2 a 4 personas · vista al lago',98000,'🏞️','linear-gradient(135deg,#9ec7d6,#4d8aa3)'],['Cabaña Bosque','2 personas · entre coihues',82000,'🌲','linear-gradient(135deg,#a9c9a0,#4c7d5a)'],['Cabaña Familia','4 a 6 personas · parrilla propia',126000,'🔥','linear-gradient(135deg,#e6c79a,#b87d3b)']],a=null,b=null,busy=[8,9,14,15,16,22];
document.getElementById('cb').innerHTML=C.map(function(c){return'<article><div class="im" style="background:'+c[4]+'">'+c[3]+'</div><div class="tx"><h3>'+c[0]+'</h3><small>'+c[1]+'</small><div class="pr">$ '+c[2].toLocaleString('es-AR')+' <span>/ noche</span></div></div></article>'}).join('');
var cl=document.getElementById('cl'),h='';['L','M','M','J','V','S','D'].forEach(function(d){h+='<b>'+d+'</b>'});h+='<span></span><span></span><span></span>';for(var d=1;d<=31;d++)h+='<button data-d="'+d+'"'+(busy.indexOf(d)>=0?' class="x"':'')+'>'+d+'</button>';cl.innerHTML=h;
function u(){var bs=cl.querySelectorAll('button');bs.forEach(function(x){var d=+x.dataset.d;x.classList.remove('in','s');if(a&&d===a||b&&d===b)x.classList.add('s');else if(a&&b&&d>a&&d<b)x.classList.add('in')});var n=a&&b?b-a:0,r=document.getElementById('rn');r.textContent=n?n+T[L].n:'—';if(n)document.getElementById('rt').textContent=(L==='es'?'Del ':'From ')+a+(L==='es'?' al ':' to ')+b+(L==='es'?' de octubre · desde $ '+(n*82000).toLocaleString('es-AR'):' October · from $ '+(n*82000).toLocaleString('es-AR')); else document.getElementById('rt').textContent=T[L].rt}
cl.onclick=function(e){var x=e.target.closest('button');if(!x||x.classList.contains('x'))return;var d=+x.dataset.d;if(!a||(a&&b)){a=d;b=null}else if(d>a){var ok=true;for(var i=a;i<=d;i++)if(busy.indexOf(i)>=0)ok=false;if(ok)b=d;else{a=d;b=null}}else{a=d;b=null}u()};
document.getElementById('lg').onclick=function(e){var x=e.target.closest('button');if(!x)return;L=x.dataset.l;this.querySelectorAll('button').forEach(function(y){y.classList.toggle('on',y===x)});document.documentElement.lang=L;document.querySelectorAll('[data-k]').forEach(function(el){if(T[L][el.dataset.k])el.textContent=T[L][el.dataset.k]});u()};
document.getElementById('rb').onclick=function(){wa(a&&b?'Reserva del '+a+' al '+b+' de octubre (seña por Mercado Pago, simulada)':'Primero elegí las fechas')}})()</script>""")

# ───────── Educación · Instituto Horizonte ─────────
B["educacion"] = page("Instituto Horizonte", "family=Outfit:wght@400;500;600;700;800",
    dict(bg="#f5f8ff", ink="#0b2a5b", pri="#2f6bff", **{"pri-ink": "#fff"}, r="14px", f1="Outfit,sans-serif", f2="Outfit,sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:center;padding:18px 0}nav b{font-size:24px;font-weight:800;display:flex;align-items:center;gap:8px}nav b i{width:32px;height:32px;border-radius:50%;background:linear-gradient(135deg,#ff8a00,#ffc23d);display:block}nav div{display:flex;gap:24px;font-weight:500;font-size:15px}
.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:30px;align-items:center;padding:26px 0 54px}.hero h1{font-size:clamp(44px,6.5vw,78px);line-height:.98;font-weight:800;letter-spacing:-.04em}.hero h1 em{font-style:normal;color:#2f6bff}.hero p{font-size:19px;margin:16px 0 26px;opacity:.75;max-width:38ch}.hero .stats{display:flex;gap:26px;margin-top:30px}.hero .stats b{font-size:32px;display:block}.hero .stats span{font-size:14px;opacity:.7}
.cap{background:#0b2a5b;border-radius:30px;padding:34px;color:#fff}.cap h3{font-size:22px;margin-bottom:14px}.cap input,.cap select{width:100%;padding:14px;border-radius:12px;border:0;margin-bottom:10px;font:500 15px var(--f2)}.cap .btn{background:#ff8a00;width:100%;justify-content:center}
.cur{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.cur article{background:#fff;border-radius:24px;padding:24px;border:1px solid #dfe7fb;transition:transform .2s,box-shadow .2s}.cur article:hover{transform:translateY(-4px);box-shadow:0 18px 40px rgba(47,107,255,.15)}.cur .ic{width:50px;height:50px;border-radius:16px;display:grid;place-items:center;font-size:26px;margin-bottom:14px}.cur h3{font-size:22px}.cur ul{list-style:none;margin:10px 0 14px;font-size:14px;opacity:.75}.cur li{padding:3px 0}.cur .pr{font-size:26px;font-weight:800}.cur .pr span{font-size:14px;font-weight:500;opacity:.6}.cur .btn{width:100%;justify-content:center;margin-top:12px}
.cuo{background:#fff;border-radius:26px;padding:30px;display:grid;grid-template-columns:1fr 1fr;gap:26px;align-items:center;border:1px solid #dfe7fb}.cuo .seg{display:flex;gap:8px;margin:12px 0}.cuo .seg button{flex:1;border:2px solid #dfe7fb;background:#fff;border-radius:12px;padding:12px;font:600 15px var(--f2);cursor:pointer}.cuo .seg button.on{border-color:#2f6bff;background:#eaf0ff;color:#2f6bff}.cuo .big{font-size:48px;font-weight:800;color:#2f6bff}
details{background:#fff;border:1px solid #dfe7fb;border-radius:14px;padding:16px 20px;margin-bottom:10px}summary{font-weight:700;cursor:pointer}details p{margin-top:8px;opacity:.75}""",
    '<div class="w"><nav><b><i></i>Instituto Horizonte</b><div><a>Cursos</a><a>Cuotas</a><a>Preguntas</a></div></nav><section class="hero"><div><h1>Aprendé un oficio <em>en 6 meses.</em></h1><p>Cursos cortos con práctica real, docentes en actividad y certificado. Cursá presencial u online.</p><a class="btn" href="#cursos">Ver cursos</a><div class="stats"><div><b>4.200</b><span>egresados</span></div><div><b>92 %</b><span>consigue trabajo</span></div></div></div>'
    '<form class="cap" onsubmit="wa(\'Inscripción enviada (demo)\');return false"><h3>Inscribite hoy</h3><input placeholder="Tu nombre" aria-label="Nombre"><input placeholder="Tu WhatsApp" aria-label="WhatsApp"><select aria-label="Curso"><option>Marketing digital</option><option>Programación web</option><option>Diseño gráfico</option></select><button class="btn">Inscribirme</button></form></section></div>'
    '<section class="sec" id="cursos"><div class="w"><h2>Cursos</h2><div class="cur"><article><div class="ic" style="background:#ffe6c7">📣</div><h3>Marketing digital</h3><ul><li>6 meses · 2 clases por semana</li><li>Presencial y online</li></ul><div class="pr">$ 62.000 <span>/ mes</span></div><button class="btn" data-wa="Quiero inscribirme en Marketing digital">Inscribirme</button></article><article><div class="ic" style="background:#dbe7ff">💻</div><h3>Programación web</h3><ul><li>6 meses · 3 clases por semana</li><li>Proyecto final con equipo</li></ul><div class="pr">$ 78.000 <span>/ mes</span></div><button class="btn" data-wa="Quiero inscribirme en Programación web">Inscribirme</button></article><article><div class="ic" style="background:#ffd9ec">🎨</div><h3>Diseño gráfico</h3><ul><li>5 meses · 2 clases por semana</li><li>Portfolio profesional</li></ul><div class="pr">$ 58.000 <span>/ mes</span></div><button class="btn" data-wa="Quiero inscribirme en Diseño gráfico">Inscribirme</button></article></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w"><div class="cuo"><div><h2 style="font-size:30px">Pagá en cuotas con Mercado Pago</h2><div class="seg" id="sg"><button class="on" data-n="1">1 pago</button><button data-n="3">3 cuotas</button><button data-n="6">6 cuotas</button></div><small style="opacity:.65">Valor del curso Marketing digital: $ 372.000</small></div><div><div style="opacity:.7">Pagás por mes</div><div class="big" id="cb">$ 372.000</div></div></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w" style="max-width:760px"><h2>Preguntas frecuentes</h2><details open><summary>¿Los títulos tienen validez?</summary><p>Entregamos certificado del instituto, avalado por cámaras del sector.</p></details><details><summary>¿Puedo cursar online?</summary><p>Sí: las clases se transmiten en vivo y quedan grabadas.</p></details><details><summary>¿Hay bolsa de trabajo?</summary><p>Sí, con empresas que contratan egresados cada trimestre.</p></details></div></section><footer>Instituto Horizonte · Av. Santa Fe 2300</footer>',
    """<script>document.getElementById('sg').onclick=function(e){var b=e.target.closest('button');if(!b)return;this.querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b)});document.getElementById('cb').textContent='$ '+Math.round(372000/+b.dataset.n).toLocaleString('es-AR')}</script>""")

# ───────── Eventos · Quinta El Aromo ─────────
B["eventos"] = page("Quinta El Aromo", "family=Cormorant+Garamond:ital,wght@0,500;0,700;1,500&family=Lato:wght@400;700",
    dict(bg="#f7f2fa", ink="#3b2250", pri="#4a2a5c", **{"pri-ink": "#fff"}, r="2px", f1="'Cormorant Garamond',serif", f2="Lato,sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:center;padding:22px 0;font-size:12.5px;letter-spacing:.18em;text-transform:uppercase}nav b{font:700 28px var(--f1);letter-spacing:0;text-transform:none;font-style:italic}nav div{display:flex;gap:26px}
.hero{text-align:center;padding:30px 0 60px}.hero small{font-size:12.5px;letter-spacing:.3em;text-transform:uppercase;color:#a07d2d}.hero h1{font-size:clamp(54px,9vw,120px);line-height:.92;font-style:italic;font-weight:500;margin:12px 0 22px}.hero p{max-width:46ch;margin:0 auto 28px;font-size:18px;opacity:.78}.hero .orn{font-size:26px;color:#c9a24b;letter-spacing:.6em;margin-bottom:6px}
.vista{height:340px;background:linear-gradient(180deg,rgba(74,42,92,.0),rgba(74,42,92,.5)),linear-gradient(135deg,#e5d4f2,#b79cd1 50%,#7d5aa3);display:grid;place-items:center;color:#fff;font:italic 500 40px var(--f1)}
.paq{display:grid;grid-template-columns:repeat(3,1fr);gap:0;border:1px solid #3b2250}.paq article{padding:34px 28px;border-right:1px solid #3b2250;background:#fff;text-align:center}.paq article:last-child{border-right:0}.paq article.top{background:#4a2a5c;color:#fff}.paq h3{font:italic 500 34px var(--f1)}.paq .n{font-size:13px;letter-spacing:.2em;text-transform:uppercase;opacity:.7;margin:4px 0 14px}.paq ul{list-style:none;font-size:15px;margin-bottom:18px}.paq li{padding:5px 0;border-bottom:1px solid rgba(128,128,128,.25)}
.fecha{display:grid;grid-template-columns:1fr 1fr;gap:34px;background:#fff;padding:36px;border:1px solid #3b2250}.fecha .g7{display:grid;grid-template-columns:repeat(7,1fr);gap:4px;text-align:center}.fecha .g7 b{font-size:12px;opacity:.6;padding:6px 0}.fecha .g7 button{aspect-ratio:1;border:0;background:#f1e9f7;cursor:pointer;font:700 14px var(--f2)}.fecha .g7 button.x{background:#d8c9e3;opacity:.5;cursor:not-allowed}.fecha .g7 button.s{background:#4a2a5c;color:#fff}.fecha .r{align-self:center}.fecha .r b{font:italic 500 32px var(--f1);display:block;margin-bottom:8px}.fecha .leg{display:flex;gap:16px;font-size:12px;margin-top:10px;opacity:.7}
.gal{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.gal i{display:block;aspect-ratio:1}""",
    '<div class="w"><nav><b>El Aromo</b><div><a>Paquetes</a><a>Fechas</a><a>Contacto</a></div></nav><section class="hero"><div class="orn">✦ ✦ ✦</div><small>Quinta de eventos · Pilar</small><h1>El lugar para tu gran día.</h1><p>Cuatro hectáreas de jardín, salón con capacidad para 180 invitados y un equipo que cuida cada detalle.</p><a class="btn" href="#fecha">Consultar fecha</a></section></div><div class="vista">Jardín · Salón · Pérgola</div>'
    '<section class="sec"><div class="w"><h2 style="text-align:center;font-style:italic;font-weight:500">Paquetes</h2><div class="paq"><article><h3>Casamientos</h3><div class="n">hasta 180 invitados</div><ul><li>Salón y jardín</li><li>Catering completo</li><li>Ceremonia en el parque</li></ul><a class="btn o" data-wa="Consulta por paquete Casamientos">Consultar</a></article><article class="top"><h3>Cumpleaños de 15</h3><div class="n">hasta 120 invitados</div><ul><li>Salón y pista</li><li>DJ y luces</li><li>Candy bar</li></ul><a class="btn" style="background:#c9a24b;color:#3b2250" data-wa="Consulta por paquete Cumpleaños de 15">Consultar</a></article><article><h3>Corporativos</h3><div class="n">hasta 250 personas</div><ul><li>Salón y auditorio</li><li>Coffee y almuerzo</li><li>Estacionamiento</li></ul><a class="btn o" data-wa="Consulta por paquete Corporativo">Consultar</a></article></div></div></section>'
    '<section class="sec" id="fecha" style="padding-top:0"><div class="w"><h2>Consultá tu fecha · Noviembre</h2><div class="fecha"><div><div class="g7" id="cl"></div><div class="leg"><span>■ Disponible</span><span style="color:#a98fbd">■ Reservado</span><span style="color:#4a2a5c">■ Tu elección</span></div></div><div class="r"><b id="rt">Elegí un sábado</b><p id="rd" style="opacity:.75;margin-bottom:14px">Los sábados y viernes se reservan con hasta un año de anticipación.</p><button class="btn" id="rb">Consultar esta fecha</button></div></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w"><div class="gal"><i style="background:linear-gradient(135deg,#f0dcf7,#a07dc2)"></i><i style="background:linear-gradient(135deg,#f6e6bd,#c9a24b)"></i><i style="background:linear-gradient(135deg,#d6e6d0,#7aa56a)"></i><i style="background:linear-gradient(135deg,#e5d4f2,#7d5aa3)"></i></div></div></section><footer>Quinta El Aromo · Ruta 8 km 52, Pilar</footer>',
    """<script>(function(){var busy=[2,8,9,15,16,23,29,30],s=null,cl=document.getElementById('cl'),h='';['L','M','M','J','V','S','D'].forEach(function(d){h+='<b>'+d+'</b>'});h+='<span></span><span></span><span></span><span></span><span></span>';for(var d=1;d<=30;d++)h+='<button data-d="'+d+'"'+(busy.indexOf(d)>=0?' class="x"':'')+'>'+d+'</button>';cl.innerHTML=h;
cl.onclick=function(e){var x=e.target.closest('button');if(!x||x.classList.contains('x'))return;s=+x.dataset.d;cl.querySelectorAll('button').forEach(function(y){y.classList.toggle('s',y===x)});document.getElementById('rt').textContent='Sábado '+s+' de noviembre · disponible';document.getElementById('rd').textContent='Podés consultar esta fecha sin compromiso. Te respondemos en el día con presupuesto.'};
document.getElementById('rb').onclick=function(){wa(s?'Consulta de fecha: '+s+' de noviembre':'Primero elegí una fecha disponible')}})()</script>""")

# ───────── Hogar · Frío Total ─────────
B["hogar"] = page("Frío Total", "family=Anton&family=Roboto:wght@400;500;700",
    dict(bg="#ffffff", ink="#0a1a33", pri="#0057d9", **{"pri-ink": "#fff"}, r="8px", f1="Anton,sans-serif", f2="Roboto,sans-serif"),
    """.bar{background:#0057d9;color:#fff;text-align:center;padding:9px;font-weight:700;font-size:14px}nav{display:flex;justify-content:space-between;align-items:center;padding:16px 0}nav b{font:400 30px var(--f1);text-transform:uppercase;letter-spacing:.02em}nav b span{color:#0057d9}nav a.tel{font:700 20px var(--f2);color:#0057d9}
.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:30px;align-items:center;padding:20px 0 50px}.hero h1{font:400 clamp(54px,9vw,110px)/.92 var(--f1);text-transform:uppercase}.hero h1 span{color:#0057d9}.hero p{font-size:19px;margin:18px 0 26px;max-width:36ch}.hero .row{display:flex;gap:12px;flex-wrap:wrap}.btn.big{padding:18px 28px;font-size:18px}.btn.red{background:#ff3b30}
.ice{aspect-ratio:1;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fff,#bfe0ff 55%,#5aa7ff);display:grid;place-items:center;font-size:150px;box-shadow:0 30px 60px rgba(0,87,217,.3)}
.srv{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.srv article{border:3px solid #0a1a33;border-radius:10px;padding:26px;box-shadow:6px 6px 0 #0057d9}.srv h3{font:400 30px var(--f1);text-transform:uppercase}.srv p{opacity:.8;margin-top:6px}
.zonas{display:flex;flex-wrap:wrap;gap:8px}.zonas span{background:#eaf2ff;color:#0057d9;padding:9px 16px;border-radius:99px;font-weight:700}
.form{background:#0a1a33;color:#fff;border-radius:16px;padding:40px;display:grid;grid-template-columns:1fr 1fr;gap:30px}.form h2{color:#fff;text-transform:uppercase}.form form{display:grid;gap:10px}.form input,.form select{padding:14px;border-radius:8px;border:0;font:500 15px var(--f2)}.form .urg{display:flex;gap:10px;align-items:center;font-weight:700}.form .btn{justify-content:center;font-size:17px}
.mat{display:flex;gap:30px;flex-wrap:wrap;font-weight:700}.mat div{display:flex;align-items:center;gap:10px}.mat i{width:38px;height:38px;border-radius:50%;background:#eaf2ff;display:grid;place-items:center;font-style:normal;color:#0057d9}
.rev{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.rev blockquote{background:#f1f6ff;border-radius:10px;padding:22px}.rev cite{display:block;font-style:normal;font-size:13px;opacity:.65;margin-top:8px}""",
    '<div class="bar">⚡ Urgencias: llegamos hoy en 2 horas · Zona Sur y CABA</div><div class="w"><nav><b>Frío <span>Total</span></b><a class="tel" data-wa="Hola, necesito un técnico">11 2345-6789</a></nav><section class="hero"><div><h1>Tu aire <span>funcionando</span> hoy.</h1><p>Instalación, service y reparación de aires acondicionados. Técnicos matriculados, presupuesto en el momento y garantía escrita.</p><div class="row"><a class="btn big" href="#tec">Pedir técnico</a><a class="btn big red" data-wa="Urgencia: mi aire no enfría">Es urgente</a></div></div><div class="ice">❄️</div></section></div>'
    '<section class="sec" style="background:#f1f6ff"><div class="w"><h2 style="font-family:var(--f1);text-transform:uppercase;font-weight:400">Servicios</h2><div class="srv"><article><h3>Instalación</h3><p>Split frío/calor, con base, cañería y puesta en marcha.</p></article><article><h3>Service</h3><p>Limpieza completa, control de gas y filtros.</p></article><article><h3>Reparación</h3><p>Diagnóstico gratis si hacemos la reparación.</p></article></div></div></section>'
    '<section class="sec"><div class="w"><h2 style="font-family:var(--f1);text-transform:uppercase;font-weight:400">Zonas que cubrimos</h2><div class="zonas"><span>Lomas de Zamora</span><span>Banfield</span><span>Lanús</span><span>Avellaneda</span><span>Quilmes</span><span>CABA sur</span></div><div class="mat" style="margin-top:26px"><div><i>✓</i>Matrícula ENARGAS 5821</div><div><i>✓</i>Garantía por escrito</div><div><i>✓</i>Repuestos originales</div></div></div></section>'
    '<div class="w" id="tec"><div class="form"><div><h2>Pedí tu técnico</h2><p style="opacity:.8">Contanos qué le pasa a tu equipo y te llamamos en minutos.</p></div><form onsubmit="wa(\'Pedido de técnico enviado (demo)\');return false"><select aria-label="Servicio"><option>Instalación</option><option>Service</option><option>Reparación</option></select><input placeholder="Tu barrio" aria-label="Barrio"><input placeholder="Tu WhatsApp" aria-label="WhatsApp"><label class="urg"><input type="checkbox" style="width:auto"> Es urgente (hoy)</label><button class="btn big">Pedir técnico</button></form></div></div>'
    '<section class="sec"><div class="w"><div class="rev"><blockquote>“Vinieron en dos horas y quedó funcionando.”<cite>Daniel P. · Lanús · ★★★★★</cite></blockquote><blockquote>“Precio claro desde el primer llamado.”<cite>Silvia M. · Banfield · ★★★★★</cite></blockquote><blockquote>“Muy prolijos con la instalación.”<cite>Ariel G. · Quilmes · ★★★★★</cite></blockquote></div></div></section><footer>Frío Total · Climatización · Lomas de Zamora</footer>')

# ───────── Profesional · Lic. Carolina Díaz ─────────
B["profesional"] = page("Lic. Carolina Díaz", "family=Lora:ital,wght@0,500;0,700;1,500&family=Nunito+Sans:wght@400;600;700",
    dict(bg="#f6f2ea", ink="#2b3a2f", pri="#2f4a3a", **{"pri-ink": "#fff"}, r="999px", f1="Lora,serif", f2="'Nunito Sans',sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:center;padding:20px 0}nav b{font:600 22px var(--f1)}nav div{display:flex;gap:24px;font-size:14px;font-weight:600}
.hero{display:grid;grid-template-columns:1.15fr .85fr;gap:40px;align-items:center;padding:30px 0 56px}.hero h1{font-size:clamp(40px,5.8vw,68px);line-height:1.04;letter-spacing:-.02em;font-weight:500}.hero h1 em{color:#c46a4a}.hero p{font-size:18px;margin:16px 0 26px;max-width:40ch;opacity:.78}.hero .row{display:flex;gap:12px;flex-wrap:wrap}
.pf{aspect-ratio:4/5;border-radius:200px 200px 24px 24px;background:linear-gradient(170deg,#e3d4c1,#c9a98a 60%,#a97f5f);position:relative;overflow:hidden;display:grid;place-items:end center}.pf::before{content:"CD";position:absolute;top:34%;left:50%;transform:translate(-50%,-50%);font:600 84px var(--f1);color:rgba(255,255,255,.85)}.pf span{background:#fff;border-radius:99px;padding:8px 16px;font-weight:700;font-size:13px;margin-bottom:18px}
.mod{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.mod article{background:#fff;border-radius:26px;padding:26px;border:1px solid #e6dccb}.mod .ic{width:46px;height:46px;border-radius:50%;background:#e8efe6;display:grid;place-items:center;font-size:22px;margin-bottom:12px}.mod h3{font:600 22px var(--f1)}.mod p{font-size:15px;opacity:.75;margin:6px 0}.mod b{font-size:15px}
.turn{background:#2f4a3a;color:#fff;border-radius:34px;padding:40px;display:grid;grid-template-columns:1fr 1fr;gap:30px}.turn h2{color:#fff}.turn .seg{display:flex;gap:8px;margin-bottom:12px}.turn .seg button{flex:1;border:1.5px solid rgba(255,255,255,.4);background:transparent;color:#fff;padding:11px;border-radius:99px;font:700 14px var(--f2);cursor:pointer}.turn .seg button.on{background:#fff;color:#2f4a3a}.turn .sl{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:14px}.turn .sl button{border:1.5px solid rgba(255,255,255,.35);background:transparent;color:#fff;padding:11px;border-radius:12px;font:600 14px var(--f2);cursor:pointer}.turn .sl button.on{background:#f3c9b6;color:#2b3a2f;border-color:#f3c9b6}.turn .btn{background:#f3c9b6;color:#2b3a2f;width:100%;justify-content:center}.turn small{display:block;margin-top:10px;opacity:.75}
.blog{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.blog article{background:#fff;border-radius:22px;padding:22px;border:1px solid #e6dccb}.blog small{color:#c46a4a;font-weight:700;letter-spacing:.06em;text-transform:uppercase;font-size:12px}.blog b{display:block;font:600 20px/1.2 var(--f1);margin:8px 0 12px}""",
    '<div class="w"><nav><b>Lic. Carolina Díaz</b><div><a>Modalidades</a><a>Turnos</a><a>Escritos</a></div></nav><section class="hero"><div><h1>Hablemos de <em>lo que te pasa.</em></h1><p>Psicóloga (UBA, M.N. 41.236). Terapia individual, de pareja y orientación vocacional, en consultorio de Palermo o por videollamada.</p><div class="row"><a class="btn" href="#turnos">Pedir primera sesión</a><a class="btn o" data-wa="Hola Carolina, quiero hacerte una consulta">Escribirme</a></div></div><div class="pf"><span>Primera consulta de 20 min sin cargo</span></div></section></div>'
    '<section class="sec" style="background:#fff"><div class="w"><h2>Modalidades</h2><div class="mod"><article><div class="ic">🌱</div><h3>Terapia individual</h3><p>Ansiedad, duelos, vínculos y momentos de cambio.</p><b>Sesión de 50 min · $ 38.000</b></article><article><div class="ic">🤝</div><h3>Terapia de pareja</h3><p>Comunicación, acuerdos y crisis de convivencia.</p><b>Sesión de 60 min · $ 52.000</b></article><article><div class="ic">🧭</div><h3>Orientación vocacional</h3><p>Para jóvenes y adultos que quieren redefinir su camino.</p><b>Ciclo de 4 encuentros · $ 120.000</b></article></div></div></section>'
    '<section class="sec" id="turnos"><div class="w"><div class="turn"><div><h2>Pedí tu primera sesión</h2><p style="opacity:.85">Elegí cómo preferís atenderte y un horario. Te confirmo por WhatsApp.</p></div><div><div class="seg" id="sm"><button class="on">Presencial</button><button>Videollamada</button></div><div class="sl" id="ss"><button>Lun 10:00</button><button>Mar 18:00</button><button>Mié 16:00</button><button>Jue 11:00</button><button>Vie 15:00</button><button>Sáb 10:00</button></div><button class="btn" id="tb">Pedir turno</button><small id="tm">Elegí modalidad y horario</small></div></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w"><h2>Escritos</h2><div class="blog"><article><small>Ansiedad</small><b>Cómo reconocer una crisis de ansiedad y qué hacer</b><a>Leer →</a></article><article><small>Pareja</small><b>Discutir bien: cinco acuerdos que ayudan</b><a>Leer →</a></article><article><small>Vocación</small><b>¿Es tarde para cambiar de carrera?</b><a>Leer →</a></article></div></div></section><footer>Lic. Carolina Díaz · Psicóloga · Palermo y online</footer>',
    """<script>(function(){var m='Presencial',h=null;document.getElementById('sm').onclick=function(e){var b=e.target.closest('button');if(!b)return;m=b.textContent;this.querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b)});u()};
document.getElementById('ss').onclick=function(e){var b=e.target.closest('button');if(!b)return;h=b.textContent;this.querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b)});u()};function u(){document.getElementById('tm').textContent=h?m+' · '+h:'Elegí modalidad y horario'}
document.getElementById('tb').onclick=function(){wa(h?'Turno solicitado: '+m+' · '+h:'Primero elegí un horario')}})()</script>""")
