#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Núcleo de patrones de landing y tipos de web (borrador de Claude, sin validar). El "cómo" y el "aporta" originales se conservan."""
from lab_nucleo_suma import S

# id: (qué es, qué problema resuelve, cuándo sí, cuándo no)
LP = {
"hero-features-cta": ("La estructura clásica: un hero con titular e imagen, la propuesta de valor, tres a cinco funcionalidades y un llamado a la acción.", "Un producto con varias características necesita explicarse con orden antes de pedir una acción.", "Productos y servicios con varias funciones para explicar, como software, apps y servicios.", "Cuando solo hay una cosa que decir: sobran secciones."),
"hero-testimonials-cta": ("Un hero, el planteo del problema, la solución y testimonios que preceden al llamado a la acción.", "La gente duda de lo que dice el propio negocio: necesita ver que otros ya lo probaron.", "Servicios y productos donde la confianza decide la compra y ya hay clientes que opinen.", "Si todavía no tenés testimonios reales: no los inventes, elegí otro patrón."),
"product-demo-features": ("Un hero, una demo o mockup del producto al centro y el detalle de las funcionalidades por sección.", "Un producto digital no se entiende solo con texto: hay que verlo funcionando.", "Software, apps y herramientas con una interfaz que se pueda mostrar.", "Servicios o productos físicos sin interfaz para mostrar."),
"minimal-single-column": ("Una columna con titular, descripción corta, hasta tres beneficios y un solo llamado a la acción.", "Cuanto más hay en la página, menos gente llega a la acción.", "Ofertas simples, campañas y servicios donde alcanza con un mensaje.", "Productos con mucho para explicar: queda corta."),
"funnel-3-step-conversion": ("Una página que lleva a la persona por tres pasos: problema, solución y acción, mostrando solo lo esencial en cada uno.", "Mostrar todo junto abruma; ir paso a paso mantiene la atención.", "Ofertas que necesitan convencer de a poco, como servicios de consultoría o cursos.", "Si la persona ya sabe lo que quiere: un embudo la demora."),
"comparison-table-cta": ("Un hero, el problema, una tabla que compara tu producto con la competencia y el llamado a la acción.", "Quien está comparando alternativas necesita ver las diferencias lado a lado.", "Mercados con competidores conocidos y ventajas concretas para mostrar.", "Si no tenés ventajas verificables: una tabla que no favorece es peor que no tenerla."),
"lead-magnet-form": ("Un titular con el beneficio, una vista previa del material gratuito y un formulario corto.", "Pedir datos sin dar nada a cambio hace que casi nadie los deje.", "Para juntar contactos ofreciendo algo útil: una guía, una checklist o una plantilla.", "Si no tenés un material que valga la pena regalar."),
"pricing-page-cta": ("Un hero de precios, tarjetas comparativas de planes, una tabla de funcionalidades y preguntas frecuentes.", "Los precios poco claros frenan la compra: la persona quiere saber qué paga y qué recibe.", "Productos con planes o paquetes definidos.", "Servicios a medida donde el precio depende de cada caso."),
"video-first-hero": ("Un hero con un video de fondo, las funcionalidades clave encima y un llamado a la acción.", "Una imagen fija no transmite el movimiento ni el ambiente de un producto.", "Marcas con buen material audiovisual para mostrar: turismo, gastronomía, eventos.", "Si el video pesa mucho o no se puede entender sin sonido en celular."),
"scroll-triggered-storytelling": ("Una historia en capítulos (problema, recorrido y solución) que se revela al hacer scroll, con el llamado a la acción en el momento culminante.", "Una página que lista beneficios no emociona; una historia sí.", "Marcas con una historia para contar y lanzamientos de producto.", "Públicos que van directo a lo concreto, o sitios que dependen de SEO y velocidad."),
"ai-personalization-landing": ("Una landing que cambia el hero, las funcionalidades y los testimonios según quién la visita.", "Un mensaje único no le habla igual a todos los públicos.", "Cuando hay públicos muy distintos y datos para segmentarlos.", "Sin analítica ni volumen de visitas: la personalización no tiene con qué trabajar."),
"waitlist-coming-soon": ("Una página de cuenta regresiva con una vista previa del producto y un formulario para dejar el email.", "Antes de lanzar, hay que juntar interesados para tener a quién avisar.", "Lanzamientos próximos y validación de una idea.", "Si ya tenés producto a la venta: es una barrera."),
"comparison-table-focus": ("Una landing cuya pieza central es la matriz comparativa entre tu producto y las alternativas.", "Cuando la decisión es racional, la comparación es el argumento principal.", "Productos técnicos en un mercado con alternativas conocidas.", "Productos nuevos sin competencia directa o sin datos objetivos."),
"pricing-focused-landing": ("Una landing donde los precios, en tres niveles, son lo central, con comparación y preguntas frecuentes.", "Cuando la decisión pasa por el precio, esconderlo genera desconfianza.", "SaaS y servicios con planes claros.", "Productos a medida con precio a consultar."),
"app-store-style-landing": ("Una landing con el formato de una tienda de aplicaciones: mockup, capturas, funciones con íconos, reseñas y botones de descarga.", "Quien va a instalar una app quiere ver capturas y calificaciones antes.", "Aplicaciones móviles listas para descargar.", "Productos que no son apps."),
"faq-documentation-landing": ("Una página con buscador, categorías populares y preguntas frecuentes, y un camino a soporte.", "Muchas consultas se repiten y saturan la atención al cliente.", "Productos con muchas dudas frecuentes y soporte que se quiere aliviar.", "Si el sitio es chico y las dudas son pocas: alcanza con una sección de preguntas."),
"immersive-interactive-experience": ("Una experiencia a pantalla completa con un elemento interactivo que guía un recorrido por el producto.", "Algunos productos se entienden mejor tocándolos que leyendo.", "Lanzamientos y marcas que buscan sorprender.", "Conexiones lentas, celulares básicos o públicos que buscan rapidez."),
"event-conference-landing": ("Un hero con fecha, lugar y cuenta regresiva, la grilla de oradores, la agenda, los sponsors y la inscripción.", "Un evento necesita responder rápido quién, cuándo, dónde y cuánto cuesta.", "Congresos, jornadas, talleres y eventos con inscripción.", "Cuando no hay fecha ni oradores definidos."),
"product-review-ratings-focused": ("Una landing que muestra la calificación promedio, el desglose y las reseñas individuales antes de la compra.", "Los usuarios confían más en otras personas que en el vendedor.", "Productos con muchas reseñas reales y buen puntaje.", "Si las reseñas son pocas o malas, o si no podés verificarlas."),
"community-forum-landing": ("Una landing que muestra una comunidad activa: temas populares, miembros destacados y un llamado a sumarse.", "Nadie se une a una comunidad vacía: hay que mostrar que está viva.", "Comunidades, foros y grupos con actividad real.", "Comunidades nuevas sin miembros."),
"before-after-transformation": ("Una landing que muestra el estado antes, el resultado después y cómo se llega, con métricas concretas.", "Prometer un resultado no alcanza: hay que mostrarlo.", "Servicios con resultado visible: estética, obras, rediseños, ordenamiento.", "Si no podés mostrar resultados reales: no los simules."),
"marketplace-directory": ("Una landing centrada en el buscador, con categorías, publicaciones destacadas y mensajes de seguridad.", "En un marketplace, el valor está en encontrar algo rápido.", "Plataformas que conectan oferta y demanda.", "Sitios con pocas publicaciones: la búsqueda no luce."),
"newsletter-content-first": ("Una landing con un formulario de un solo campo, ediciones anteriores y la cantidad de lectores.", "Para convencer de suscribirse hay que mostrar qué se va a recibir.", "Newsletters y boletines con contenido de calidad.", "Si todavía no hay ediciones publicadas para mostrar."),
"webinar-registration": ("Una landing con el tema, el horario, el formulario, el orador y un incentivo para inscribirse ya.", "La gente se inscribe si entiende qué aprende, quién lo da y cuándo.", "Webinars y clases en vivo.", "Contenidos grabados sin fecha."),
"enterprise-gateway": ("Un portal para empresas grandes con soluciones por industria y por rol, logos de clientes y contacto a ventas.", "Una empresa grande tiene muchos públicos, y cada uno busca algo distinto.", "Compañías con varias líneas de producto y públicos distintos.", "Pymes con una oferta simple."),
"portfolio-grid": ("Una grilla de proyectos con filtro por categoría, una presentación personal y el contacto.", "Quien contrata quiere ver trabajos antes de leer promesas.", "Creativos, fotógrafos, diseñadores y estudios.", "Cuando los trabajos no se pueden mostrar o no son visuales."),
"horizontal-scroll-journey": ("Un recorrido con scroll horizontal en el centro, con una introducción y un cierre verticales.", "Algunos relatos funcionan mejor como un camino lateral que como una lista.", "Historias de producto, líneas de tiempo y recorridos.", "Celulares y sitios que priorizan accesibilidad."),
"bento-grid-showcase": ("Una vidriera de funcionalidades en una grilla bento, con tarjetas de distinto tamaño y especificaciones.", "Muchas funciones en una lista se leen como ruido.", "Productos con varias funciones de distinta importancia.", "Cuando hay poco que mostrar, o mucho texto por función."),
"interactive-3d-configurator": ("Un configurador 3D donde la persona arma el producto, ve el precio y compra.", "En productos personalizables, la duda es cómo va a quedar.", "Muebles, calzado, autos o joyería con opciones.", "Productos simples o sitios que tienen que cargar rápido en cualquier celular."),
"ai-driven-dynamic-landing": ("Una landing con un campo de entrada que genera en el momento una vista previa del resultado.", "Explicar lo que hace una herramienta de IA convence menos que verla funcionar.", "Productos de IA que se pueden mostrar con una prueba rápida.", "Si la prueba es lenta o costosa."),
"feature-rich-showcase": ("Una vidriera de cuatro a seis funcionalidades en tarjetas, con casos de uso, prueba social y un llamado a la acción.", "Un producto con muchas funciones no se explica con un solo párrafo.", None, None),
"hero-centric-design": ("Una landing que apuesta casi todo al hero: un titular fuerte con un visual a todo el ancho y un solo llamado a la acción.", "Si la primera pantalla no convence, la persona no sigue.", None, None),
"trust-authority-conversion": ("Un hero con la misión o la credibilidad, pruebas (logos, certificaciones y cifras) y un camino claro a la acción.", "Cuando hay dinero o datos en juego, sin confianza no hay conversión.", "Salud, finanzas, servicios legales y productos premium.", "Productos casuales o de bajo riesgo, donde tanta prueba sobra."),
"real-time-operations-landing": ("Una landing con una vista en vivo del producto, métricas clave, cómo funciona y un acceso a la prueba.", "Los productos de operaciones o seguridad se entienden viendo los datos reales.", "Productos de operaciones, monitoreo o IoT que puedan mostrar un estado en vivo.", "Productos sin datos que mostrar."),
}
SUMA_LP = {("landing", k): S(que=q, problema=p, si=si, no=no) for k, (q, p, si, no) in LP.items()}

# Tipos de web (arquetipos): ya traen problema, cuándo sí y aporta; se suma "qué es" y, donde faltaba, "cuándo no".
SOL = {
"landing": ("Una sola página enfocada en una acción: registrarse, comprar, pedir una demo o contactar.", None),
"institucional": ("La presencia oficial de una empresa u organización en internet: quiénes son, qué hacen y cómo contactarlos.", None),
"portfolio": ("Una web personal que muestra quién sos, qué hiciste y cómo contactarte.", "Cuando no tenés trabajos para mostrar todavía, o la información sensible no se puede publicar."),
"ecommerce": ("Una tienda online completa: catálogo, carrito, checkout y cuentas de clientes.", None),
"catalogo": ("Un catálogo de productos con precios o fotos, sin carrito: el cliente consulta o pide por WhatsApp.", "Cuando necesitás cobrar online o manejar stock en tiempo real: ahí corresponde una tienda."),
"blog": ("Un sitio de artículos organizados por categorías, pensado para atraer lectores y posicionar en buscadores.", "Si no vas a publicar con regularidad: un blog abandonado resta credibilidad."),
"saas": ("Una aplicación web con cuentas de usuarios que se ofrece como servicio, normalmente por suscripción.", "Cuando el problema se resuelve con una planilla o una landing: construir un SaaS es mucho trabajo."),
"dashboard": ("Un panel que reúne métricas y herramientas de gestión en una sola pantalla.", "Si hay pocos datos o los consulta una persona una vez por semana: una planilla alcanza."),
"reservas": ("Un sistema para que los clientes reserven turnos o lugares online según la disponibilidad real.", "Si el negocio atiende pocas veces por día o por orden de llegada: no hay disponibilidad que gestionar."),
"marketplace": ("Una plataforma que junta vendedores y compradores de un nicho.", "Sin una masa mínima de oferta y demanda: un marketplace vacío no atrae a nadie."),
"interna": ("Una aplicación para uso del equipo de una empresa, no para el público.", "Cuando el proceso cambia todo el tiempo o hay una herramienta del mercado que ya lo cubre."),
"docs": ("Un sitio de manuales, guías y preguntas frecuentes ordenado y con buscador.", "Si el contenido es poco y rara vez se consulta."),
"pwa": ("Una aplicación web que se puede instalar en el celular y funciona sin conexión, sin pasar por las tiendas.", "Si necesitás funciones del sistema que el navegador no ofrece, o estar presente en las tiendas de apps."),
}
SUMA_SOL = {("soluciones", k): S(que=q, no=n) for k, (q, n) in SOL.items()}
