#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Segundo grupo de ejemplos de negocios (ver lab_demos_negocios.py)."""
from lab_demos_negocios import page, B

# ───────── Estética · Estudio Lumière ─────────
B["estetica"] = page("Estudio Lumière", "family=Cormorant+Garamond:ital,wght@0,500;0,700;1,500;1,700&family=Jost:wght@400;500;600",
    dict(bg="#f3eefa", ink="#2a1f3d", pri="#7d5cb8", **{"pri-ink": "#fff"}, r="999px", f1="'Cormorant Garamond',serif", f2="Jost,sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:center;padding:22px 0;font-size:13px;letter-spacing:.14em;text-transform:uppercase}nav b{font:700 30px var(--f1);letter-spacing:0;text-transform:none;font-style:italic}nav div{display:flex;gap:26px}
.hero{display:grid;grid-template-columns:1fr 1fr;gap:40px;align-items:center;padding:30px 0 60px}.hero h1{font-size:clamp(48px,7vw,92px);line-height:.95;font-style:italic;font-weight:500;letter-spacing:-.02em}.hero p{font-size:18px;margin:18px 0 28px;opacity:.75;max-width:38ch}
.arch{height:480px;border-radius:240px 240px 0 0;background:linear-gradient(170deg,#e4d4f5,#b9a0e0 55%,#8f6fc7);position:relative;overflow:hidden}.arch::after{content:"";position:absolute;left:50%;bottom:-40px;width:230px;height:330px;transform:translateX(-50%);background:radial-gradient(circle at 50% 22%,#f6e9e2 0 16%,transparent 17%),linear-gradient(#3b2a5a,#3b2a5a);border-radius:115px 115px 0 0;opacity:.9}
.price{display:flex;align-items:baseline;gap:10px;padding:16px 0;border-bottom:1px solid #d6c9ea;cursor:pointer}.price b{font:600 26px var(--f1)}.price i{flex:1;border-bottom:2px dotted #b9a6d9;transform:translateY(-4px)}.price span{font:600 18px var(--f2)}.price small{display:block;font-size:13px;opacity:.65;font-weight:400}.price:hover b{font-style:italic}.price.on b{color:#7d5cb8}
.gal{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.gal i{aspect-ratio:3/4;border-radius:120px 120px 14px 14px;display:block}.gal i:nth-child(2n){border-radius:14px 14px 120px 120px}
.book{background:#2a1f3d;color:#fff;border-radius:34px;padding:46px;display:grid;grid-template-columns:1fr 1fr;gap:34px}.book h2{color:#fff}.book .row{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:14px}.book .row button{border:1px solid rgba(255,255,255,.35);background:transparent;color:#fff;padding:9px 16px;border-radius:99px;font:500 14px var(--f2);cursor:pointer}.book .row button.on{background:#e6d6ff;color:#2a1f3d;border-color:#e6d6ff}.book .btn{background:#e6d6ff;color:#2a1f3d}.book small{opacity:.7;display:block;margin-top:12px}
.rev{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.rev blockquote{background:#fff;border-radius:22px;padding:24px;font:italic 500 21px/1.3 var(--f1)}.rev cite{display:block;font:500 13px var(--f2);font-style:normal;opacity:.6;margin-top:10px}""",
    '<div class="w"><nav><b>Lumière</b><div><a>Servicios</a><a>Galería</a><a>Turnos</a></div></nav><section class="hero"><div><h1>Tu mejor versión empieza acá.</h1><p>Peluquería y estética en Recoleta. Color, corte y tratamientos con productos profesionales y turnos puntuales.</p><a class="btn" href="#turnos">Reservar turno</a></div><div class="arch"></div></section></div>'
    '<section class="sec" style="background:#fff"><div class="w" style="max-width:760px"><h2>Servicios</h2><div id="sv"></div></div></section>'
    '<section class="sec"><div class="w"><h2>Nuestro trabajo</h2><div class="gal"><i style="background:linear-gradient(160deg,#f3d6c8,#c98a6c)"></i><i style="background:linear-gradient(160deg,#e6d6ff,#8f6fc7)"></i><i style="background:linear-gradient(160deg,#d9e6d0,#7aa56a)"></i><i style="background:linear-gradient(160deg,#f6e2a8,#d49a2f)"></i></div></div></section>'
    '<section class="sec" id="turnos" style="padding-top:0"><div class="w"><div class="book"><div><h2>Reservá tu turno</h2><p style="opacity:.8">Elegí el servicio y el horario. Dejás una seña con Mercado Pago y listo.</p></div><div><div class="row" id="bs"></div><div class="row" id="bd"></div><button class="btn" id="bk">Reservar con seña de $ 5.000</button><small id="bm">Elegí un servicio y un horario</small></div></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w"><h2>Lo que dicen</h2><div class="rev"><blockquote>“El mejor color que me hicieron.”<cite>Valeria R. · ★★★★★</cite></blockquote><blockquote>“Puntuales y muy delicados.”<cite>Camila T. · ★★★★★</cite></blockquote><blockquote>“La keratina duró meses.”<cite>Julieta M. · ★★★★★</cite></blockquote></div></div></section><footer>Estudio Lumière · Av. Callao 1190, Recoleta</footer>',
    """<script>(function(){var S=[['Corte y brushing','45 min',18500],['Color completo','2 h 30',54000],['Keratina','3 h',68000]],H=['Mar 10:00','Mié 15:30','Jue 11:00','Sáb 12:30'],s=null,h=null;
document.getElementById('sv').innerHTML=S.map(function(x,i){return'<div class="price" data-i="'+i+'"><div><b>'+x[0]+'</b><small>'+x[1]+'</small></div><i></i><span>$ '+x[2].toLocaleString('es-AR')+'</span></div>'}).join('');
document.getElementById('bs').innerHTML=S.map(function(x,i){return'<button data-s="'+i+'">'+x[0]+'</button>'}).join('');document.getElementById('bd').innerHTML=H.map(function(x){return'<button data-h="'+x+'">'+x+'</button>'}).join('');
function u(){document.getElementById('bm').textContent=s!==null&&h?S[s][0]+' · '+h:'Elegí un servicio y un horario';document.querySelectorAll('.price').forEach(function(p){p.classList.toggle('on',+p.dataset.i===s)})}
document.querySelector('.book').onclick=function(e){var b=e.target.closest('button[data-s],button[data-h]');if(!b)return;var g=b.parentNode;g.querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b)});if(b.dataset.s!==undefined)s=+b.dataset.s;else h=b.dataset.h;u()};
document.getElementById('sv').onclick=function(e){var p=e.target.closest('.price');if(!p)return;s=+p.dataset.i;document.querySelectorAll('#bs button').forEach(function(x){x.classList.toggle('on',+x.dataset.s===s)});u()};
document.getElementById('bk').onclick=function(){wa(s!==null&&h?'Reserva '+S[s][0]+' · '+h+' (seña por Mercado Pago, simulada)':'Primero elegí servicio y horario')}})()</script>""")

# ───────── Veterinaria · Patitas ─────────
B["veterinaria"] = page("Veterinaria Patitas", "family=Baloo+2:wght@500;700;800&family=Nunito:wght@400;600;700",
    dict(bg="#f2f8ec", ink="#1f3a29", pri="#2f7d4f", **{"pri-ink": "#fff"}, r="18px", f1="'Baloo 2',sans-serif", f2="Nunito,sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:center;padding:16px 0}nav b{font:800 26px var(--f1);display:flex;align-items:center;gap:8px}nav div{display:flex;gap:22px;font-weight:700;font-size:14px}
.urg{background:#ffe3e0;color:#a3261d;border-radius:99px;padding:8px 16px;font-weight:800;font-size:14px;display:inline-flex;gap:8px;align-items:center}.urg i{width:9px;height:9px;border-radius:50%;background:#e03a2e;animation:pl 1.4s infinite}@keyframes pl{50%{opacity:.3}}
.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:30px;align-items:center;padding:26px 0 50px}.hero h1{font-size:clamp(44px,6.5vw,76px);line-height:.98;letter-spacing:-.02em;margin:14px 0}.hero p{font-size:19px;max-width:38ch;margin-bottom:24px;opacity:.8}.hero .row{display:flex;gap:12px;flex-wrap:wrap}.btn.red{background:#e03a2e}
.pets{position:relative;height:340px}.pets i{position:absolute;border-radius:50%;display:grid;place-items:center;font-style:normal}.pets .a{width:260px;height:260px;background:#bfe3c8;left:10%;top:10%;font-size:120px}.pets .b{width:170px;height:170px;background:#ffd9a8;right:6%;bottom:2%;font-size:84px}.pets .c{width:90px;height:90px;background:#fff;left:2%;bottom:8%;font-size:42px;box-shadow:0 8px 20px rgba(0,0,0,.1)}
.srv{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.srv article{background:#fff;border-radius:24px;padding:26px;box-shadow:0 8px 24px rgba(47,125,79,.1)}.srv i{font-size:34px;font-style:normal}.srv h3{font-size:22px;margin:6px 0}.srv p{font-size:15px;opacity:.75}
.turno{background:#2f7d4f;color:#fff;border-radius:34px;padding:40px;display:grid;grid-template-columns:1fr 1fr;gap:30px}.turno h2{color:#fff}.turno .seg{display:flex;gap:8px;margin-bottom:12px}.turno .seg button{flex:1;border:2px solid rgba(255,255,255,.4);background:transparent;color:#fff;padding:12px;border-radius:14px;font:700 15px var(--f2);cursor:pointer}.turno .seg button.on{background:#fff;color:#2f7d4f;border-color:#fff}.turno input,.turno select{width:100%;padding:13px;border-radius:12px;border:0;margin-bottom:10px;font:600 15px var(--f2)}.turno .btn{background:#ffd9a8;color:#1f3a29;width:100%;justify-content:center}
.shop{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.prod{background:#fff;border-radius:22px;padding:18px;text-align:center}.prod i{display:block;height:110px;border-radius:16px;margin-bottom:10px;font-size:50px;line-height:110px;font-style:normal}.prod b{display:block}.prod span{opacity:.7;font-size:14px}.prod .btn{margin-top:10px;padding:9px 16px;font-size:14px}.cnt{position:fixed;right:80px;bottom:22px;background:#1f3a29;color:#fff;border-radius:99px;padding:10px 16px;font-weight:800;font-size:14px;z-index:50}""",
    '<div class="w"><nav><b>🐾 Patitas</b><div><a>Servicios</a><a>Turnos</a><a>Tienda</a><a>Cómo llegar</a></div></nav><section class="hero"><div><span class="urg"><i></i>Guardia de urgencias 24 h</span><h1>Cuidamos a los que más querés.</h1><p>Veterinaria con consultorio, vacunatorio y pet shop en Villa Urquiza. Atención cálida, con turno o sin él.</p><div class="row"><a class="btn" href="#turno">Sacar turno</a><a class="btn red" data-wa="¡Urgencia! Mi mascota necesita atención ahora">Es una urgencia</a></div></div><div class="pets"><i class="a">🐶</i><i class="b">🐱</i><i class="c">💉</i></div></section></div>'
    '<section class="sec" style="background:#fff"><div class="w"><h2>Servicios</h2><div class="srv"><article><i>🩺</i><h3>Consulta clínica</h3><p>Control general, diagnóstico y seguimiento.</p></article><article><i>💉</i><h3>Plan de vacunas</h3><p>Calendario completo para cachorros y adultos.</p></article><article><i>✂️</i><h3>Peluquería</h3><p>Baño, corte y cuidado de uñas.</p></article></div></div></section>'
    '<section class="sec" id="turno"><div class="w"><div class="turno"><div><h2>Pedí tu turno</h2><p style="opacity:.85">Contanos de tu mascota y te confirmamos por WhatsApp.</p></div><div><div class="seg" id="sg"><button class="on">🐶 Perro</button><button>🐱 Gato</button><button>🐰 Otro</button></div><input placeholder="Nombre de tu mascota" id="nm" aria-label="Nombre de tu mascota"><select id="mt" aria-label="Motivo"><option>Consulta general</option><option>Vacunación</option><option>Peluquería</option></select><button class="btn" id="tg">Pedir turno</button></div></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w"><h2>Pet shop</h2><div class="shop" id="sh"></div></div></section><div class="cnt" id="cn">🛒 0</div><footer>Veterinaria Patitas · Triunvirato 4800 · Matrícula M.P. 4521</footer>',
    """<script>(function(){var P=[['Alimento premium 15 kg','$ 68.500','🥣','#ffe9c7'],['Antipulgas mensual','$ 14.900','💊','#d6f0e0'],['Cama ortopédica','$ 42.000','🛏️','#e6e0f5']],n=0;
document.getElementById('sh').innerHTML=P.map(function(p){return'<div class="prod"><i style="background:'+p[3]+'">'+p[2]+'</i><b>'+p[0]+'</b><span>'+p[1]+'</span><br><button class="btn" data-a>Agregar</button></div>'}).join('');
document.getElementById('sh').onclick=function(e){if(e.target.closest('[data-a]')){n++;document.getElementById('cn').textContent='🛒 '+n}};
document.getElementById('sg').onclick=function(e){var b=e.target.closest('button');if(b)this.querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b)})};
document.getElementById('tg').onclick=function(){var a=document.querySelector('#sg .on').textContent.trim(),m=document.getElementById('nm').value||'mi mascota';wa('Turno para '+m+' ('+a+') · '+document.getElementById('mt').value)}})()</script>""")

# ───────── Tienda · Casa Bosque (marca que vende en Mercado Libre) ─────────
B["tienda"] = page("Casa Bosque", "family=Space+Grotesk:wght@400;500;700&family=Inter:wght@400;500;600",
    dict(bg="#f1f1ee", ink="#111111", pri="#111111", **{"pri-ink": "#fff"}, r="2px", f1="'Space Grotesk',sans-serif", f2="Inter,sans-serif"),
    """.top{background:#111;color:#fff;text-align:center;font-size:12.5px;padding:8px;letter-spacing:.04em}nav{display:flex;justify-content:space-between;align-items:center;padding:20px 0}nav b{font:700 26px var(--f1);letter-spacing:-.04em}nav div{display:flex;gap:26px;font-size:14px}nav .cart{font-weight:700}
.hero{display:grid;grid-template-columns:1fr 1fr;gap:0;border:1px solid #111;margin-bottom:10px}.hero .tx{padding:50px 40px;display:flex;flex-direction:column;justify-content:center;background:#fff}.hero h1{font-size:clamp(40px,5.5vw,70px);line-height:.98;letter-spacing:-.045em}.hero p{margin:16px 0 24px;opacity:.7;max-width:34ch}.hero .im{background:linear-gradient(135deg,#d8d6cc,#a9a89c);display:grid;place-items:center;font-size:130px;min-height:340px}
.ml{display:inline-flex;align-items:center;gap:8px;background:#ffe600;color:#2d3277;font:700 12px var(--f2);padding:5px 10px;border-radius:99px;margin-bottom:16px;width:fit-content}
.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.p{background:#fff;border:1px solid #d9d8d0;padding:14px}.p .im{aspect-ratio:1;display:grid;place-items:center;font-size:64px;margin-bottom:12px}.p b{display:block;font:500 16px var(--f1)}.p .pr{font:700 20px var(--f1);margin:6px 0 2px}.p small{display:block;color:#0a7a3d;font-weight:600;font-size:12.5px}.p .btn{width:100%;justify-content:center;margin-top:12px;padding:11px}.p .tag{font-size:11px;font-weight:700;background:#111;color:#fff;padding:3px 8px;letter-spacing:.06em;text-transform:uppercase}
.faq{max-width:760px;margin:0 auto}.faq details{border-bottom:1px solid #111;padding:16px 0}.faq summary{font:700 18px var(--f1);cursor:pointer}.faq p{margin-top:8px;opacity:.75}
.rev{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.rev blockquote{background:#fff;border:1px solid #d9d8d0;padding:22px;font-size:15px}.rev cite{display:block;font-style:normal;font-size:12.5px;opacity:.6;margin-top:10px}""",
    '<div class="top">Envíos a todo el país · 6 cuotas sin interés con Mercado Pago · 10 % off por transferencia</div><div class="w"><nav><b>casa bosque</b><div><a>Cocina</a><a>Mesa</a><a>Ofertas</a><span class="cart" id="cc">Carrito (0)</span></div></nav>'
    '<section class="hero"><div class="tx"><span class="ml">★ También lo encontrás en Mercado Libre</span><h1>Utensilios que duran toda la vida.</h1><p>Diseñados en acero y madera, con garantía de 5 años. Comprá directo y ahorrás la comisión.</p><a class="btn" style="width:fit-content" href="#vendidos">Ver productos</a></div><div class="im">🔪</div></section></div>'
    '<section class="sec" id="vendidos"><div class="w"><h2>Más vendidos</h2><div class="grid" id="gp"></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w"><h2>Lo que dicen</h2><div class="rev"><blockquote>“La mandolina es una maravilla, corta parejo.”<cite>Reseña verificada · 5 ★</cite></blockquote><blockquote>“Llegó en 48 h y bien embalado.”<cite>Reseña verificada · 5 ★</cite></blockquote><blockquote>“Los cuchillos mantienen el filo.”<cite>Reseña verificada · 5 ★</cite></blockquote></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="faq"><h2>Preguntas frecuentes</h2><details open><summary>¿Cuánto tarda el envío?</summary><p>De 2 a 5 días hábiles, con seguimiento.</p></details><details><summary>¿Tienen garantía?</summary><p>5 años contra defectos de fabricación.</p></details><details><summary>¿Por qué comprar acá y no en Mercado Libre?</summary><p>Mismo producto, mejor precio y combos que allá no ofrecemos.</p></details></div></section><footer>Casa Bosque · Venta online · Atención de lunes a viernes</footer>',
    """<script>(function(){var P=[['Mandolina V5','$ 38.900','🥕','#e4e1d4','Más vendido'],['Set de cuchillos','$ 64.500','🔪','#d9dcd2','Nuevo'],['Rallador multiuso','$ 12.800','🧀','#e8e2d0',''],['Tabla de bambú','$ 21.300','🪵','#e2dccb','']],n=0;
document.getElementById('gp').innerHTML=P.map(function(p){return'<article class="p"><div class="im" style="background:'+p[3]+'">'+p[2]+'</div>'+(p[4]?'<span class="tag">'+p[4]+'</span>':'')+'<b>'+p[0]+'</b><div class="pr">'+p[1]+'</div><small>6 cuotas sin interés</small><button class="btn" data-a>Agregar al carrito</button></article>'}).join('');
document.getElementById('gp').onclick=function(e){if(e.target.closest('[data-a]')){n++;document.getElementById('cc').textContent='Carrito ('+n+')'}}})()</script>""")

# ───────── Comercio · Almacén Doña Rosa ─────────
B["comercio"] = page("Almacén Doña Rosa", "family=Fredoka:wght@400;500;600;700&family=Nunito:wght@400;600;700",
    dict(bg="#fff6dc", ink="#3b2a12", pri="#ef8300", **{"pri-ink": "#fff"}, r="16px", f1="Fredoka,sans-serif", f2="Nunito,sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:center;padding:16px 0}nav b{font:700 28px var(--f1);color:#ef8300}nav span{font-weight:700;font-size:14px}
.hero{display:grid;grid-template-columns:1.2fr .8fr;gap:24px;align-items:center;padding:20px 0 40px}.hero h1{font-size:clamp(44px,6.5vw,76px);line-height:.98;letter-spacing:-.02em}.hero h1 em{font-style:normal;color:#ef8300}.hero p{font-size:19px;margin:16px 0 24px;opacity:.8}.sign{background:#fff;border:4px solid #3b2a12;border-radius:20px;padding:24px;text-align:center;transform:rotate(3deg);box-shadow:8px 8px 0 #ef8300}.sign b{display:block;font:700 30px var(--f1)}.sign small{font-size:15px}
.promos{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:34px}.promos div{background:#ef8300;color:#fff;border-radius:18px;padding:16px;font:600 17px var(--f1);text-align:center}.promos div:nth-child(2){background:#3b2a12}.promos div:nth-child(3){background:#2f9e44}
.cat{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.it{background:#fff;border-radius:20px;padding:16px;display:flex;gap:14px;align-items:center;box-shadow:0 6px 16px rgba(59,42,18,.08)}.it i{width:62px;height:62px;border-radius:16px;display:grid;place-items:center;font-size:32px;font-style:normal;background:#fff0c2;flex:none}.it div{flex:1}.it b{display:block}.it small{opacity:.65}.it .q{display:flex;align-items:center;gap:8px;margin-top:6px}.it .q button{width:30px;height:30px;border-radius:50%;border:2px solid #ef8300;background:#fff;color:#ef8300;font:700 18px var(--f1);cursor:pointer}.it .q span{min-width:18px;text-align:center;font-weight:800}
.bar{position:sticky;bottom:12px;margin:26px auto 0;max-width:700px;background:#3b2a12;color:#fff;border-radius:22px;padding:14px 18px;display:flex;justify-content:space-between;align-items:center;gap:12px;box-shadow:0 14px 34px rgba(59,42,18,.35)}.bar b{font:600 18px var(--f1)}.bar .btn{background:#25d366}
.loc{display:grid;grid-template-columns:1fr 1fr;gap:22px;background:#fff;border-radius:26px;padding:28px}.map{border-radius:18px;background:linear-gradient(135deg,#e6f0d6,#cfe3b3);min-height:170px;position:relative}.map::after{content:"📍";position:absolute;left:46%;top:36%;font-size:38px}""",
    '<div class="w"><nav><b>Almacén Doña Rosa</b><span>📍 Av. Rivadavia 6700 · Lun a Sáb 8 a 21 h</span></nav><section class="hero"><div><h1>Lo de siempre, <em>ahora por WhatsApp.</em></h1><p>Armá tu pedido tocando los productos y nos lo mandás. Lo preparamos y lo retirás o te lo llevamos.</p><a class="btn" href="#cat">Armar pedido ↓</a></div><div class="sign"><b>¡Promos de la semana!</b><small>Hasta el domingo o hasta agotar stock</small></div></section>'
    '<div class="promos"><div>Picada para 4 · $ 18.900</div><div>2 × 1 en quesos cremosos</div><div>Aceite de oliva · 20 % off</div></div></div>'
    '<section class="sec" id="cat" style="padding-top:0"><div class="w"><h2>Catálogo</h2><div class="cat" id="ct"></div><div class="bar"><b id="bt">Tu pedido está vacío</b><button class="btn" id="bs">Enviar por WhatsApp</button></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w"><div class="loc"><div><h2 style="font-size:30px">Pasá a visitarnos</h2><p>Av. Rivadavia 6700, Flores.<br>Lunes a sábado de 8 a 21 h.<br>Hacemos entregas en el barrio.</p></div><div class="map"></div></div></div></section><footer>Almacén Doña Rosa · Desde 1989</footer>',
    """<script>(function(){var P=[['Picada para 4','Jamón, queso y salame',18900,'🧀'],['Queso cremoso','El kilo',9800,'🧈'],['Aceite de oliva','Botella de 500 ml',7400,'🫒'],['Yerba 1 kg','Marca de siempre',4900,'🧉'],['Fideos secos','Paquete de 500 g',1800,'🍝'],['Dulce de leche','Pote de 400 g',3200,'🍯']],C={};
document.getElementById('ct').innerHTML=P.map(function(p,i){return'<div class="it"><i>'+p[3]+'</i><div><b>'+p[0]+'</b><small>'+p[1]+' · $ '+p[2].toLocaleString('es-AR')+'</small><div class="q"><button data-i="'+i+'" data-d="-1" aria-label="Menos">−</button><span id="q'+i+'">0</span><button data-i="'+i+'" data-d="1" aria-label="Más">+</button></div></div></div>'}).join('');
function r(){var t=0,n=0,m=[];P.forEach(function(p,i){var q=C[i]||0;document.getElementById('q'+i).textContent=q;if(q){t+=q*p[2];n+=q;m.push(q+' '+p[0])}});document.getElementById('bt').textContent=n?n+' productos · $ '+t.toLocaleString('es-AR'):'Tu pedido está vacío';return m.length?'Hola Doña Rosa, quiero: '+m.join(', ')+'. Total $ '+t.toLocaleString('es-AR'):''}
document.getElementById('ct').onclick=function(e){var b=e.target.closest('button');if(!b)return;var i=b.dataset.i;C[i]=Math.max(0,(C[i]||0)+(+b.dataset.d));r()};
document.getElementById('bs').onclick=function(){wa(r()||'Primero elegí algún producto')}})()</script>""")

# ───────── Construcción · Obras Martínez ─────────
B["construccion"] = page("Obras Martínez", "family=Archivo+Black&family=Space+Mono:wght@400;700&family=Archivo:wght@400;600",
    dict(bg="#e9e9e5", ink="#161616", pri="#ffb703", **{"pri-ink": "#161616"}, r="0px", f1="'Archivo Black',sans-serif", f2="Archivo,sans-serif"),
    """nav{display:flex;justify-content:space-between;align-items:center;padding:18px 0;border-bottom:4px solid #161616}nav b{font:400 28px var(--f1);text-transform:uppercase}nav b span{background:#ffb703;padding:0 8px}nav div{display:flex;gap:24px;font:700 13px 'Space Mono',monospace;text-transform:uppercase}
.hero{padding:44px 0}.hero h1{font:400 clamp(54px,10vw,128px)/.88 var(--f1);text-transform:uppercase;letter-spacing:-.03em}.hero h1 span{background:#ffb703;padding:0 12px}.hero p{font:400 17px 'Space Mono',monospace;max-width:46ch;margin:22px 0 26px}.btn{border:4px solid #161616;box-shadow:6px 6px 0 #161616;font-family:'Space Mono',monospace;text-transform:uppercase}
.stripe{height:26px;background:repeating-linear-gradient(135deg,#161616 0 18px,#ffb703 18px 36px)}
.srv{display:grid;grid-template-columns:repeat(3,1fr);gap:0;border:4px solid #161616}.srv article{padding:28px;border-right:4px solid #161616;background:#fff}.srv article:last-child{border-right:0}.srv small{font:700 13px 'Space Mono',monospace}.srv h3{font:400 34px var(--f1);text-transform:uppercase;margin:6px 0}.srv p{font-size:15px}
.ba{position:relative;aspect-ratio:16/8;border:4px solid #161616;overflow:hidden;--x:50%;user-select:none}.ba .l{position:absolute;inset:0;display:grid;place-items:center;font:400 60px var(--f1);color:rgba(255,255,255,.9);text-transform:uppercase}.ba .antes{background:linear-gradient(135deg,#8b8579,#5f5a50)}.ba .desp{background:linear-gradient(135deg,#f7d56b,#e2a62a);clip-path:inset(0 0 0 var(--x))}.ba .ln{position:absolute;top:0;bottom:0;left:var(--x);width:6px;margin-left:-3px;background:#161616}.ba input{position:absolute;inset:0;width:100%;height:100%;opacity:0;cursor:ew-resize}.ba .t{position:absolute;top:12px;font:700 13px 'Space Mono';background:#161616;color:#fff;padding:4px 10px}
.pres{display:grid;grid-template-columns:1fr 1fr;gap:30px;background:#161616;color:#fff;padding:44px}.pres h2{color:#ffb703;text-transform:uppercase}.pres form{display:grid;gap:10px}.pres input,.pres select{padding:14px;border:0;font:400 15px 'Space Mono',monospace}.pres .btn{background:#ffb703;box-shadow:6px 6px 0 #fff;border-color:#ffb703;justify-content:center}
.rev{font:400 18px 'Space Mono',monospace;border-left:8px solid #ffb703;padding:6px 0 6px 20px;margin:10px 0}""",
    '<div class="w"><nav><b>Obras <span>Martínez</span></b><div><a>Qué hacemos</a><a>Obras</a><a>Presupuesto</a></div></nav><section class="hero"><h1>Reformas <span>sin sorpresas.</span></h1><p>Cocinas, baños y ampliaciones en CABA y zona norte. Presupuesto cerrado por escrito, cronograma semanal y garantía de obra.</p><a class="btn" href="#pres">Pedir presupuesto →</a></section></div><div class="stripe"></div>'
    '<section class="sec"><div class="w"><h2 style="font-family:var(--f1);text-transform:uppercase">Qué hacemos</h2><div class="srv"><article><small>01</small><h3>Cocinas</h3><p>Demolición, instalaciones, muebles y mesadas.</p></article><article><small>02</small><h3>Baños</h3><p>Revestimientos, sanitarios y griferías.</p></article><article><small>03</small><h3>Ampliaciones</h3><p>Habitaciones, quinchos y entrepisos.</p></article></div></div></section>'
    '<section class="sec" style="padding-top:0"><div class="w"><h2 style="font-family:var(--f1);text-transform:uppercase">Antes y después</h2><div class="ba" id="ba"><div class="l antes">Antes</div><div class="l desp">Después</div><div class="ln"></div><span class="t" style="left:12px">ANTES</span><span class="t" style="right:12px">DESPUÉS</span><input type="range" min="0" max="100" value="50" aria-label="Comparar antes y después"></div><div class="rev">“Terminaron en la fecha prometida y el presupuesto no se movió.” — Laura, Villa Urquiza</div></div></section>'
    '<div class="w" id="pres"><div class="pres"><div><h2>Pedí tu presupuesto</h2><p style="font:400 15px \'Space Mono\',monospace;opacity:.8">Contanos qué querés hacer. Te respondemos en 24 h con una visita sin cargo.</p></div><form onsubmit="wa(\'Pedido de presupuesto enviado (demo)\');return false"><select aria-label="Tipo de obra"><option>Cocina</option><option>Baño</option><option>Ampliación</option></select><input placeholder="Metros cuadrados aprox." aria-label="Metros cuadrados"><input placeholder="Tu WhatsApp" aria-label="WhatsApp"><button class="btn">Enviar pedido</button></form></div></div><footer>Obras Martínez · Matriculado COPAIPA · Zona norte y CABA</footer>',
    """<script>document.querySelector('#ba input').oninput=function(){document.getElementById('ba').style.setProperty('--x',this.value+'%')}</script>""")
