# -*- coding: utf-8 -*-
"""
Negocios de Argentina a los que se les puede vender una web.
Alimenta dos cosas:
  - la categoría "Negocios para vender" del Lab de Programación (fields, related)
  - el constructor armar.html (preset: textos, paleta, tipografías, estilo, secciones y funcionalidades por defecto)
Los nombres de los negocios del preset son inventados (ejemplos), no marcas reales.
"""

def n(id, name, summary, tags, web, funciones, clientes, pitch, related, preset):
    return dict(id=id, name=name, summary=summary, tags=tags,
                fields=[["Qué web le vendés", web], ["Funcionalidades que venden", funciones],
                        ["Cómo le trae clientes", clientes], ["Argumento de venta", pitch]],
                related=related, preset=preset)

NEGOCIOS = [
  n("restaurante", "Restaurante, bar o café", "Carta siempre actualizada, reservas y pedidos por WhatsApp.",
    ["gastronomía", "reservas", "WhatsApp"],
    "Landing con la carta, fotos, reservas y ubicación. Si hace delivery, catálogo con pedido por WhatsApp.",
    "Carta con QR para las mesas, reservas online, botón de WhatsApp, mapa y horarios, reseñas de Google.",
    "Aparece en Google Maps cuando buscan 'dónde comer cerca', y la carta con QR ahorra reimprimir menús cada vez que cambian los precios.",
    "Con la inflación los precios cambian todo el tiempo: con la carta online los actualizás en un minuto y no reimprimís nada.",
    ["soluciones/landing", "soluciones/catalogo", "servicios/mercadopago", "servicios/ga4"],
    dict(nombre="La Esquina de Palermo", hero="Cocina de barrio, fuego lento.", sub="Parrilla y pastas caseras en Palermo. Reservá tu mesa o pedí por WhatsApp.",
         cta="Reservar mesa", itemsLabel="La carta",
         items=[["Bife de chorizo", "Con papas rústicas", "$18.500"], ["Sorrentinos de calabaza", "Manteca y salvia", "$12.900"], ["Flan casero", "Con dulce de leche", "$5.800"]],
         paleta="terracota", fuentes="clasica", estilo="calido", objetivo="turnos",
         secciones=["hero", "servicios", "galeria", "resenas", "ubicacion", "contacto"], funciones=["whatsapp", "turnos", "mapa", "resenas"])),
  n("delivery", "Rotisería, delivery o dark kitchen", "Menú online con pedido armado que llega directo al WhatsApp.",
    ["gastronomía", "pedidos", "Mercado Pago"],
    "Catálogo con carrito que arma el pedido y lo manda por WhatsApp, con pago por Mercado Pago.",
    "Carrito simple, pedido por WhatsApp con el detalle armado, link de pago de Mercado Pago, zonas y horarios de envío.",
    "Sale de las comisiones de las apps de delivery: los clientes que ya lo conocen piden directo por su web.",
    "Cada pedido que entra por tu web y no por la app es una comisión que no pagás.",
    ["soluciones/catalogo", "soluciones/ecommerce", "servicios/mercadopago"],
    dict(nombre="Rotisería Don Tito", hero="Comida casera, lista en 30 minutos.", sub="Armá tu pedido acá, te llega por WhatsApp y pagás con Mercado Pago.",
         cta="Hacer mi pedido", itemsLabel="Menú del día",
         items=[["Milanesa napolitana", "Con puré o fritas", "$11.200"], ["Tarta de jamón y queso", "Porción grande", "$6.400"], ["Pollo al horno", "Medio pollo con papas", "$13.900"]],
         paleta="citrico", fuentes="impacto", estilo="vibrante", objetivo="vender",
         secciones=["hero", "servicios", "ubicacion", "contacto"], funciones=["whatsapp", "carrito", "mercadopago", "mapa"])),
  n("inmobiliaria", "Inmobiliaria", "Propiedades con filtros, fichas con fotos y contacto directo con el agente.",
    ["inmobiliaria", "leads", "SEO local"],
    "Web institucional con buscador de propiedades, ficha de cada una y formulario que llega al agente.",
    "Buscador por zona, tipo y precio, fichas con galería, WhatsApp por propiedad, tasaciones online, panel para cargar propiedades.",
    "Capta consultas propias además de los portales, y cada propiedad compartida en redes lleva a su web.",
    "Hoy le pagás a los portales por cada aviso: con tu web los interesados te contactan directo y la marca es tuya.",
    ["soluciones/institucional", "soluciones/marketplace", "arquitecturas/headless-cms"],
    dict(nombre="Aguirre Propiedades", hero="Tu próxima casa está en Belgrano.", sub="Venta y alquiler con 20 años en el barrio. Tasamos tu propiedad sin cargo.",
         cta="Pedir tasación", itemsLabel="Propiedades destacadas",
         items=[["3 ambientes con balcón", "Belgrano R · 78 m²", "USD 165.000"], ["Casa con jardín", "Villa Urquiza · 140 m²", "USD 240.000"], ["Monoambiente a estrenar", "Núñez · 35 m²", "Alquiler"]],
         paleta="marino", fuentes="moderna", estilo="minimal", objetivo="leads",
         secciones=["hero", "servicios", "equipo", "resenas", "contacto"], funciones=["formulario", "whatsapp", "panel", "mapa"])),
  n("consultorio", "Consultorio médico u odontológico", "Turnos online, obras sociales y confianza desde el primer clic.",
    ["salud", "turnos", "confianza"],
    "Web institucional con turnos online, especialidades, profesionales y obras sociales.",
    "Turnos online con recordatorio, listado de obras sociales, WhatsApp, mapa, preguntas frecuentes.",
    "Aparece en Google cuando buscan la especialidad en la zona y baja las llamadas para sacar turno.",
    "La secretaria deja de atender el teléfono para dar turnos: el paciente lo saca solo a cualquier hora.",
    ["soluciones/reservas", "soluciones/institucional", "servicios/clerk"],
    dict(nombre="Consultorio Odontológico Rivas", hero="Tu sonrisa, en buenas manos.", sub="Odontología general, ortodoncia e implantes en Caballito. Sacá tu turno online.",
         cta="Sacar turno", itemsLabel="Especialidades",
         items=[["Limpieza y control", "Cada 6 meses", "OSDE · Swiss"], ["Ortodoncia", "Brackets y alineadores", "Consultá"], ["Implantes", "Evaluación sin cargo", "Financiación"]],
         paleta="clinico", fuentes="moderna", estilo="minimal", objetivo="turnos",
         secciones=["hero", "servicios", "equipo", "turnos", "faq", "ubicacion"], funciones=["turnos", "whatsapp", "mapa", "resenas"])),
  n("estudio", "Estudio contable o jurídico", "Autoridad, servicios claros y un formulario que filtra consultas.",
    ["profesionales", "leads", "confianza"],
    "Web institucional sobria con servicios, equipo, novedades y formulario de consulta calificado.",
    "Formulario con motivo de consulta, blog de novedades impositivas, WhatsApp, área de clientes para documentos.",
    "El blog con novedades (vencimientos, cambios de normativa) posiciona en Google y trae consultas nuevas cada mes.",
    "Un cliente que te encuentra por un artículo sobre monotributo ya llega sabiendo que sabés.",
    ["soluciones/institucional", "soluciones/blog", "servicios/formspree"],
    dict(nombre="Estudio Ferrari & Asociados", hero="Tus números, en orden.", sub="Contabilidad, impuestos y sueldos para pymes y monotributistas.",
         cta="Hacer una consulta", itemsLabel="Servicios",
         items=[["Monotributo", "Alta, recategorización y baja", "Mensual"], ["Sociedades", "Balances y DDJJ", "Anual"], ["Sueldos", "Liquidación y F.931", "Mensual"]],
         paleta="marino", fuentes="clasica", estilo="editorial", objetivo="leads",
         secciones=["hero", "servicios", "equipo", "blog", "faq", "contacto"], funciones=["formulario", "whatsapp", "blog", "panel"])),
  n("gimnasio", "Gimnasio, box o estudio de yoga", "Planes, horarios de clases y reserva de lugar.",
    ["fitness", "turnos", "suscripción"],
    "Landing con planes, grilla de clases, reserva de lugar y pago de la cuota online.",
    "Grilla de horarios, reserva de clase, planes con débito por Mercado Pago, clase de prueba gratis, WhatsApp.",
    "La clase de prueba gratis capta gente nueva, y el débito automático reduce la morosidad de las cuotas.",
    "Con la cuota por débito automático dejás de perseguir a los que se olvidan de pagar.",
    ["soluciones/landing", "soluciones/reservas", "servicios/mercadopago"],
    dict(nombre="Box Norte", hero="Entrená fuerte. Entrená acá.", sub="Funcional y crossfit en Vicente López. Tu primera clase es gratis.",
         cta="Reservar clase gratis", itemsLabel="Planes",
         items=[["2 veces por semana", "Ideal para empezar", "$32.000/mes"], ["Libre", "Todas las clases", "$45.000/mes"], ["Personalizado", "Con entrenador", "Consultá"]],
         paleta="grafito", fuentes="impacto", estilo="oscuro", objetivo="turnos",
         secciones=["hero", "servicios", "precios", "turnos", "resenas", "contacto"], funciones=["turnos", "mercadopago", "whatsapp", "resenas"])),
  n("estetica", "Peluquería, barbería o centro de estética", "Turnos online, servicios con precio y galería de trabajos.",
    ["belleza", "turnos", "Instagram"],
    "Landing con servicios y precios, galería de trabajos y turnos online con seña.",
    "Turnos con seña por Mercado Pago (baja las ausencias), galería conectada al Instagram, WhatsApp, reseñas.",
    "Instagram muestra el trabajo; la web convierte ese interés en turnos sin ir y venir por mensajes.",
    "La seña online reduce los turnos perdidos, y eso es plata que hoy se te escapa.",
    ["soluciones/reservas", "soluciones/landing", "servicios/mercadopago"],
    dict(nombre="Estudio Lumière", hero="Tu mejor versión empieza acá.", sub="Color, cortes y tratamientos en Recoleta. Reservá online en un minuto.",
         cta="Reservar turno", itemsLabel="Servicios",
         items=[["Corte y brushing", "45 minutos", "$15.000"], ["Color completo", "Incluye tratamiento", "$38.000"], ["Keratina", "Hasta 3 meses", "$52.000"]],
         paleta="lavanda", fuentes="elegante", estilo="calido", objetivo="turnos",
         secciones=["hero", "servicios", "galeria", "turnos", "resenas", "ubicacion"], funciones=["turnos", "mercadopago", "whatsapp", "resenas"])),
  n("veterinaria", "Veterinaria y pet shop", "Turnos, urgencias visibles y tienda de alimentos.",
    ["mascotas", "turnos", "tienda"],
    "Web con turnos, guardia de urgencias bien visible y catálogo de alimentos con envío.",
    "Botón de urgencias, turnos online, catálogo con carrito, recordatorio de vacunas, WhatsApp.",
    "Aparece en Google Maps en las búsquedas de urgencia, y la tienda online vende alimento con envío a domicilio.",
    "El que compra el alimento online vuelve todos los meses: es venta recurrente que hoy se lleva el súper.",
    ["soluciones/reservas", "soluciones/ecommerce", "servicios/tiendanube"],
    dict(nombre="Veterinaria Patitas", hero="Cuidamos a los que más querés.", sub="Clínica, vacunas y peluquería canina en Flores. Urgencias las 24 hs.",
         cta="Sacar turno", itemsLabel="Servicios",
         items=[["Consulta clínica", "Con turno", "$14.000"], ["Plan de vacunas", "Cachorros y adultos", "Consultá"], ["Alimento premium", "Envío en el día", "Tienda"]],
         paleta="bosque", fuentes="amigable", estilo="calido", objetivo="turnos",
         secciones=["hero", "servicios", "turnos", "resenas", "ubicacion", "contacto"], funciones=["turnos", "whatsapp", "carrito", "mapa"])),
  n("tienda", "Marca que vende en Mercado Libre", "Tienda propia para no depender sólo del marketplace.",
    ["e-commerce", "Mercado Libre", "marca"],
    "E-commerce propio (Tienda Nube o a medida) conectado al stock, con la identidad de la marca.",
    "Catálogo con filtros, checkout con Mercado Pago, envíos, cupones para clientes que vuelven, integración de stock con ML.",
    "Las ventas propias no pagan comisión del marketplace y los datos del cliente quedan en la marca para volver a venderle.",
    "En Mercado Libre el cliente es de Mercado Libre; en tu tienda el cliente es tuyo.",
    ["soluciones/ecommerce", "arquitecturas/ecommerce-saas", "servicios/tiendanube", "servicios/mercadopago"],
    dict(nombre="Casa Bosque", hero="Utensilios que duran toda la vida.", sub="Cocina alemana y diseño argentino. Envío gratis desde $60.000.",
         cta="Ver productos", itemsLabel="Más vendidos",
         items=[["Mandolina V5", "5 placas · Inox", "$64.900"], ["Set de cuchillos", "Acero alemán", "$89.500"], ["Rallador multiuso", "Apto lavavajillas", "$23.900"]],
         paleta="mono", fuentes="moderna", estilo="minimal", objetivo="vender",
         secciones=["hero", "servicios", "resenas", "faq", "contacto"], funciones=["carrito", "mercadopago", "whatsapp", "panel", "analitica"])),
  n("comercio", "Comercio de barrio con catálogo", "Catálogo simple que se pide por WhatsApp, sin carrito complejo.",
    ["comercio", "WhatsApp", "catálogo"],
    "Catálogo sin carrito: productos con precio y un botón que arma el pedido por WhatsApp.",
    "Catálogo editable desde el celular, pedido por WhatsApp, horarios, ubicación, promociones de la semana.",
    "Los clientes del barrio consultan precios antes de ir y hacen el pedido desde la casa.",
    "Tus clientes ya te escriben por WhatsApp: con el catálogo te llegan los pedidos armados y no perdés tiempo pasando precios.",
    ["soluciones/catalogo", "soluciones/landing"],
    dict(nombre="Almacén Doña Rosa", hero="Lo de siempre, ahora por WhatsApp.", sub="Fiambres, quesos y almacén en Villa Crespo. Armá tu pedido y pasalo a buscar.",
         cta="Armar pedido", itemsLabel="Promos de la semana",
         items=[["Picada para 4", "Fiambres y quesos", "$21.000"], ["Queso cremoso", "Por kilo", "$9.800"], ["Aceite de oliva", "Botella 1 litro", "$14.500"]],
         paleta="citrico", fuentes="amigable", estilo="vibrante", objetivo="consultas",
         secciones=["hero", "servicios", "ubicacion", "contacto"], funciones=["whatsapp", "mapa"])),
  n("construccion", "Constructora, arquitectura o reformas", "Portfolio de obras que genera pedidos de presupuesto.",
    ["construcción", "portfolio", "presupuestos"],
    "Web con portfolio de obras (antes y después), servicios y formulario de presupuesto detallado.",
    "Galería de obras por categoría, antes y después, formulario de presupuesto con metros y tipo de obra, WhatsApp.",
    "Las fotos de obras terminadas son la mejor prueba, y el formulario filtra consultas serias con datos para cotizar.",
    "Un cliente que ve tus obras terminadas llega convencido; el formulario te trae los datos para cotizar sin ir al lugar.",
    ["soluciones/portfolio", "soluciones/institucional"],
    dict(nombre="Obras Martínez", hero="Reformas sin sorpresas.", sub="Cocinas, baños y ampliaciones en zona norte. Presupuesto en 48 horas.",
         cta="Pedir presupuesto", itemsLabel="Qué hacemos",
         items=[["Cocinas", "Diseño y ejecución", "Llave en mano"], ["Baños", "En 15 días hábiles", "Con garantía"], ["Ampliaciones", "Con planos y permisos", "A medida"]],
         paleta="grafito", fuentes="tecnica", estilo="brutal", objetivo="leads",
         secciones=["hero", "servicios", "galeria", "resenas", "contacto"], funciones=["formulario", "whatsapp", "panel"])),
  n("turismo", "Cabañas, hotel boutique o turismo", "Reservas directas sin comisión de las plataformas.",
    ["turismo", "reservas", "Mercado Pago"],
    "Web con galería, disponibilidad, reserva con seña y actividades de la zona.",
    "Calendario de disponibilidad, reserva con seña por Mercado Pago, galería, mapa, versión en inglés.",
    "Los huéspedes que vuelven reservan directo y sin comisión; la versión en inglés capta turismo extranjero.",
    "Cada reserva directa te ahorra la comisión de la plataforma de alquiler.",
    ["soluciones/reservas", "soluciones/landing", "servicios/mercadopago"],
    dict(nombre="Cabañas Los Coihues", hero="Despertate frente al lago.", sub="Cabañas para 2 a 6 personas en San Martín de los Andes. Reservá directo.",
         cta="Ver disponibilidad", itemsLabel="Cabañas",
         items=[["Cabaña Lago", "2 personas · Vista al lago", "Por noche"], ["Cabaña Bosque", "4 personas · Parrilla", "Por noche"], ["Cabaña Familia", "6 personas · 2 baños", "Por noche"]],
         paleta="bosque", fuentes="elegante", estilo="editorial", objetivo="turnos",
         secciones=["hero", "servicios", "galeria", "turnos", "resenas", "ubicacion"], funciones=["turnos", "mercadopago", "idiomas", "mapa", "resenas"])),
  n("educacion", "Instituto, cursos o clases particulares", "Oferta de cursos, inscripción online y pago de cuotas.",
    ["educación", "inscripción", "suscripción"],
    "Web con la oferta de cursos, inscripción online, pago de matrícula y campus o material para alumnos.",
    "Fichas de cursos con fechas, inscripción con pago por Mercado Pago, área de alumnos, preguntas frecuentes.",
    "Cada curso tiene su página en Google, y la inscripción con pago cierra la venta sin mensajes de ida y vuelta.",
    "Mientras dormís, alguien se está inscribiendo: la web vende las vacantes sola.",
    ["soluciones/landing", "soluciones/saas", "servicios/mercadopago"],
    dict(nombre="Instituto Horizonte", hero="Aprendé un oficio en 6 meses.", sub="Cursos presenciales y online con certificado. Inscripciones abiertas.",
         cta="Inscribirme", itemsLabel="Cursos",
         items=[["Marketing digital", "6 meses · Online", "Cuotas"], ["Programación web", "8 meses · Híbrido", "Cuotas"], ["Diseño gráfico", "5 meses · Presencial", "Cuotas"]],
         paleta="marino", fuentes="moderna", estilo="vibrante", objetivo="leads",
         secciones=["hero", "servicios", "precios", "resenas", "faq", "contacto"], funciones=["formulario", "mercadopago", "panel", "blog"])),
  n("eventos", "Salón de eventos, catering o fotografía", "Galería que enamora y pedido de presupuesto por fecha.",
    ["eventos", "presupuestos", "galería"],
    "Web con galería de eventos, paquetes y consulta de disponibilidad por fecha.",
    "Galería por tipo de evento, consulta de fecha disponible, paquetes, testimonios, WhatsApp.",
    "Las parejas y empresas comparan varias opciones: la galería y los paquetes claros ayudan a que te elijan.",
    "Cuando alguien compara tres salones, gana el que muestra mejor y responde primero.",
    ["soluciones/portfolio", "soluciones/landing"],
    dict(nombre="Quinta El Aromo", hero="El lugar para tu gran día.", sub="Casamientos, cumpleaños y eventos corporativos en Pilar. Consultá tu fecha.",
         cta="Consultar fecha", itemsLabel="Paquetes",
         items=[["Casamientos", "Hasta 250 invitados", "Todo incluido"], ["Cumpleaños de 15", "Con DJ y ambientación", "Consultá"], ["Corporativos", "Jornadas y fiestas", "A medida"]],
         paleta="lavanda", fuentes="clasica", estilo="editorial", objetivo="leads",
         secciones=["hero", "servicios", "galeria", "resenas", "contacto"], funciones=["formulario", "whatsapp", "mapa", "resenas"])),
  n("hogar", "Plomero, electricista o aire acondicionado", "Urgencias por WhatsApp y confianza con reseñas.",
    ["oficios", "urgencias", "SEO local"],
    "Landing simple, rápida y con WhatsApp siempre visible, orientada a búsquedas locales.",
    "Botón de WhatsApp y llamada, zonas de cobertura, matrícula visible, reseñas de Google, formulario de presupuesto.",
    "Cuando alguien busca 'electricista urgente' en su barrio, la web con reseñas y WhatsApp gana el trabajo.",
    "La gente llama al primero que le da confianza: reseñas y matrícula a la vista hacen que ese seas vos.",
    ["soluciones/landing"],
    dict(nombre="Frío Total", hero="Tu aire funcionando hoy.", sub="Instalación y service de aires en CABA y GBA. Técnico matriculado.",
         cta="Pedir técnico", itemsLabel="Servicios",
         items=[["Instalación", "Split hasta 6000 frigorías", "Con garantía"], ["Service", "Limpieza y carga de gas", "En el día"], ["Reparación", "Diagnóstico sin cargo", "Urgencias"]],
         paleta="clinico", fuentes="impacto", estilo="brutal", objetivo="consultas",
         secciones=["hero", "servicios", "resenas", "faq", "contacto"], funciones=["whatsapp", "formulario", "resenas"])),
  n("profesional", "Profesional independiente", "Psicólogos, nutricionistas, coaches: marca personal y turnos.",
    ["marca personal", "turnos", "confianza"],
    "Web personal con enfoque, formación, modalidad (presencial u online) y turnos.",
    "Turnos online, sesiones por videollamada, pago anticipado, blog para posicionarse, WhatsApp.",
    "El blog responde las dudas que la gente busca en Google y la lleva a pedir la primera sesión.",
    "Tu web trabaja por vos: explica cómo trabajás antes de la primera sesión y filtra a quien no es tu paciente.",
    ["soluciones/portfolio", "soluciones/reservas", "soluciones/blog"],
    dict(nombre="Lic. Carolina Díaz", hero="Hablemos de lo que te pasa.", sub="Psicóloga clínica. Sesiones presenciales en Palermo y online.",
         cta="Pedir primera sesión", itemsLabel="Modalidades",
         items=[["Terapia individual", "Adultos y adolescentes", "Presencial u online"], ["Terapia de pareja", "Sesiones de 60 min", "Online"], ["Orientación vocacional", "4 encuentros", "Online"]],
         paleta="bosque", fuentes="elegante", estilo="calido", objetivo="turnos",
         secciones=["hero", "servicios", "equipo", "turnos", "faq", "contacto"], funciones=["turnos", "whatsapp", "blog", "mercadopago"])),
]

# Ejemplos reales argentinos para cada tipo de web y a quién se lo podés vender
VENDER = {
  "landing":       "Gimnasios, oficios (plomeros, electricistas), lanzamientos de productos, cursos.",
  "institucional": "Estudios contables y jurídicos, inmobiliarias, constructoras, pymes industriales.",
  "portfolio":     "Arquitectos, fotógrafos, diseñadores, profesionales independientes.",
  "ecommerce":     "Marcas que venden en Mercado Libre y quieren canal propio, tiendas de ropa, vinotecas.",
  "catalogo":      "Almacenes, rotiserías, distribuidoras mayoristas, comercios de barrio.",
  "blog":          "Estudios contables (novedades impositivas), nutricionistas, inmobiliarias (guías de barrios).",
  "saas":          "Emprendedores con una idea de producto digital; es el proyecto más grande de la lista.",
  "dashboard":     "Pymes que llevan todo en Excel: stock, ventas, métricas de Mercado Libre.",
  "reservas":      "Consultorios, peluquerías, canchas de pádel, cabañas, gimnasios.",
  "marketplace":   "Proyectos que juntan oferentes y clientes: oficios, alquileres temporarios, clases.",
  "interna":       "Empresas con procesos en papel o planillas: pedidos, turnos del personal, inventario.",
  "docs":          "Empresas de software, instituciones con reglamentos o manuales de procedimiento.",
  "pwa":           "Delivery, clubes y gimnasios que quieren 'una app' sin pasar por las tiendas.",
}
EJEMPLOS_AR = {
  "landing":       [["Ualá", "https://www.uala.com.ar"], ["Brubank", "https://www.brubank.com"]],
  "institucional": [["Arcor", "https://www.arcor.com"], ["YPF", "https://www.ypf.com"]],
  "portfolio":     [["Esta web", "index.html"]],
  "ecommerce":     [["Frávega", "https://www.fravega.com"], ["Musimundo", "https://www.musimundo.com"]],
  "blog":          [["Infobae", "https://www.infobae.com"], ["La Nación", "https://www.lanacion.com.ar"]],
  "saas":          [["Tiendanube", "https://www.tiendanube.com"], ["Xubio", "https://xubio.com"]],
  "dashboard":     [["ML Tracker", "herramientas.html#tracker"]],
  "reservas":      [["Doctoralia", "https://www.doctoralia.com.ar"]],
  "marketplace":   [["Mercado Libre", "https://www.mercadolibre.com.ar"], ["Zonaprop", "https://www.zonaprop.com.ar"], ["PedidosYa", "https://www.pedidosya.com.ar"]],
  "interna":       [["Panel admin de esta web (privado)", "admin.html"]],
  "docs":          [["Mercado Libre Developers", "https://developers.mercadolibre.com.ar"], ["Argentina.gob.ar", "https://www.argentina.gob.ar"]],
}
