# -*- coding: utf-8 -*-
"""
Contenido curado (en castellano) del Lab de Programación.
Cada entrada: id, name, summary, tags, fields (lista de [etiqueta, valor]), related (ids "categoria/id").
Para sumar contenido: agregá entradas acá y corré  python3 tools/build-weblab.py
"""

SOLUCIONES = [
  dict(id="landing", name="Landing page", summary="Una sola página enfocada en una acción: registrarse, comprar, pedir una demo o contactar.",
       tags=["marketing", "conversión", "una página"],
       fields=[["Cuándo conviene", "Lanzamientos, campañas de pauta, validar una idea o captar leads de un producto puntual."],
               ["Secciones típicas", "Hero con propuesta de valor · beneficios · prueba social (testimonios, logos, números) · preguntas frecuentes · CTA final."],
               ["Funcionalidades clave", "Formulario o botón de acción único, píxeles de medición (Meta, Google), carga muy rápida, versión mobile impecable."],
               ["Complejidad", "Baja"],
               ["Errores comunes", "Muchas acciones compitiendo, textos genéricos, formularios largos, imágenes pesadas que frenan la carga."]],
       related=["arquitecturas/estatico", "arquitecturas/jamstack", "servicios/vercel", "servicios/formspree", "servicios/ga4", "landing/hero-features-cta"]),
  dict(id="institucional", name="Web institucional", summary="La presencia oficial de una empresa u organización: quiénes son, qué hacen y cómo contactarlos.",
       tags=["empresa", "multi-página", "SEO"],
       fields=[["Cuándo conviene", "Pymes, estudios profesionales, consultorios, organismos. Cuando la confianza y el SEO local importan."],
               ["Secciones típicas", "Inicio · Nosotros · Servicios · Casos o clientes · Novedades · Contacto con mapa."],
               ["Funcionalidades clave", "Contenido editable sin programar (CMS), formulario de contacto, WhatsApp, Google Business, SEO local."],
               ["Complejidad", "Baja a media"],
               ["Errores comunes", "Textos que nadie actualiza, no tener datos de contacto visibles, no cargar la ficha de Google."]],
       related=["arquitecturas/jamstack", "arquitecturas/headless-cms", "stacks/astro", "servicios/wordpress", "servicios/sanity"]),
  dict(id="portfolio", name="Portfolio / CV online", summary="Muestra quién sos, qué hiciste y cómo contactarte. Tu mejor carta de presentación.",
       tags=["personal", "marca personal", "reclutadores"],
       fields=[["Cuándo conviene", "Búsqueda laboral, freelancers, creativos, desarrolladores."],
               ["Secciones típicas", "Hero con nombre y rol · métricas clave · experiencia · casos con resultados · formación · contacto."],
               ["Funcionalidades clave", "Casos de éxito con números reales, CV descargable, contacto de un clic, tema claro/oscuro, carga rápida."],
               ["Complejidad", "Baja a media"],
               ["Ejemplo propio", "Esta misma web: HTML/CSS/JS sin framework + funciones serverless en Vercel + MongoDB."]],
       related=["arquitecturas/estatico", "arquitecturas/serverless", "servicios/vercel", "servicios/mongodb-atlas", "stacks/vanilla"]),
  dict(id="ecommerce", name="E-commerce / tienda online", summary="Catálogo con carrito, pagos y gestión de pedidos para vender online.",
       tags=["ventas", "pagos", "catálogo"],
       fields=[["Cuándo conviene", "Marcas que quieren canal propio además de Mercado Libre, o márgenes que no soportan las comisiones del marketplace."],
               ["Secciones típicas", "Home con destacados · listado con filtros · ficha de producto · carrito · checkout · mi cuenta."],
               ["Funcionalidades clave", "Pagos (Mercado Pago), cálculo de envío, stock, cupones, emails transaccionales, integración con el marketplace."],
               ["Complejidad", "Media a alta (baja si se usa una plataforma como Tienda Nube o Shopify)"],
               ["Errores comunes", "Checkout con demasiados pasos, fotos de baja calidad, costos de envío que aparecen al final."]],
       related=["arquitecturas/ecommerce-saas", "arquitecturas/headless-cms", "servicios/mercadopago", "servicios/tiendanube", "stacks/nextjs"]),
  dict(id="catalogo", name="Catálogo sin carrito", summary="Muestra productos o servicios y deriva la venta a WhatsApp, a un local o a Mercado Libre.",
       tags=["ventas", "WhatsApp", "simple"],
       fields=[["Cuándo conviene", "Negocios chicos, mayoristas, productos que requieren asesoramiento o precios a consultar."],
               ["Funcionalidades clave", "Buscador y filtros, botón “Consultar por WhatsApp” con el producto precargado, link a la publicación de ML."],
               ["Complejidad", "Baja"],
               ["Ventaja", "Cero costos de pasarela y se arma en días; el catálogo puede salir de una planilla o de un CMS."]],
       related=["arquitecturas/jamstack", "servicios/sanity", "stacks/astro"]),
  dict(id="blog", name="Blog / sitio de contenidos", summary="Artículos, guías o novedades para atraer tráfico orgánico y construir autoridad.",
       tags=["SEO", "contenido", "CMS"],
       fields=[["Cuándo conviene", "Estrategias de SEO, marca personal, documentar conocimiento (como el Lab de ML de esta web)."],
               ["Funcionalidades clave", "Editor cómodo, categorías y etiquetas, buscador, RSS, datos estructurados (schema.org), imágenes optimizadas."],
               ["Complejidad", "Baja a media"]],
       related=["arquitecturas/jamstack", "arquitecturas/headless-cms", "stacks/astro", "servicios/wordpress"]),
  dict(id="saas", name="SaaS / aplicación web", summary="Software que se usa desde el navegador, con usuarios, datos propios y lógica de negocio.",
       tags=["app", "usuarios", "suscripción"],
       fields=[["Cuándo conviene", "Herramientas que resuelven un problema recurrente: gestión, automatización, análisis."],
               ["Funcionalidades clave", "Registro e inicio de sesión, roles, base de datos, panel, planes y cobros, emails, auditoría de acciones."],
               ["Complejidad", "Alta"],
               ["Ejemplo propio", "ML Tracker: JavaScript sin framework + funciones serverless en Node (Vercel) + MongoDB + OAuth de Mercado Libre."]],
       related=["arquitecturas/spa-api", "arquitecturas/baas", "servicios/supabase", "servicios/clerk", "stacks/mern"]),
  dict(id="dashboard", name="Dashboard / panel de gestión", summary="Pantallas con métricas, tablas y acciones para operar un negocio o un sistema.",
       tags=["datos", "admin", "interno"],
       fields=[["Cuándo conviene", "Seguimiento de KPIs, back-office, paneles de administración de otra web."],
               ["Funcionalidades clave", "Gráficos, filtros por fecha, tablas con orden y búsqueda, exportar a CSV/PDF, permisos."],
               ["Complejidad", "Media a alta"],
               ["Clave de diseño", "Densidad de información sin ruido: jerarquía clara, pocos colores con significado, estados vacíos y de carga."]],
       related=["arquitecturas/spa-api", "stacks/react-vite", "estilos"]),
  dict(id="reservas", name="Reservas y turnos", summary="Agenda online para que los clientes reserven y paguen sin llamar.",
       tags=["servicios", "agenda", "pagos"],
       fields=[["Cuándo conviene", "Consultorios, peluquerías, canchas, profesionales independientes."],
               ["Funcionalidades clave", "Calendario con disponibilidad real, recordatorios por email/WhatsApp, seña con Mercado Pago, cancelaciones."],
               ["Complejidad", "Media"]],
       related=["arquitecturas/baas", "servicios/supabase", "servicios/mercadopago", "servicios/resend"]),
  dict(id="marketplace", name="Marketplace", summary="Plataforma donde muchos vendedores publican y muchos compradores compran.",
       tags=["multi-vendedor", "pagos divididos"],
       fields=[["Cuándo conviene", "Cuando el valor está en juntar oferta y demanda de un nicho."],
               ["Funcionalidades clave", "Alta de vendedores, moderación, reputación, pagos divididos, mensajería, disputas."],
               ["Complejidad", "Muy alta"]],
       related=["arquitecturas/spa-api", "arquitecturas/microservicios", "servicios/mercadopago"]),
  dict(id="interna", name="Herramienta interna", summary="Una web que usa sólo un equipo para ordenar un proceso: carga de datos, verificaciones, reportes.",
       tags=["equipo", "procesos", "productividad"],
       fields=[["Cuándo conviene", "Cuando un proceso vive en planillas sueltas o mensajes y se pierde información."],
               ["Funcionalidades clave", "Login, formularios de carga con validación, historial, exportar, permisos por rol."],
               ["Complejidad", "Baja a media"],
               ["Tip", "Una sola página bien hecha resuelve mucho: empezá por el flujo más usado."]],
       related=["arquitecturas/baas", "servicios/supabase", "stacks/vanilla"]),
  dict(id="docs", name="Documentación / base de conocimiento", summary="Contenido técnico o procedimientos organizados para consultar rápido.",
       tags=["contenido", "buscador"],
       fields=[["Cuándo conviene", "Manuales, onboarding de equipos, guías de producto, bases como este Lab."],
               ["Funcionalidades clave", "Buscador, índice lateral, enlaces profundos, versionado, modo oscuro."],
               ["Complejidad", "Baja"]],
       related=["arquitecturas/jamstack", "stacks/astro"]),
  dict(id="pwa", name="PWA (web instalable)", summary="Web que se instala como app en el celular y puede funcionar sin conexión.",
       tags=["mobile", "offline"],
       fields=[["Cuándo conviene", "Cuando necesitás “una app” pero no querés publicar en las tiendas ni mantener dos códigos."],
               ["Funcionalidades clave", "Manifest, service worker, caché offline, notificaciones push (con limitaciones en iOS)."],
               ["Complejidad", "Media"]],
       related=["arquitecturas/spa-api", "stacks/react-vite"]),
]

ARQUITECTURAS = [
  dict(id="estatico", name="Sitio estático", summary="Archivos HTML, CSS y JS servidos tal cual desde un CDN. Sin servidor que procese cada visita.",
       tags=["simple", "rápido", "barato"],
       fields=[["Cómo funciona", "Escribís (o generás) los archivos una vez y el hosting los entrega directo al navegador."],
               ["Ventajas", "Rapidísimo, casi gratis, muy seguro (no hay servidor que atacar), fácil de mantener."],
               ["Desventajas", "Cualquier dato dinámico (formularios, login) necesita un servicio externo o funciones serverless."],
               ["Cuándo usarla", "Landings, portfolios, institucionales, documentación."],
               ["Hosting", "Vercel, Netlify, Cloudflare Pages, GitHub Pages."]],
       related=["arquitecturas/serverless", "servicios/vercel", "servicios/netlify", "stacks/vanilla"]),
  dict(id="jamstack", name="JAMstack / generación estática (SSG)", summary="Un generador arma las páginas en el build a partir de datos (Markdown, CMS, APIs) y se publican como estáticas.",
       tags=["SEO", "rendimiento", "build"],
       fields=[["Cómo funciona", "En cada publicación se corre un build que genera todo el HTML; los datos pueden venir de un CMS headless."],
               ["Ventajas", "Velocidad de sitio estático con contenido editable; excelente SEO."],
               ["Desventajas", "Cada cambio de contenido requiere un nuevo build (segundos o minutos)."],
               ["Tecnologías", "Astro, Next.js (export estático), Eleventy, Hugo."]],
       related=["stacks/astro", "arquitecturas/headless-cms", "servicios/sanity"]),
  dict(id="spa-api", name="SPA + API REST", summary="Frontend en React/Vue que corre en el navegador y habla con una API separada que tiene la lógica y los datos.",
       tags=["apps", "separación", "JSON"],
       fields=[["Cómo funciona", "El navegador descarga la app una vez y después pide datos a la API (JSON). Frontend y backend se despliegan por separado."],
               ["Ventajas", "Experiencia fluida tipo app, equipos y deploys independientes, la API sirve también a una app mobile."],
               ["Desventajas", "SEO más difícil, primera carga más pesada, hay que manejar CORS y autenticación."],
               ["Ejemplo propio", "ML Tracker aplica la idea: el panel es una app en JavaScript sin framework que le pide JSON a /api/tracker (una función serverless con MongoDB). Frontend y API se publican juntos en Vercel."]],
       related=["stacks/react-vite", "stacks/mern", "servicios/railway", "servicios/mongodb-atlas"]),
  dict(id="ssr", name="SSR (renderizado en el servidor)", summary="El servidor arma el HTML de cada página en el momento en que se pide, con los datos al día.",
       tags=["SEO", "dinámico"],
       fields=[["Cómo funciona", "Cada visita ejecuta código en el servidor que consulta datos y devuelve HTML listo."],
               ["Ventajas", "SEO excelente con contenido siempre actualizado; buena primera carga."],
               ["Desventajas", "Necesita servidor o funciones activas; más costo y complejidad que lo estático."],
               ["Tecnologías", "Next.js, Nuxt, SvelteKit, Remix."]],
       related=["stacks/nextjs", "arquitecturas/hibrida"]),
  dict(id="hibrida", name="Híbrida (estático + dinámico por página)", summary="Cada página elige: estática, regenerada cada tanto o renderizada al vuelo. Lo mejor de cada mundo.",
       tags=["moderno", "flexible"],
       fields=[["Cómo funciona", "Frameworks como Next.js o Astro permiten mezclar páginas estáticas, ISR (regeneración incremental) y SSR."],
               ["Ventajas", "Rendimiento donde importa y datos frescos donde hace falta."],
               ["Desventajas", "Más conceptos para aprender; depende bastante del hosting."]],
       related=["stacks/nextjs", "stacks/astro", "servicios/vercel"]),
  dict(id="serverless", name="Funciones serverless", summary="Pequeñas funciones backend que se ejecutan a demanda. Pagás por uso y no administrás servidores.",
       tags=["backend", "escala", "sin servidor"],
       fields=[["Cómo funciona", "Cada endpoint es un archivo (por ej. /api/contact.js) que el proveedor ejecuta cuando llega una petición."],
               ["Ventajas", "Escala solo, costo cero o casi cero con poco tráfico, deploy junto al frontend."],
               ["Desventajas", "Arranque en frío, límite de tiempo por ejecución, la memoria no persiste entre llamadas (usar base de datos)."],
               ["Ejemplo propio", "Esta web: /api/audit, /api/contact y /api/content corren como funciones en Vercel."]],
       related=["servicios/vercel", "servicios/netlify", "servicios/mongodb-atlas"]),
  dict(id="monolito", name="Monolito (MVC)", summary="Una sola aplicación que tiene todo: rutas, lógica, vistas y acceso a datos.",
       tags=["clásico", "simple de desplegar"],
       fields=[["Cómo funciona", "Un servidor (Express, Laravel, Django, Rails) recibe la petición, consulta la base y renderiza la vista."],
               ["Ventajas", "Simple de entender y desplegar; ideal para equipos chicos."],
               ["Desventajas", "Con el tiempo cuesta escalar partes por separado."],
               ["Tecnologías", "Express + plantillas, Laravel, Django, Rails."]],
       related=["servicios/railway", "servicios/render"]),
  dict(id="baas", name="BaaS (Backend as a Service)", summary="Base de datos, autenticación, archivos y APIs listos como servicio. Escribís casi sólo frontend.",
       tags=["rápido", "auth incluida"],
       fields=[["Cómo funciona", "El servicio expone la base de datos con reglas de seguridad y SDKs; el frontend lo usa directo."],
               ["Ventajas", "Salís a producción muy rápido: login, base, storage y tiempo real sin armar backend."],
               ["Desventajas", "Dependés del proveedor; la lógica compleja termina necesitando funciones propias."],
               ["Tecnologías", "Supabase, Firebase, Appwrite."]],
       related=["servicios/supabase", "servicios/firebase"]),
  dict(id="headless-cms", name="Headless CMS", summary="El contenido se edita en un panel y se consume por API desde cualquier frontend.",
       tags=["contenido", "editores"],
       fields=[["Cómo funciona", "El CMS guarda textos e imágenes; tu web (estática o SSR) los pide por API y los muestra con tu diseño."],
               ["Ventajas", "Clientes editan sin tocar código; mismo contenido para web y app."],
               ["Desventajas", "Un servicio más que mantener; costo al crecer."],
               ["Tecnologías", "Sanity, Strapi, Contentful, WordPress en modo headless."]],
       related=["servicios/sanity", "servicios/wordpress", "arquitecturas/jamstack"]),
  dict(id="ecommerce-saas", name="Plataforma de e-commerce", summary="La tienda corre sobre una plataforma que ya resuelve carrito, pagos, stock y envíos.",
       tags=["ventas", "sin programar"],
       fields=[["Cómo funciona", "Elegís un tema, cargás productos y conectás pagos y envíos. Se personaliza con temas y apps."],
               ["Ventajas", "Tienda lista en días, seguridad y pagos resueltos, integraciones con Mercado Libre."],
               ["Desventajas", "Comisión o abono mensual, personalización limitada al sistema de la plataforma."],
               ["Tecnologías", "Tienda Nube, Shopify, WooCommerce."]],
       related=["servicios/tiendanube", "servicios/mercadopago"]),
  dict(id="microservicios", name="Microservicios", summary="El sistema se divide en servicios chicos e independientes que se comunican por red.",
       tags=["escala", "equipos grandes"],
       fields=[["Cómo funciona", "Cada servicio tiene su propia base y deploy; se hablan por HTTP o colas de mensajes."],
               ["Ventajas", "Escalar y desplegar partes por separado; equipos autónomos."],
               ["Desventajas", "Mucha complejidad operativa. Para proyectos chicos es sobreingeniería."],
               ["Cuándo usarla", "Sistemas grandes con varios equipos. Casi nunca para empezar."]],
       related=["arquitecturas/monolito"]),
]

SERVICIOS = [
  dict(id="vercel", name="Vercel", summary="Hosting para frontends y funciones serverless con deploy automático desde Git.",
       tags=["hosting", "serverless", "plan gratuito"], fields=[["Para qué", "Publicar sitios estáticos, Next.js y funciones /api."], ["Por qué elegirlo", "Deploy con cada push, previews por rama, dominio y HTTPS automáticos."], ["Ojo con", "Límites de tiempo por función y de uso en el plan gratuito; revisá los precios vigentes."], ["Lo uso en", "Esta web (frontend + /api)."], ["Sitio", "https://vercel.com"]],
       related=["arquitecturas/serverless", "arquitecturas/estatico"]),
  dict(id="netlify", name="Netlify", summary="Hosting de sitios estáticos con funciones, formularios y deploy desde Git.",
       tags=["hosting", "serverless", "plan gratuito"], fields=[["Para qué", "Sitios estáticos y JAMstack."], ["Por qué elegirlo", "Formularios integrados sin backend, redirects simples, previews."], ["Sitio", "https://www.netlify.com"]],
       related=["arquitecturas/jamstack"]),
  dict(id="cloudflare-pages", name="Cloudflare Pages", summary="Hosting estático sobre la red de Cloudflare, con Workers para lógica en el borde.",
       tags=["hosting", "CDN", "plan gratuito"], fields=[["Para qué", "Sitios estáticos muy rápidos en todo el mundo."], ["Por qué elegirlo", "CDN enorme, DNS y dominio en el mismo lugar."], ["Sitio", "https://pages.cloudflare.com"]], related=["arquitecturas/estatico"]),
  dict(id="github-pages", name="GitHub Pages", summary="Hosting gratuito de sitios estáticos directo desde un repositorio.",
       tags=["hosting", "gratis"], fields=[["Para qué", "Portfolios, documentación, demos."], ["Limitación", "Sólo estático: sin funciones de servidor."], ["Sitio", "https://pages.github.com"]], related=["arquitecturas/estatico"]),
  dict(id="railway", name="Railway", summary="Plataforma para desplegar servidores Node, bases de datos y workers sin configurar infraestructura.",
       tags=["hosting", "backend", "bases de datos"], fields=[["Para qué", "APIs que necesitan estar siempre encendidas (Express, cron jobs)."], ["Sitio", "https://railway.app"]], related=["arquitecturas/spa-api", "arquitecturas/monolito"]),
  dict(id="render", name="Render", summary="Hosting de servicios web, bases Postgres y sitios estáticos.",
       tags=["hosting", "backend"], fields=[["Para qué", "Alternativa a Railway para APIs y monolitos."], ["Sitio", "https://render.com"]], related=["arquitecturas/monolito"]),
  dict(id="mongodb-atlas", name="MongoDB Atlas", summary="MongoDB administrado en la nube.",
       tags=["base de datos", "NoSQL", "plan gratuito"], fields=[["Para qué", "Guardar documentos JSON: contenido, usuarios, mensajes, snapshots."], ["Lo uso en", "Esta web (contenido, mensajes, token de ML) y ML Tracker."], ["Tip", "En serverless reutilizá la conexión entre llamadas (ver api/db.js)."], ["Sitio", "https://www.mongodb.com/atlas"]], related=["arquitecturas/serverless", "stacks/mern"]),
  dict(id="supabase", name="Supabase", summary="Postgres + autenticación + storage + tiempo real, como servicio.",
       tags=["base de datos", "auth", "BaaS", "plan gratuito"], fields=[["Para qué", "Apps con usuarios y datos relacionales sin armar backend."], ["Por qué elegirlo", "SQL de verdad, reglas de seguridad por fila, SDK muy simple."], ["Sitio", "https://supabase.com"]], related=["arquitecturas/baas"]),
  dict(id="firebase", name="Firebase", summary="Suite de Google: base en tiempo real, autenticación, hosting y notificaciones.",
       tags=["BaaS", "auth", "mobile"], fields=[["Para qué", "Apps con tiempo real y login social rápido."], ["Sitio", "https://firebase.google.com"]], related=["arquitecturas/baas"]),
  dict(id="clerk", name="Clerk", summary="Autenticación lista: login, registro, social, organizaciones y componentes de UI.",
       tags=["auth"], fields=[["Para qué", "No reinventar el login en un SaaS."], ["Alternativas", "Auth0, Supabase Auth, NextAuth/Auth.js."], ["Sitio", "https://clerk.com"]], related=["soluciones/saas"]),
  dict(id="resend", name="Resend", summary="API para enviar emails transaccionales desde tu código.",
       tags=["email", "API", "plan gratuito"], fields=[["Para qué", "Avisos de formularios, confirmaciones, recuperación de contraseña."], ["Lo uso en", "Opcional en /api/contact de esta web: si está configurado, te llega un mail por cada mensaje."], ["Sitio", "https://resend.com"]], related=["servicios/formspree"]),
  dict(id="formspree", name="Formspree", summary="Backend para formularios: apuntás el form a su URL y te llegan los mensajes por mail.",
       tags=["formularios", "sin backend"], fields=[["Para qué", "Sitios estáticos que necesitan un formulario sin programar servidor."], ["Sitio", "https://formspree.io"]], related=["arquitecturas/estatico"]),
  dict(id="mercadopago", name="Mercado Pago", summary="Pagos online en Argentina: checkout, links de pago, suscripciones.",
       tags=["pagos", "Argentina"], fields=[["Para qué", "Cobrar con tarjetas, dinero en cuenta y cuotas."], ["Integración", "Checkout Pro (redirige a MP) o Checkout API (formulario propio). Siempre confirmar pagos por webhook."], ["Sitio", "https://www.mercadopago.com.ar/developers"]], related=["soluciones/ecommerce", "soluciones/reservas"]),
  dict(id="stripe", name="Stripe", summary="Pagos y suscripciones a nivel internacional.",
       tags=["pagos", "internacional"], fields=[["Para qué", "SaaS que cobran en dólares o a clientes del exterior."], ["Sitio", "https://stripe.com"]], related=["soluciones/saas"]),
  dict(id="tiendanube", name="Tienda Nube", summary="Plataforma de e-commerce líder en Latinoamérica.",
       tags=["e-commerce", "Argentina"], fields=[["Para qué", "Tienda propia sin programar, con integración a Mercado Libre y medios de pago locales."], ["Lo uso en", "Diseño de la tienda de Borner."], ["Sitio", "https://www.tiendanube.com"]], related=["arquitecturas/ecommerce-saas"]),
  dict(id="wordpress", name="WordPress", summary="El CMS más usado del mundo; con WooCommerce también es tienda.",
       tags=["CMS", "blog", "plugins"], fields=[["Para qué", "Institucionales y blogs que el cliente edita solo."], ["Ojo con", "Mantener plugins y versión actualizados por seguridad."], ["Sitio", "https://wordpress.org"]], related=["arquitecturas/headless-cms", "arquitecturas/monolito"]),
  dict(id="sanity", name="Sanity", summary="Headless CMS con editor personalizable y API de contenido.",
       tags=["CMS", "headless"], fields=[["Para qué", "Contenido editable para sitios hechos a medida (Astro, Next)."], ["Sitio", "https://www.sanity.io"]], related=["arquitecturas/headless-cms"]),
  dict(id="ga4", name="Google Analytics 4", summary="Medición de tráfico y conversiones.",
       tags=["analítica", "gratis"], fields=[["Para qué", "Saber de dónde vienen las visitas y qué convierte."], ["Ojo con", "Requiere aviso de cookies según el público; alternativa liviana: Plausible."], ["Sitio", "https://analytics.google.com"]], related=["servicios/clarity", "servicios/plausible"]),
  dict(id="plausible", name="Plausible", summary="Analítica simple, liviana y respetuosa de la privacidad.",
       tags=["analítica", "privacidad"], fields=[["Para qué", "Métricas básicas sin cookies ni banners."], ["Sitio", "https://plausible.io"]], related=["servicios/ga4"]),
  dict(id="clarity", name="Microsoft Clarity", summary="Mapas de calor y grabaciones de sesiones, gratis.",
       tags=["analítica", "UX", "gratis"], fields=[["Para qué", "Ver dónde hacen clic y dónde abandonan los usuarios."], ["Sitio", "https://clarity.microsoft.com"]], related=["servicios/ga4"]),
  dict(id="cloudinary", name="Cloudinary", summary="Almacenamiento y transformación de imágenes y videos al vuelo.",
       tags=["imágenes", "CDN"], fields=[["Para qué", "Servir la imagen justa (tamaño, formato WebP/AVIF) a cada dispositivo."], ["Sitio", "https://cloudinary.com"]], related=["soluciones/ecommerce"]),
  dict(id="claude-api", name="Claude API (Anthropic)", summary="Modelos de IA para generar y analizar texto, código e imágenes.",
       tags=["IA", "API"], fields=[["Para qué", "Redactar títulos y descripciones, resumir, clasificar, asistentes."], ["Sitio", "https://docs.anthropic.com"]], related=["servicios/groq"]),
  dict(id="groq", name="Groq", summary="Inferencia muy rápida de modelos abiertos (Llama y otros).",
       tags=["IA", "API", "plan gratuito"], fields=[["Para qué", "Tareas de IA rápidas y baratas."], ["Lo uso en", "Opcional en la auditoría de esta web: sugiere un título optimizado."], ["Sitio", "https://groq.com"]], related=["servicios/claude-api"]),
  dict(id="sentry", name="Sentry", summary="Monitoreo de errores en frontend y backend.",
       tags=["monitoreo"], fields=[["Para qué", "Enterarte de los errores antes que tus usuarios."], ["Sitio", "https://sentry.io"]], related=[]),
  dict(id="nic-ar", name="NIC Argentina", summary="Registro oficial de dominios .ar / .com.ar.",
       tags=["dominio", "Argentina"], fields=[["Para qué", "Registrar el dominio .com.ar de un negocio local."], ["Tip", "Después apuntás el DNS al hosting (Vercel, Netlify, etc.)."], ["Sitio", "https://nic.ar"]], related=["servicios/vercel"]),
]

STACKS = [
  dict(id="vanilla", name="HTML + CSS + JavaScript", summary="La web sin frameworks. Lo que entiende el navegador de forma nativa.",
       tags=["base", "sin build"], fields=[["Curva de aprendizaje", "Baja: es el punto de partida obligado."], ["Ideal para", "Landings, portfolios, herramientas internas chicas."], ["Lo uso en", "Esta web."]], related=["arquitecturas/estatico"]),
  dict(id="react-vite", name="React + Vite", summary="Librería de componentes más usada, con Vite como herramienta de desarrollo rápida.",
       tags=["frontend", "SPA"], fields=[["Curva de aprendizaje", "Media."], ["Ideal para", "Apps interactivas, dashboards."]], related=["arquitecturas/spa-api"]),
  dict(id="nextjs", name="Next.js", summary="Framework de React con rutas, SSR, SSG y API integradas.",
       tags=["fullstack", "SSR", "SEO"], fields=[["Curva de aprendizaje", "Media a alta."], ["Ideal para", "E-commerce a medida, SaaS con SEO, sitios híbridos."]], related=["arquitecturas/ssr", "arquitecturas/hibrida", "servicios/vercel"]),
  dict(id="astro", name="Astro", summary="Framework orientado a contenido: HTML estático por defecto e interactividad sólo donde hace falta.",
       tags=["contenido", "rendimiento"], fields=[["Curva de aprendizaje", "Baja a media."], ["Ideal para", "Blogs, docs, institucionales, landings."]], related=["arquitecturas/jamstack"]),
  dict(id="vue", name="Vue / Nuxt", summary="Alternativa a React con sintaxis más cercana al HTML; Nuxt agrega SSR y rutas.",
       tags=["frontend", "SSR"], fields=[["Curva de aprendizaje", "Baja a media."], ["Ideal para", "Equipos que prefieren plantillas; apps y sitios."]], related=["arquitecturas/ssr"]),
  dict(id="sveltekit", name="SvelteKit", summary="Framework con compilador que genera muy poco JavaScript.",
       tags=["frontend", "rendimiento"], fields=[["Curva de aprendizaje", "Baja a media."], ["Ideal para", "Apps rápidas y livianas."]], related=["arquitecturas/hibrida"]),
  dict(id="node-express", name="Node.js + Express", summary="JavaScript en el servidor con el framework de APIs más difundido.",
       tags=["backend", "API"], fields=[["Curva de aprendizaje", "Media."], ["Ideal para", "APIs REST, integraciones, automatizaciones."], ["Lo uso en", "Node sí: las funciones /api de esta web y de ML Tracker corren en Node como funciones serverless, sin Express."]], related=["arquitecturas/spa-api", "arquitecturas/monolito"]),
  dict(id="mern", name="MERN (MongoDB, Express, React, Node)", summary="Stack completo en JavaScript de punta a punta.",
       tags=["fullstack"], fields=[["Ideal para", "SaaS y apps con datos flexibles."]], related=["servicios/mongodb-atlas", "stacks/react-vite", "stacks/node-express"]),
  dict(id="tailwind", name="Tailwind CSS", summary="CSS con clases utilitarias directamente en el HTML.",
       tags=["estilos", "CSS"], fields=[["Ideal para", "Iterar diseño rápido y mantener consistencia con tokens."], ["Combina con", "shadcn/ui, React, Astro."]], related=["stacks/shadcn"]),
  dict(id="shadcn", name="shadcn/ui", summary="Componentes accesibles (Radix) que copiás a tu proyecto y adaptás con Tailwind.",
       tags=["componentes", "React"], fields=[["Ideal para", "Dashboards y SaaS con UI prolija sin diseñar cada componente."]], related=["stacks/tailwind", "stacks/react-vite"]),
]


# ── Ejemplos reales de cada tipo de web (sitios públicos y conocidos) ──
EJEMPLOS = {
  "landing":       [["Linear", "https://linear.app"], ["Vercel", "https://vercel.com"]],
  "institucional": [["Arcor", "https://www.arcor.com"], ["YPF", "https://www.ypf.com"]],
  "portfolio":     [["Brittany Chiang", "https://brittanychiang.com"], ["Esta web", "index.html"]],
  "ecommerce":     [["Frávega", "https://www.fravega.com"], ["Garbarino", "https://www.garbarino.com"]],
  "blog":          [["CSS-Tricks", "https://css-tricks.com"], ["Smashing Magazine", "https://www.smashingmagazine.com"]],
  "saas":          [["Notion", "https://www.notion.com"], ["Trello", "https://trello.com"]],
  "dashboard":     [["ML Tracker", "herramientas.html#tracker"]],
  "reservas":      [["Calendly", "https://calendly.com"]],
  "marketplace":   [["Mercado Libre", "https://www.mercadolibre.com.ar"], ["Airbnb", "https://www.airbnb.com.ar"]],
  "interna":       [["Panel admin de esta web (privado)", "admin.html"]],
  "docs":          [["MDN Web Docs", "https://developer.mozilla.org"], ["Mercado Libre Developers", "https://developers.mercadolibre.com.ar"]],
  "pwa":           [["Starbucks (PWA)", "https://app.starbucks.com"], ["X", "https://x.com"]],
}

# ── Flujo de cada arquitectura: cómo viaja un pedido (se dibuja como diagrama) ──
FLUJOS = {
  "estatico":       [["Navegador", "pide la página"], ["CDN", "entrega HTML, CSS y JS ya hechos"]],
  "jamstack":       [["Build", "genera las páginas una vez"], ["CDN", "las sirve"], ["Navegador", "suma datos vía APIs"]],
  "spa-api":        [["Navegador", "app React que se arma sola"], ["API REST", "responde JSON"], ["Base de datos", "guarda y consulta"]],
  "ssr":            [["Navegador", "pide la página"], ["Servidor", "arma el HTML en cada pedido"], ["Base de datos", "aporta los datos"]],
  "hibrida":        [["Navegador", "pide la página"], ["Framework", "decide: estática o dinámica"], ["CDN o servidor", "según la página"]],
  "serverless":     [["Navegador", "página estática"], ["Función /api", "se ejecuta sólo cuando la llaman"], ["Base de datos", "persiste"]],
  "monolito":       [["Navegador", "pide la página"], ["Aplicación única", "rutas, vistas y lógica juntas"], ["Base de datos", "una sola"]],
  "baas":           [["Navegador", "tu frontend"], ["BaaS", "auth, base y archivos listos"]],
  "headless-cms":   [["Editor", "carga contenido"], ["CMS headless", "lo expone por API"], ["Frontend", "lo muestra donde quieras"]],
  "ecommerce-saas": [["Comprador", "navega la tienda"], ["Plataforma", "catálogo, carrito y stock"], ["Pasarela de pago", "cobra"]],
  "microservicios": [["Navegador", "una app"], ["API Gateway", "reparte los pedidos"], ["Servicios", "usuarios, pedidos, pagos"], ["Bases propias", "una por servicio"]],
}
