# -*- coding: utf-8 -*-
"""
Skills de Claude para el Lab de Programación (categoría "Skills").
Fuentes verificadas en sep-2026:
  - Oficiales: https://github.com/anthropics/skills (carpeta skills/)
  - Comunitarias: repos de cada autor (ver "source").
Cada entrada: id, name, summary, tags, fields, install (comandos), prompt (ejemplo de uso), source (URL).
"""

OFICIAL = "https://github.com/anthropics/skills/tree/main/skills/"
INST_DOCS = "/plugin marketplace add anthropics/skills\n/plugin install document-skills@anthropic-agent-skills"
INST_EJ   = "/plugin marketplace add anthropics/skills\n/plugin install example-skills@anthropic-agent-skills"

def of(id, name, summary, tags, que, cuando, prompt, docs=False):
    return dict(id=id, name=name, summary=summary, tags=["Oficial Anthropic"] + tags,
                fields=[["Qué hace", que], ["Cuándo usarla", cuando], ["Autor", "Anthropic"]],
                install=INST_DOCS if docs else INST_EJ, prompt=prompt, source=OFICIAL + id)

def com(id, name, summary, tags, que, cuando, autor, install, prompt, source):
    return dict(id=id, name=name, summary=summary, tags=["Comunidad"] + tags,
                fields=[["Qué hace", que], ["Cuándo usarla", cuando], ["Autor", autor]],
                install=install, prompt=prompt, source=source)

SKILLS = [
  # ── Oficiales de Anthropic ──
  of("frontend-design", "Frontend Design", "Empuja a Claude a diseñar interfaces con personalidad en vez de la estética genérica de IA.",
     ["Diseño", "Frontend"],
     "Antes de escribir código, elige una dirección visual clara (tipografía, color, composición) y la ejecuta con detalle. Es la skill de diseño más instalada.",
     "Landings, portfolios, componentes y cualquier interfaz que no querés que parezca hecha por una plantilla.",
     "Diseñá la landing de una marca de utensilios de cocina alemanes: tiene que sentirse premium y distinta, nada de degradés violetas."),
  of("skill-creator", "Skill Creator", "La skill para crear, mejorar y medir otras skills.",
     ["Meta", "Productividad"],
     "Te guía para escribir el SKILL.md, arma casos de prueba (evals) y compara el rendimiento con y sin la skill.",
     "Cuando repetís siempre las mismas instrucciones y querés empaquetarlas para que Claude las use solo.",
     "Creá una skill que audite publicaciones de Mercado Libre con mi checklist de 7 fotos, título de 60 caracteres y atributos completos."),
  of("xlsx", "Excel (xlsx)", "Crear, leer y editar planillas de Excel con fórmulas, formato y gráficos.",
     ["Documentos", "Datos"],
     "Genera archivos .xlsx reales: fórmulas que funcionan, formatos, varias hojas, gráficos y limpieza de datos desordenados.",
     "Reportes de ventas, control de stock, análisis de ACOS o cualquier planilla que después abrís en Excel.",
     "Con este CSV de ventas armame un Excel con una hoja por marca, margen por SKU y un gráfico de ACOS semanal.", docs=True),
  of("docx", "Word (docx)", "Documentos de Word con formato profesional: títulos, tablas, índices y control de cambios.",
     ["Documentos"],
     "Crea y edita .docx preservando estilos; también lee documentos existentes y trabaja con comentarios y cambios marcados.",
     "Informes, propuestas, manuales de procedimientos o cualquier entrega que tenga que ser un Word.",
     "Escribí en Word el informe de auditoría del catálogo: resumen ejecutivo, tabla de publicaciones críticas y plan de 30 días.", docs=True),
  of("pptx", "PowerPoint (pptx)", "Presentaciones de PowerPoint desde cero o a partir de una plantilla.",
     ["Documentos", "Presentaciones"],
     "Arma diapositivas con layouts, gráficos y notas del orador; puede leer y reorganizar presentaciones existentes.",
     "Presentar resultados a la gerencia, pitch de un proyecto o un reporte mensual.",
     "Armá una presentación de 8 diapositivas con los resultados del trimestre: facturación, ACOS y próximas acciones.", docs=True),
  of("pdf", "PDF", "Leer, crear, unir, dividir y completar PDFs.",
     ["Documentos"],
     "Extrae texto y tablas, une o separa archivos, completa formularios, agrega marcas de agua y aplica OCR a escaneos.",
     "Facturas, catálogos de proveedores en PDF, formularios o documentos escaneados.",
     "Sacame en una tabla los códigos, descripciones y precios de este catálogo de proveedor en PDF.", docs=True),
  of("webapp-testing", "Webapp Testing", "Prueba aplicaciones web locales manejando un navegador con Playwright.",
     ["Desarrollo", "Testing"],
     "Abre tu app, hace clics, completa formularios, saca capturas y revisa errores de consola para verificar que todo funcione.",
     "Después de un cambio en el frontend, para comprobar flujos completos sin hacerlo a mano.",
     "Probá el formulario de contacto en localhost:3000: enviá uno válido, uno con email roto y sacá captura de cada estado."),
  of("mcp-builder", "MCP Builder", "Guía para construir servidores MCP que conectan a Claude con APIs y herramientas.",
     ["Desarrollo", "Integraciones"],
     "Ayuda a diseñar las herramientas, escribir el servidor (TypeScript o Python) y probarlo con buenas prácticas.",
     "Cuando querés que Claude use directamente un servicio propio o una API externa.",
     "Armame un servidor MCP que consulte la API de Mercado Libre y devuelva el score de salud de una publicación."),
  of("claude-api", "Claude API", "Referencia actualizada para construir con la API de Claude y sus SDKs.",
     ["Desarrollo", "IA"],
     "Modelos vigentes, precios, streaming, tool use, caché de prompts y migraciones entre versiones.",
     "Al integrar Claude en una app propia, como el generador de títulos de ML Tracker.",
     "Sumá a mi backend en Node un endpoint que genere 3 títulos optimizados para Mercado Libre usando la API de Claude con streaming."),
  of("web-artifacts-builder", "Web Artifacts Builder", "Construye artifacts web complejos con React, Tailwind y shadcn/ui.",
     ["Frontend", "Prototipos"],
     "Arma aplicaciones de varios componentes con estado y rutas, empaquetadas en un solo HTML.",
     "Prototipos interactivos, calculadoras o mini apps para compartir con un link.",
     "Hacé una calculadora de rentabilidad para Mercado Libre: precio, costo, comisión, envío y ACOS, con el margen final en grande."),
  of("canvas-design", "Canvas Design", "Piezas visuales en PNG o PDF con criterio de diseño.",
     ["Diseño", "Gráfica"],
     "Primero define una filosofía visual y después compone afiches, portadas o gráficas estáticas.",
     "Flyers, portadas, banners o infografías que no necesitan ser interactivas.",
     "Diseñá una infografía vertical con los 4 beneficios de la mandolina Borner para usar como foto 6 de la publicación."),
  of("algorithmic-art", "Algorithmic Art", "Arte generativo con p5.js: aleatoriedad controlada, campos de flujo y partículas.",
     ["Diseño", "Creatividad"],
     "Crea piezas generativas reproducibles (con semilla) y permite explorar variaciones.",
     "Fondos únicos para una marca, visuales para redes o experimentación creativa.",
     "Generá un fondo abstracto con líneas que fluyan en amarillo y grafito para el hero de mi portfolio."),
  of("theme-factory", "Theme Factory", "Aplica temas visuales completos (colores y tipografías) a documentos y artifacts.",
     ["Diseño", "Branding"],
     "Trae temas prearmados y puede generar uno nuevo para aplicarlo de forma consistente.",
     "Cuando tenés varias piezas (presentación, informe, página) y querés que compartan identidad.",
     "Aplicale un tema sobrio y profesional a esta presentación de resultados."),
  of("brand-guidelines", "Brand Guidelines", "Aplica los colores y la tipografía oficiales de la marca Anthropic.",
     ["Branding"],
     "Ejemplo de cómo empaquetar un manual de marca en una skill para que todo salga con la identidad correcta.",
     "Como modelo para armar la skill del manual de marca de tu propia empresa.",
     "Tomando esta skill como base, armá una para el manual de marca de Borner con sus colores y tono."),
  of("internal-comms", "Internal Comms", "Redacta comunicaciones internas con los formatos que usan las empresas.",
     ["Escritura", "Empresa"],
     "Reportes de estado, novedades del equipo, resúmenes de incidentes, preguntas frecuentes.",
     "Cuando tenés que informar avances o problemas al equipo o a la gerencia de forma clara.",
     "Redactá el reporte semanal para gerencia: ventas +12%, ACOS 13%, tres publicaciones pausadas por falta de stock."),
  of("doc-coauthoring", "Doc Co-authoring", "Un flujo guiado para escribir documentos de a dos con Claude.",
     ["Escritura"],
     "Recolecta contexto, propone estructura, itera por secciones y verifica que el documento se entienda solo.",
     "Propuestas, especificaciones técnicas o documentos de decisión que necesitan varias vueltas.",
     "Ayudame a escribir la propuesta para rediseñar el catálogo de Vacu Vin: arrancá preguntándome lo que necesites."),
  of("slack-gif-creator", "Slack GIF Creator", "GIFs animados optimizados para Slack.",
     ["Creatividad"],
     "Genera animaciones cortas respetando los límites de tamaño y dimensiones de Slack.",
     "Celebraciones del equipo, reacciones o anuncios con un poco de humor.",
     "Hacé un GIF de un cohete despegando con el texto '¡Récord de ventas!' para el canal del equipo."),

  # ── Comunidad ──
  com("superpowers", "Superpowers", "La skill más popular de la comunidad: hace que Claude trabaje como un desarrollador senior con método.",
      ["Desarrollo", "Metodología"],
      "Brainstorming antes de programar, planes en tareas chicas, TDD y ejecución con subagentes. Aceptada en el marketplace oficial.",
      "Features medianas o grandes donde improvisar sale caro.",
      "Jesse Vincent (obra)", "npx skills add obra/superpowers",
      "Quiero sumar un módulo de alertas de stock al tracker: primero hacemos brainstorming y un plan, después lo implementás con tests.",
      "https://github.com/obra/superpowers"),
  com("impeccable", "Impeccable", "Vocabulario de diseño con comandos (polish, audit, critique, bolder…) para pulir interfaces.",
      ["Diseño", "Frontend", "La uso"],
      "Más de 20 comandos para criticar, auditar y mejorar UI: jerarquía, tipografía, color, accesibilidad, microinteracciones.",
      "Revisar y pulir una interfaz existente o dirigir el diseño con una palabra.",
      "Paul Bakaus", "npx skills add pbakaus/impeccable",
      "Hacé un audit de mi página de contacto y después un polish de lo que encuentres.",
      "https://github.com/pbakaus/impeccable"),
  com("ui-ux-pro-max", "UI UX Pro Max", "Base de conocimiento de diseño: estilos, paletas, tipografías y guías UX.",
      ["Diseño", "La uso"],
      "Trae decenas de estilos, paletas por rubro, combinaciones tipográficas y buenas prácticas UX. Las fichas de diseño de este Lab salen de esta skill.",
      "Elegir la dirección visual de un proyecto nuevo según el rubro.",
      "nextlevelbuilder", "npx skills add nextlevelbuilder/ui-ux-pro-max-skill",
      "Recomendame estilo, paleta y tipografías para la tienda online de una marca de vinos premium.",
      "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill"),
  com("web-design-guidelines", "Web Design Guidelines", "Audita interfaces contra más de 100 reglas de accesibilidad, rendimiento y UX.",
      ["Diseño", "Calidad"],
      "Revisa tu UI regla por regla y te devuelve los problemas priorizados.",
      "Antes de publicar un sitio o después de un rediseño.",
      "Vercel Labs", "npx skills add https://github.com/vercel-labs/agent-skills --skill web-design-guidelines",
      "Revisá mi home con las guías de diseño web y listame lo que está mal ordenado por importancia.",
      "https://github.com/vercel-labs/agent-skills"),
  com("react-best-practices", "React Best Practices", "Reglas de rendimiento para React y Next.js, ordenadas por impacto real.",
      ["Desarrollo", "React"],
      "Aplica decenas de reglas de rendimiento (renders, bundles, datos) priorizadas por lo que más mueve la aguja.",
      "Apps en React que se sienten lentas o antes de escalar un proyecto.",
      "Vercel Labs", "npx skills add https://github.com/vercel-labs/agent-skills --skill vercel-react-best-practices",
      "El dashboard del tracker tarda en cargar: revisalo con las buenas prácticas de React y proponé cambios.",
      "https://github.com/vercel-labs/agent-skills"),
  com("trailofbits", "Trail of Bits Security", "Análisis de seguridad con la metodología de una auditora profesional.",
      ["Seguridad"],
      "Corre análisis estático con herramientas como CodeQL y Semgrep siguiendo procesos de auditoría reales.",
      "Antes de publicar una app con login, pagos o datos de clientes.",
      "Trail of Bits", "npx skills add trailofbits/skills",
      "Auditá la seguridad de mi backend: login, tokens de Mercado Libre y el formulario de contacto.",
      "https://github.com/trailofbits/skills"),
  com("remotion", "Remotion Best Practices", "Experiencia de dominio para crear videos con código usando React y Remotion.",
      ["Video", "Creatividad"],
      "Guía para componer, animar y renderizar videos programáticos.",
      "Videos de producto, clips para redes o piezas que se generan en serie.",
      "Remotion", "npx skills add https://github.com/remotion-dev/skills --skill remotion-best-practices",
      "Hacé un video de 15 segundos que muestre el antes y después de la publicación de la mandolina.",
      "https://github.com/remotion-dev/skills"),
  com("grill-me", "Grill Me", "Claude te entrevista y cuestiona tus supuestos antes de construir.",
      ["Metodología", "Planificación"],
      "Hace preguntas incómodas sobre el diseño hasta que el plan cierra, antes de escribir una línea.",
      "Al arrancar una idea nueva, para no construir lo que no hacía falta.",
      "Matt Pocock", "npx skills add https://github.com/mattpocock/skills --skill grill-me",
      "Quiero armar un SaaS de auditoría de catálogos para vendedores de Mercado Libre. Grill me.",
      "https://github.com/mattpocock/skills"),

  # ── Marketing y publicidad ──
  com("claude-ads", "Claude Ads", "Equipo completo de publicidad paga: estrategia, auditoría, creatividades y reportes para Meta, Google, TikTok y 9 plataformas más.",
      ["Marketing", "Meta Ads", "Publicidad"],
      "34 skills y 25 agentes: plan de medios y presupuesto (ads-plan), especialista en Meta con píxel y Conversions API (ads-meta), conceptos y textos (ads-create), competencia en la biblioteca de anuncios (ads-competitor), cálculo de punto de equilibrio y ROAS (ads-math), imágenes (ads-generate) y reportes. Todo queda en borrador hasta que lo aprobás.",
      "Armar campañas de Meta Ads desde cero, auditar una cuenta que ya invierte o preparar el reporte mensual de un cliente. Para generar imágenes necesita la clave de un proveedor (Gemini, OpenAI o Replicate).",
      "Daniel Agrici", "/plugin marketplace add agricidaniel/claude-ads\n/plugin install claude-ads@ai-marketing-hub-claude-ads",
      "/ads plan: armá la estrategia de Meta Ads para lanzar la preventa de una tienda de TCG japonés con $300.000 por mes. Objetivo: reservas antes del 16/10.",
      "https://github.com/AgriciDaniel/claude-ads"),
  com("ad-creative", "Ad Creative", "Genera y escala anuncios: hooks, textos principales, títulos y variantes por formato.",
      ["Marketing", "Meta Ads", "Copy"],
      "Escribe anuncios en serie para Feed, Stories y Reels, propone qué formato conviene (UGC, video sin cara, estático) y arma la hoja de ruta de pruebas creativas.",
      "Cuando necesitás muchas variantes para testear o renovar anuncios que se cansaron.",
      "Corey Haines", "npx skills add https://github.com/coreyhaines31/marketingskills --skill ad-creative",
      "Escribí 10 hooks y 5 textos principales para un anuncio de Reels de booster boxes japonesas en preventa. Nada de urgencia inventada.",
      "https://github.com/coreyhaines31/marketingskills"),
  com("copywriting", "Copywriting", "Textos que venden para landings, fichas de producto y secciones de una web.",
      ["Marketing", "Copy"],
      "Propuesta de valor, títulos, llamados a la acción y estructura de página pensada para convertir, con la voz de la marca.",
      "Antes de lanzar una landing o cuando una página tiene visitas y no convierte.",
      "Corey Haines", "npx skills add https://github.com/coreyhaines31/marketingskills --skill copywriting",
      "Reescribí el hero de la tienda: tiene que quedar claro que es producto sellado original importado directo de Japón.",
      "https://github.com/coreyhaines31/marketingskills"),
  com("marketing-psychology", "Marketing Psychology", "Principios de comportamiento aplicados a vender: anclaje, prueba social, aversión a la pérdida.",
      ["Marketing", "Estrategia"],
      "Explica qué sesgo usar en cada situación y cómo aplicarlo sin manipular: precios, ofertas, orden de la información.",
      "Diseñar ofertas, precios de preventa o el mensaje de un anuncio.",
      "Corey Haines", "npx skills add https://github.com/coreyhaines31/marketingskills --skill marketing-psychology",
      "¿Cómo presento una preventa con seña del 30% para que se entienda el valor sin meter presión falsa?",
      "https://github.com/coreyhaines31/marketingskills"),
  com("image", "Image", "Imágenes de marketing con IA: piezas para redes, mockups de producto y banners.",
      ["Marketing", "Imágenes", "Creatividad"],
      "Elige el modelo según la pieza (FLUX, Gemini, Ideogram, GPT Image), arma los prompts y optimiza el resultado para web.",
      "Piezas para anuncios o redes cuando no hay fotos de producción. Funciona con ComfyUI local o con proveedores pagos.",
      "Corey Haines", "npx skills add https://github.com/coreyhaines31/marketingskills --skill image",
      "Armá 3 fondos para anuncios 4:5 estilo card shop de Akihabara de noche, con lugar para la foto del producto a la derecha.",
      "https://github.com/coreyhaines31/marketingskills"),
  com("video", "Video", "Producción de videos con IA o con código: demos, clips para redes y anuncios.",
      ["Marketing", "Video", "Creatividad"],
      "Elige entre video programático (Remotion, gratis), generación con IA (Veo, Kling, Runway) o avatares, y arma guion, escenas y render.",
      "Videos de anuncios para Reels y Stories, cuentas regresivas de lanzamientos o demos de producto.",
      "Corey Haines", "npx skills add https://github.com/coreyhaines31/marketingskills --skill video",
      "Hacé un video de Reels de 12 segundos con Remotion: cuenta regresiva al lanzamiento japonés del 16/10 y la caja al final.",
      "https://github.com/coreyhaines31/marketingskills"),
]
