export MONGO_URI=mongodb://127.0.0.1:27099/sdv_demo PORT=5099 NODE_ENV=development ADMIN_2FA=off
export ADMIN_EMAIL=demo@demo.test ADMIN_PASSWORD=demo-123456 JWT_SECRET=demo-secret-1 JWT_PACIENTE_SECRET=demo-secret-2
export SMTP_HOST=127.0.0.1 SMTP_PORT=1 SMTP_USER= SMTP_PASS= ADMIN_NOTIFY_EMAIL= MAIL_FROM= MAIL_REPLY_TO= CALLMEBOT_PHONE= CALLMEBOT_APIKEY=
export CLOUDINARY_URL=cloudinary://k:s@demo FRONTEND_URL=http://localhost:3099 RECAPTCHA_SECRET= GOOGLE_CLIENT_ID= GOOGLE_REVIEW_URL= EXTRA_ORIGINS=
